.editorconfig
.gitignore
dev/bootstrap.sh
dev/build.sh
dev/format.sh
dev/rm-caches.sh
dev/test.sh
dev/venv-create.sh
dev/venv-delete.sh
mypy.ini
pyproject.toml
src/flower/__init__.py
src/flower/server.py
src/flower/server_test.py

Create development helper scripts

---

src/flower/client.py
src/flower/client_test.py
src/flower/server.py
src/flower/server_test.py

Please note: The seemingly non-DRY code in module `server.py` (compare functions `fit_clients` and `eval_clients`) is intentional. This part is likely to change quite significantly and keeping those implementations slightly non-DRY will make those changes easier.

Add basic distributed evaluation

---

src/flower/client_manager.py

Purpose of the ClientManager is to provide an interface for the federated learning code to manage clients. A LocalClientManager and NetworkedClientManager will follow next.

Add abstract class ClientManager

---

pyproject.toml

...to bring it in line with the recommendation in https://python-poetry.org/docs/pyproject/

Update license string in pyproject.toml

---

src/flower/client.py
src/flower/client_manager.py
src/flower/client_manager_test.py
src/flower/client_test.py

After discussing we concluded that we will probably not need multiple implementations of the ClientManager

Add NetworkClient and SimpleClientManager

---

proto/flower/proto/transport.proto
src/flower/grpc_client/message_handler.py
src/flower/grpc_server/grpc_proxy_client.py
src/flower/grpc_server/grpc_proxy_client_test.py
src/flower/grpc_server/serde.py
src/flower/proto/transport_pb2.py
src/flower/proto/transport_pb2.pyi

Co-authored-by: Daniel J. Beutel <daniel@adap.com>

Add client and serverside message handling

---

src/flower/app.py
src/flower/grpc_client/connection.py
src/flower/logger.py
src/flower/server.py
src/flower_examples/tf_mnist_local.py

Adds custom logger which replaces all print statements.

Introduce a custom logger.

---

src/flower_ops/compute/ec2_adapter.py

- Change one EC2 instance type
- Show cost when starting instances

Improve EC2 Adapter

---

src/py/flwr_experimental/baseline/setting.py
src/py/flwr_experimental/baseline/tf_cifar/settings.py
src/py/flwr_experimental/baseline/tf_fashion_mnist/settings.py
src/py/flwr_experimental/baseline/tf_hotkey/settings.py

This PR addresses [this issue](https://github.com/adap/flower/issues/345). This is my first PR and I've tried adhering to most guidelines, apologies for any mistakes in that. I'm looking forward to contributing and submitting PRs to solve more of these issues.

Change Setting to Baseline

---

dev/bootstrap.sh
doc/source/conf.py
docker/default.Dockerfile
docker/sshd.Dockerfile
pyproject.toml

This updates the version number on master to 0.7.0 so the nightlies are versioned correctly after the 0.6.0 release is now published.

Prepare 0.7.0 release

---

src/py/flwr_experimental/ops/compute/ec2_adapter.py

To match with actual price and add one with more memory

Fix instance types

---

docker/sshd.Dockerfile
pyproject.toml

Upgrading torch to 1.7.0 and trochvision to 0.8.1

---

src/py/flwr/client/app.py
src/py/flwr/common/__init__.py

Add docstring for start_client and start_keras_client

---

src/py/flwr/server/app.py

Improve start_server docstring

---

src/py/flwr/server/strategy/strategy.py

Improve Strategy docstrings

---

doc/source/example_walkthrough_pytorch_mnist.rst
doc/source/index.rst
doc/source/pytorch_complete.rst
doc/source/quickstart_pytorch.rst

Make adjustment to pytorch documentation

add content for run-server.sh, run-client.sh, client.py and server.py.

---

.github/workflows/flower.yml
dev/format.sh
dev/test.sh
pyproject.toml

This PR will implement the docformatter to flower -> Refers to #473

Docformatter Flower

---

examples/quickstart_pytorch/README.md

I updated the example command, since this example is for pytorch, we are moving to pytorch directory not to tf.

Update examples/pytorch readme

---

examples/quickstart_pytorch/client.py

Fixed the issue related to the right use of the device on the Net() model class.

Fix bug Model device

---

doc/source/examples.rst

Document new examples (fixes #359)

---

doc/source/apiref-flwr.rst

Include init of FedAvg in docs

---

doc/source/_templates/sidebar.html

Set logo href to / in docs

---

examples/embedded_devices/utils.py
examples/pytorch_from_centralized_to_federated/cifar.py
src/py/flwr/server/strategy/fast_and_slow_test.py
src/py/flwr/server/strategy/fault_tolerant_fedavg.py
src/py/flwr/server/strategy/fedadagrad.py
src/py/flwr/server/strategy/fedavg.py
src/py/flwr/server/strategy/fedopt.py
src/py/flwr/server/strategy/qffedavg.py
src/py/flwr_example/pytorch_cifar/cifar.py
src/py/flwr_example/pytorch_cifar/cifar_test.py
src/py/flwr_example/pytorch_minimal/cifar.py
src/py/flwr_example/pytorch_save_weights/cifar.py
src/py/flwr_example/quickstart_pytorch/mnist.py
src/py/flwr_experimental/baseline/common/client.py
src/py/flwr_experimental/baseline/common/common.py
src/py/flwr_experimental/baseline/common/data.py
src/py/flwr_experimental/baseline/config/config.py
src/py/flwr_experimental/baseline/config/config_test.py
src/py/flwr_experimental/baseline/model/resnet.py
src/py/flwr_experimental/baseline/setting.py

Closes #569 
Updated all uses of 
`# pylint: disable-msg=...`
to
`# pylint: disable=...`

Updated pylint "disable-msg=" to "disable="

---

.github/workflows/flower.yml
.github/workflows/flower_ops.yml
dev/aws-ami-bootstrap-tf.sh
dev/bootstrap.sh
examples/quickstart_tensorflow/pyproject.toml
examples/simulation/Dockerfile
examples/simulation/pyproject.toml
pyproject.toml
src/docker/default.Dockerfile
src/docker/sshd.Dockerfile

This PR will update numpy and tensorflow-cpu and remove the numpy-stubs dependency. Refers to #454 .

Repo | numpy update, remove numpy-stubs

---

src/py/flwr/server/strategy/__init__.py

Including FedAdagrad in init file

Including FedAdagrad in __init__ file.

---

examples/pytorch_from_centralized_to_federated/cifar.py

change net initialization

---

examples/simulation/README.md
pyproject.toml
src/py/flwr_experimental/ops/cluster.py
src/py/flwr_experimental/ops/cluster_test.py

This PR will update myPy to 0.800 and fix the conflicting files.
I used version 0.800 as it is the latest supported on https://pypi.org/project/mypy/ .
Will close #629 .

myPy | Update & Fix files

---

doc/source/quickstart_tensorflow.rst

- change return values to 0.14
- change server output to 0.14

TF quickstarter: update doc

---

doc/source/quickstart_pytorch.rst

- change code snippet to new return values
- change server output to Flower 0.14

PyTorch quickstarter: update doc

---

README.md

- add mxnet to USP description (Framework agnostic)
- add mxnet doc
- add mxnet quickstart link
- add mxnet example link

Add MXNet to main README

---

src/py/flwr/server/server.py

This PR aligns the implementations of `fit` and `evaluate` and removes special case handling to unify how `fit` and `evaluate` process client results. The refactoring is in preparation for the implementation of upcoming server features.

Refactor server fit and evaluate

---

doc/source/apiref-flwr.rst
doc/source/example-mxnet-walk-through.rst
doc/source/example-pytorch-from-centralized-to-federated.rst
doc/source/example_walkthrough_pytorch_mnist.rst
doc/source/examples.rst
src/py/flwr/client/client.py
src/py/flwr/client/numpy_client.py

* Fix sphinx warnings 
* Include types in apidocs so developers can easily click on the specifications

Improve docs

---

doc/source/changelog.rst

Please review/merge #721 first

Release notes for serialization-agnostic server

---

examples/dp-sgd-mnist/README.md
examples/dp-sgd-mnist/client.py
examples/dp-sgd-mnist/common.py
examples/dp-sgd-mnist/pyproject.toml
examples/dp-sgd-mnist/server.py

This PR adds an example where Flower is used to train a federeated learning system where clients are free to choose 
between non-private and private optimizers. Specifically, clients can choose to train Keras models using the standard SGD optimizer or __Differentially Private__ SGD (DPSGD) from [Tensorflow Privacy](https://github.com/tensorflow/privacy). For this task we use the MNIST dataset which is split artificially among clients. This causes the dataset to be i.i.d. The clients using DPSGD track the amount of privacy spent and display it at the end of the training. 
This example is adapted from https://github.com/tensorflow/privacy/blob/master/tutorials/mnist_dpsgd_tutorial_keras.py
In addition, i have used code in the examples/advanced_tensorflow and examples/simulation to build …

DPSGD Mnist Example

---

src/py/flwr/server/strategy/fedavg.py

Fix type annotation in FedAvg docstring

---

src/py/flwr/server/strategy/fedadagrad.py
src/py/flwr/server/strategy/fedopt.py

Adding two variables `beta_1` and `beta_2` that will be useful for the next strategies.

Improve FedOpt

---

src/py/flwr/server/grpc_server/grpc_server.py

Improves the documentation of the internal gRPC server start method.

Improve gRPC server docs

---

.github/workflows/baselines.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_ops.yml
.github/workflows/flower_tool.yml
baselines/dev/bootstrap.sh
baselines/pyproject.toml
dev/bootstrap.sh
examples/advanced_tensorflow/pyproject.toml
examples/dp-sgd-mnist/pyproject.toml
examples/pytorch_from_centralized_to_federated/pyproject.toml
examples/quickstart_pytorch/pyproject.toml
examples/quickstart_simulation/pyproject.toml
examples/quickstart_tensorflow/pyproject.toml
examples/simulation/pyproject.toml
examples/simulation_pytorch/pyproject.toml
examples/simulation_pytorch_legacy/pyproject.toml
examples/sklearn-logreg-mnist/pyproject.toml
pyproject.toml

install related to https://github.com/python-poetry/poetry/issues/4085

Upgrades poetry to version 1.1.10. It fixes some weird bugs during

---

src/py/flwr/simulation/ray_transport/ray_client_proxy.py

Fixing a possible bug with ray and get_properties

fixing ray get_properties issue

---

baselines/flwr_baselines/experiments/fedbn_convergence_rate/README.md
baselines/flwr_baselines/experiments/fedbn_convergence_rate/utils/data_download.py
baselines/flwr_baselines/experiments/fedbn_convergence_rate/utils/data_preprocess.py

- Update readme with download link
- Add data preprocess file in utils

Add original data download link and pre-process code for FedBN

---

examples/android/server.py

The comment on the Android server number of rounds has been updated to match the source code line below it. This _pull request_ solves https://github.com/adap/flower/issues/949.

Fix Android example server comment

---

baselines/flwr_baselines/experiments/fedbn_convergence_rate/utils/create_mnistm.py
baselines/flwr_baselines/experiments/fedbn_convergence_rate/utils/data_download_raw.py

Reformatted files as needed by `./dev/test-baseline.sh`.

Reformatted files using black

---

baselines/dev/venv-create.sh
baselines/dev/venv-delete.sh
dev/venv-create.sh
dev/venv-delete.sh
doc/source/getting-started-for-contributors.rst
doc/source/recommended-env-setup.rst
src/docker/default.Dockerfile
src/docker/sshd.Dockerfile

Update scripts and docs to Python 3.7.12

---

doc/source/quickstart_mxnet.rst

The Mxnet documentation has some minor errors . 
Fix the MXNet documentation and remove typos.

update the mxnet documentation

---

README.md
doc/source/quickstart_scikitlearn.rst

The quickstart doc of the scikit examples only refers to to the corresponding readme.
Add quickstart documentation for scikit example.

Scikit doc

---

baselines/pyproject.toml

Update baselines dev tool config

---

doc/source/_templates/layout.html

none
This PR adds plausible to the docs.

Use plausible for docs

---

README.md

Update README with Flower logo and links

---

doc/source/changelog.rst

Fix PR urls in changelog

---

examples/quickstart_mlcube/README.md
examples/quickstart_mlcube/dev/client.sh
examples/quickstart_mlcube/dev/server.sh
examples/quickstart_mlcube/dev/setup.sh

Discussion in Slack. Additionally after debugging I found out that all MLCube examples currently are breaking. I opened a PR to fix that in the MLCube examples repository: mlcommons/mlcube_examples/pull/43
It improves the documentation and scripts of the MLCube example

Fix documentation and scripts of mlcube example

---

src/py/flwr/server/strategy/aggregate.py
src/py/flwr/server/strategy/aggregate_test.py
src/py/flwr/server/strategy/fast_and_slow.py
src/py/flwr/server/strategy/fault_tolerant_fedavg.py
src/py/flwr/server/strategy/fedavg.py
src/py/flwr/server/strategy/fedavg_android.py
src/py/flwr/server/strategy/fedfs_v0.py
src/py/flwr/server/strategy/fedfs_v1.py
src/py/flwr/server/strategy/qfedavg.py

Remove unused parameter from aggregation function

---

doc/source/_templates/layout.html

Updates the doc layout template

Update doc layout template

---

src/py/flwr/dataset/utils/common.py
src/py/flwr/dataset/utils/common_test.py
src/py/flwr/server/strategy/fedavg_android.py
src/py/flwr/server/strategy/qfedavg.py

This PR adresses a few NumPy related type issues that surface when installing NumPy 1.20

Fix NumPy-related mypy issues

---

.devcontainer/Dockerfile
.github/workflows/baselines.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_tool.yml
baselines/dev/bootstrap.sh
baselines/pyproject.toml
dev/aws-ami-bootstrap-tf.sh
dev/aws-ami-bootstrap-torch.sh
dev/bootstrap.sh
examples/advanced_tensorflow/pyproject.toml
examples/android/pyproject.toml
examples/dp-sgd-mnist/pyproject.toml
examples/mxnet_from_centralized_to_federated/pyproject.toml
examples/opacus/pyproject.toml
examples/pytorch_from_centralized_to_federated/pyproject.toml
examples/quickstart_huggingface/pyproject.toml
examples/quickstart_mlcube/pyproject.toml
examples/quickstart_mxnet/pyproject.toml
examples/quickstart_pytorch/pyproject.toml
examples/quickstart_pytorch_lightning/pyproject.toml
examples/quickstart_simulation/pyproject.toml
examples/quickstart_tensorflow/pyproject.toml
examples/simulation/pyproject.toml
examples/simulation_pytorch/pyproject.toml
examples/simulation_pytorch_legacy/pyproject.toml
examples/sklearn-logreg-mnist/pyproject.toml
pyproject.toml

*Blocked by #871* **Update: merged**

Upgrade pip, setuptools, and poetry

---

.github/PULL_REQUEST_TEMPLATE.md

Include changelog question in PR template

---

examples/quickstart_tensorflow/pyproject.toml

Upgrade quickstart TensorFlow to Flower 0.19

---

doc/source/_templates/base.html

Fix how script in docs is embedded

---

doc/source/_templates/base.html

Use releative path for doc script

---

pyproject.toml

Details: https://python-poetry.org/docs/pyproject/#poetry-and-pep-517

Update build-system in pyproject.toml

---

src/py/flwr/server/history.py
src/py/flwr/server/history_test.py
src/py/flwr/server/server.py
src/py/flwr/server/strategy/fault_tolerant_fedavg.py
src/py/flwr/server/strategy/fedadagrad.py
src/py/flwr/server/strategy/fedadagrad_test.py
src/py/flwr/server/strategy/fedadam.py
src/py/flwr/server/strategy/fedavg.py
src/py/flwr/server/strategy/fedavg_android.py
src/py/flwr/server/strategy/fedavgm.py
src/py/flwr/server/strategy/fedyogi.py
src/py/flwr/server/strategy/qfedavg.py
src/py/flwr/server/strategy/strategy.py
src/py/flwr/server/utils/tensorboard.py

Rename rnd to server_round

---

src/py/flwr/server/strategy/fedavg.py

Remove wording "weights" from fedavg strategy code

---

.devcontainer/Dockerfile
.github/workflows/baselines.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_tool.yml
baselines/dev/bootstrap.sh
baselines/pyproject.toml
dev/aws-ami-bootstrap-tf.sh
dev/aws-ami-bootstrap-torch.sh
dev/bootstrap.sh
examples/advanced_pytorch/pyproject.toml
examples/advanced_tensorflow/pyproject.toml
examples/android/pyproject.toml
examples/dp-sgd-mnist/pyproject.toml
examples/mxnet_from_centralized_to_federated/pyproject.toml
examples/opacus/pyproject.toml
examples/pytorch_from_centralized_to_federated/pyproject.toml
examples/quickstart_huggingface/pyproject.toml
examples/quickstart_mlcube/pyproject.toml
examples/quickstart_mxnet/pyproject.toml
examples/quickstart_pytorch/pyproject.toml
examples/quickstart_pytorch_lightning/pyproject.toml
examples/quickstart_tensorflow/pyproject.toml
examples/simulation_pytorch/pyproject.toml
examples/simulation_tensorflow/pyproject.toml
examples/sklearn-logreg-mnist/pyproject.toml

Update build tool versions

---

examples/advanced_pytorch/pyproject.toml
examples/advanced_tensorflow/pyproject.toml
examples/quickstart_huggingface/pyproject.toml
examples/quickstart_jax/pyproject.toml
examples/quickstart_pytorch/pyproject.toml
examples/quickstart_tensorflow/pyproject.toml
examples/simulation_pytorch/pyproject.toml
examples/simulation_tensorflow/pyproject.toml

Removes rc0 from the example `pyproject.toml` files

Remove rc0 from example deps

---

examples/advanced_pytorch/server.py

Format code examples

---

doc/source/implementing-strategies.rst

Some small typos on the implementing-strategies.rst were fixed.

fix typos on implementing-strategies.rst

---

README.md

Does the changelog need to be updated?
No
This PR fixes the simulation examples reference link in the README file.

Fix simulation examples reference link

---

src/py/flwr/server/strategy/fedavg.py

I did not open an issue in advance, is this something you would prefer I do in the future? Or are you ok with issues as PRs?
Modified the doc string for FedAvg to reflect the default values in the function definition.
Thanks for the great package

Update FedAvg documentation default values

---

doc/source/index.rst
doc/source/saving-and-loading-Pytorch-checkpoints.rst
doc/source/saving-progress.rst

This PR:
- Fixes the PyTorch checkpointing docs
- Updates the existing docs
Follow-up to #1364 
Fixes #1407

Update checkpointing docs

---

doc/source/example-jax-from-centralized-to-federated.rst
doc/source/example-mxnet-walk-through.rst
doc/source/example-pytorch-from-centralized-to-federated.rst
doc/source/quickstart-mxnet.rst
doc/source/quickstart-pytorch.rst

Credit to @Linardos for spotting the mistake 👏

Update docs to new get_parameters format

---

examples/quickstart_cpp/fedavg_cpp.py
examples/quickstart_cpp/include/line_fit_model.h
examples/quickstart_cpp/include/simple_client.h
examples/quickstart_cpp/include/synthetic_dataset.h
examples/quickstart_cpp/server.py
examples/quickstart_cpp/src/simple_client.cc
src/cc/flwr/include/client.h
src/cc/flwr/include/message_handler.h
src/cc/flwr/include/serde.h
src/cc/flwr/include/start.h
src/cc/flwr/include/typing.h
src/cc/flwr/src/message_handler.cc
src/cc/flwr/src/serde.cc
src/cc/flwr/src/start.cc

Update the quickstart_cpp example and make it compatible with the latest version of Flower

Update cpp to the lastest version

---

.devcontainer/Dockerfile
.github/workflows/baselines.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_tool.yml
baselines/dev/bootstrap.sh
baselines/pyproject.toml
dev/aws-ami-bootstrap-tf.sh
dev/aws-ami-bootstrap-torch.sh
dev/bootstrap.sh
examples/android/pyproject.toml
examples/dp-sgd-mnist/pyproject.toml
examples/mxnet_from_centralized_to_federated/pyproject.toml
examples/opacus/pyproject.toml
examples/pytorch_from_centralized_to_federated/pyproject.toml
examples/quickstart_mlcube/pyproject.toml
examples/quickstart_mxnet/pyproject.toml
examples/quickstart_pytorch_lightning/pyproject.toml
examples/sklearn-logreg-mnist/pyproject.toml

Currently the different tests from the workflows fail because of an install error related to `typing_extensions` not being installed, this PR aims at fixing this by upgrading pip, setuptools and poetry.

Upgrade pip, setuptools and poetry

---

README.md

Before, the build status badge on the README was not rendered.

Fix badge on README

---

dev/test.sh

Improves test.sh script to provide a better overview in case of failure

Improves test.sh script to provide a better overview

---

examples/mt-pytorch/driver.py

 Improves driver example to wait for clients

---

README.md

I realized that 2 of the tutorials were not listed on the `README` so I added them (eventhough their doc is still in progress).

Add all tutorials to README

---

examples/pytorch_federated_variational_autoencoder/.gitignore
examples/pytorch_federated_variational_autoencoder/client.py
examples/pytorch_federated_variational_autoencoder/pyproject.toml
examples/pytorch_federated_variational_autoencoder/server.py

Fix device error, update flwr and rename legacy names.

Fix Pytorch autoencoder example

---

doc/source/telemetry.md
src/py/flwr/client/app.py
src/py/flwr/common/telemetry.py
src/py/flwr/common/telemetry_test.py
src/py/flwr/driver/driver.py
src/py/flwr/server/app.py
src/py/flwr/simulation/app.py

Adds a new event to telemetry API, reduces code footprint and updates docs.

Add new events and improve telemetry code

---

doc/source/conf.py
doc/source/differential-privacy-wrappers.rst
doc/source/release-process.rst

* Fixes broken Markdown links in docs
* Adds hint to release process how to extract authors

Fixes issue with Markdown links in docs

---

doc/source/changelog.md
doc/source/conf.py
doc/source/installation.rst
pyproject.toml
src/docker/default.Dockerfile
src/docker/sshd.Dockerfile

Bump Flower version in main post-release according to our release process.

Post-release: Bump version to v1.3.0

---

examples/android/pyproject.toml

Update Flwr version and restrict Python version to resolve poetry resolve conflicts.

Update Flower version for Android example

---

examples/quickstart_pandas/README.md
examples/quickstart_pandas/client.py
examples/quickstart_pandas/server.py

There were too many weird things with this example to let it as it was, so I rewrote a big part of it, while trying to keep the original objective the same (at least what I was able to guess of it).

Fix quickstart-pandas example

---

examples/android/client/app/src/main/res/layout/activity_main.xml

The `runGrpc` function had been renamed in `MainActivity.java` but not in `activity_main.xml`.

Correct name in activity_main.xml

---

doc/source/conf.py
doc/source/index.rst
doc/source/write-documentation.rst

Its first contribution. As described in getting started with contribution flower is following Diàtaxis framework. This PR changes the documentation from writing-documentation.rst to write-documentation.rst

change writing-documentation.rst to write-documentation.rst

---

doc/source/changelog.md

Updates changelog to contain all changes since the last release.

Update changelog to contain all changes since last release

---

doc/source/conf.py
doc/source/installation.rst
pyproject.toml
src/docker/default.Dockerfile
src/docker/sshd.Dockerfile

Update Flower development version to 1.4.0

Update Flower development version to 1.4.0

---

src/py/flwr/server/state/in_memory_state_test.py
src/py/flwr/server/state/state.py

Updates the documentation of the new state to contain a more details description of what the methods have to implement and what constraints to adhere to.

Update state documentation

---

src/py/flwr/server/driver/driver_servicer.py
src/py/flwr/server/driver/driver_servicer_test.py
src/py/flwr/server/utils/validator.py
src/py/flwr/server/utils/validator_test.py

Preparing  Task validation to be used in state tests

Prepare  Task validation to be used in state tests

---

doc/source/changelog.md

Move new release to the correct spot.

Move FedProx release in CHANGELOG

---

doc/source/example-walkthrough-pytorch-mnist.rst

Fixes some deprecated typing present in the PyTorch MNIST doc example.

Fix PyTorch MNIST example doc

---

doc/source/quickstart-scikitlearn.rst

Fix some deprecated typing present in the quickstart Scikit-Learn doc.

Fix quickstart Scikit Learn example

---

README.md

Fix to flower bibtex entry

---

pyproject.toml

#1694 
Add the `xgboost` dependency to run the xgboost strategy.

Add xgboost extra dependency

---

examples/advanced_tensorflow/pyproject.toml
examples/android/pyproject.toml
examples/quickstart_tensorflow/pyproject.toml
examples/simulation_tensorflow/pyproject.toml

Fix tensorflow-cpu version

---

examples/advanced_tensorflow/pyproject.toml
examples/android/pyproject.toml
examples/quickstart_tensorflow/pyproject.toml
examples/simulation_tensorflow/pyproject.toml

Fix the version of `libclang` in order to fix the CI

Fix `libclang` version below `16.0.0`

---

src/py/flwr/__init__.py

#1730 
The common package does not appear on VSCode or using other LSPs.

Add common to __init__.py

---

pyproject.toml

This will set the version of Ray to 2.3.0 in order to fix the CI.

Fix the version of Ray to 2.3.0

---

baselines/flwr_baselines/publications/fedprox_mnist/main.py

A typo was fixed in #1716 from staggler to straggler but the suffix also needed to be changed.

Change file suffix to strag instead of stag in FedProx

---

pyproject.toml

#1737 
This reverts the mentioned PR in order to have `ray` updated to the latest version.

Update `ray` to latest version

---

examples/quickstart_xgboost_horizontal/code_horizontal.ipynb

As reported by @aiden506, the XGBoost example imports were not working properly. This is now fixed.

Fix imports in XGBoost example notebook

---

doc/source/conf.py
doc/source/index.rst
doc/source/quickstart-xgboost.rst

Add a doc article about the new quickstart XGBoost example.

Add quickstart-xgboost example to docs

---

examples/quickstart_pandas/pyproject.toml

The Pandas quickstart example was using an outdated version of Pandas.

Update Pandas to 2.0 in quickstart example

---

.github/dependabot.yml

Adds Dependabot to the repo for dev dependencies.

Add Dependabot for dev dependencies

---

pyproject.toml

The current version of `Ray` (2.3.0) is not the latest and blocks other updates.
N/A
Update `pyproject.toml` to change the `Ray` version from `^2.3.0` to `^2.4.0`.

Update `ray` to 2.4

---

examples/opacus/pyproject.toml
examples/pytorch_from_centralized_to_federated/pyproject.toml
examples/quickstart_huggingface/pyproject.toml
examples/quickstart_mlcube/pyproject.toml
examples/simulation_pytorch/pyproject.toml
examples/simulation_pytorch/requirements.txt

Dependabot discovered some vulnerabilities that could be caused by out dated package versions: https://github.com/adap/flower/security/dependabot
N/A
Bump the versions so all the vulnerabilities are patched.
N/A

Use patched versions in examples to fix vulnerabilities

---

src/py/flwr/server/server.py

This PR is to prepare for the FedBuff strategy by adding formatting.
#1883 
Basic formatting.
N/A

Reformat server for FedBuff

---

.devcontainer/Dockerfile
.github/workflows/baselines.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_tool.yml
baselines/flwr_baselines/dev/bootstrap.sh
dev/aws-ami-bootstrap-tf.sh
dev/aws-ami-bootstrap-torch.sh
dev/bootstrap.sh

Build tools are not set to its latest version.
Update build tools (pip, setuptools, poetry) to the latest version in all scripts and github actions.

Update build tools to latest version

---

src/py/flwr/simulation/app.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

The CI was failing due to `mypy` errors linked to a new `Ray` update.
#1925 
Revert temporary changes made in #1925.
N/A

Fix CI by reverting changes from #1925

---

pyproject.toml

A newer version of `mypy` is available
N/A
Update from `1.3.0` to `1.4.0`
N/A

Update `mypy` to 1.4.0

---

.github/workflows/flower.yml
src/py/flwr/server/fleet/rest_rere/rest_api.py

Not all extra dependencies were installed during the CI, which caused some discrepancies between local and CI tests.
#1967 
Install all extra dependencies in the CI.
N/A

Install all extra dependencies for the CI

---

doc/source/contributing-baselines.rst
doc/source/using-baselines.rst

Updated docs to reflect new structure in `baselines/` and instructions to contribute. Because this is not definitive, i made use of `.. warning::` comment blocks to mention that we are transitioning to a new format for Flower Baselines.

Baselines docs updates

---

examples/advanced_pytorch/pyproject.toml
examples/mt-pytorch/pyproject.toml
examples/pytorch_federated_variational_autoencoder/pyproject.toml
examples/pytorch_from_centralized_to_federated/pyproject.toml
examples/quickstart_pytorch/pyproject.toml
examples/quickstart_pytorch_lightning/pyproject.toml
examples/simulation_pytorch/pyproject.toml

The torch versions were updates in the `requirements.txt` files but not in the `pyproject.toml` files of the examples.
#1989 
Update `torch` to `1.13.1` and `pytorch-lightning` to `1.16.0` in the `pyproject.toml` files.
N/A

Update torch version in pyproject.toml files

---

.github/CODEOWNERS

Update code owners to only include current DRIs

Update codeowners list

---

examples/ios/README.md

Fixed typo in README.md
Typo in README

Improved documentation

---

.github/workflows/e2e.yml
e2e/tensorflow/client.py

Importing the client in the Tensorflow E2E test will run the training.
#1974 
Only run training when calling the file directly.
N/A

Update Tensorflow E2E test

---

.github/workflows/e2e.yml
e2e/jax/README.md
e2e/jax/client.py
e2e/jax/jax_training.py
e2e/jax/pyproject.toml
e2e/jax/server.py
e2e/jax/test.sh

End-to-end testing is missing for the Jax framework.
#1974 
Add an E2E test for the Jax framework.
N/A

Add E2E test for Jax

---

.github/workflows/e2e.yml

Ensures all Python CI jobs have the same build tool versions

Ensure build tool versions are all the same

---

.github/actions/bootstrap/action.yml
.github/workflows/baselines.yml
.github/workflows/deprecated_baselines.yml
.github/workflows/docs.yml
.github/workflows/e2e.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_tool.yml

Ensures the bootstrap CI action provides default versions for all build tools and all workflows use them.
Depends on #2096 to be merged first.

Add defaults to action

---

.github/actions/bootstrap/action.yml
.github/workflows/docs.yml

Moves pandoc install from action into workflow

Move pandoc install from action into workflow

---

README.md

We changed the deployment URLs for the docs.
N/A
Update the links to the new URLs.
N/A

Update links to the docs in the README

---

README.md
doc/source/examples.rst
examples/advanced-pytorch/pyproject.toml
examples/advanced-tensorflow/pyproject.toml

Some links were broken after #2138.
#2138
Fix the broken links and names.
N/A

Fix names and URLs in examples

---

examples/simulation-pytorch-colab/README.md

Following my previous PR (#2150 ), another link to the same Colab should be update.

Updating Links

---

examples/flower-simulation-step-by-step-pytorch/Part-I/README.md
examples/flower-simulation-step-by-step-pytorch/Part-I/client.py
examples/flower-simulation-step-by-step-pytorch/Part-I/conf/base.yaml
examples/flower-simulation-step-by-step-pytorch/Part-I/dataset.py
examples/flower-simulation-step-by-step-pytorch/Part-I/main.py
examples/flower-simulation-step-by-step-pytorch/Part-I/model.py
examples/flower-simulation-step-by-step-pytorch/Part-I/server.py
examples/flower-simulation-step-by-step-pytorch/Part-II/README.md
examples/flower-simulation-step-by-step-pytorch/Part-II/client.py
examples/flower-simulation-step-by-step-pytorch/Part-II/conf/base.yaml
examples/flower-simulation-step-by-step-pytorch/Part-II/conf/model/net.yaml
examples/flower-simulation-step-by-step-pytorch/Part-II/conf/strategy/fedadam.yaml
examples/flower-simulation-step-by-step-pytorch/Part-II/conf/strategy/fedavg.yaml
examples/flower-simulation-step-by-step-pytorch/Part-II/conf/toy.yaml
examples/flower-simulation-step-by-step-pytorch/Part-II/conf/toy_model/mobilenetv2.yaml
examples/flower-simulation-step-by-step-pytorch/Part-II/conf/toy_model/resnet18.yaml
examples/flower-simulation-step-by-step-pytorch/Part-II/dataset.py
examples/flower-simulation-step-by-step-pytorch/Part-II/main.py
examples/flower-simulation-step-by-step-pytorch/Part-II/model.py
examples/flower-simulation-step-by-step-pytorch/Part-II/server.py
examples/flower-simulation-step-by-step-pytorch/Part-II/toy.py
examples/flower-simulation-step-by-step-pytorch/README.md

Introducing a new example containing the code developed in the 2-parts/9-videos tutorial series for Flower simulation and Pytorch.

Added code example for Simulation Tutorial Series

---

pyproject.toml

Update ray to 2.6.3

---

dev/format.sh

Fix `format.sh` errors

---

examples/advanced-pytorch/client.py
examples/advanced-pytorch/server.py
examples/advanced-pytorch/utils.py
examples/advanced-tensorflow/server.py
examples/android-kotlin/gen_tflite/__init__.py
examples/android-kotlin/server.py
examples/android/server.py
examples/android/tflite_convertor/tfltransfer/bases/mobilenetv2_base.py
examples/android/tflite_convertor/tfltransfer/bases/saved_model_base.py
examples/android/tflite_convertor/tfltransfer/heads/keras_model_head.py
examples/android/tflite_convertor/tfltransfer/heads/logits_saved_model_head.py
examples/android/tflite_convertor/tfltransfer/model_correctness_test.py
examples/android/tflite_convertor/tfltransfer/tflite_transfer_converter.py
examples/doc/source/conf.py
examples/embedded-devices/client.py
examples/flower-in-30-minutes/tutorial.ipynb
examples/opacus/dp_cifar_client.py
examples/opacus/dp_cifar_main.py
examples/pytorch-from-centralized-to-federated/client.py
examples/secaggplus-mt/workflows.py
examples/simulation-pytorch/sim.ipynb
examples/sklearn-logreg-mnist/utils.py
src/py/flwr_example/quickstart_tensorflow/client.py

Ran `format.sh` and committed all changes in `examples/` and `flwr_example/`
These changes always show up whenever we run `format.sh`. It may make sense to commit those changes so that we can identify and see the changes made by us more clearly. Currently, it's often the case that we have to locate the changes of several files among loads of changes in `examples/`.

Format examples

---

baselines/baseline_template/pyproject.toml
doc/source/ref-changelog.md

Update `mypy` in `pyproject.toml` to be used in baselines. updated to the same version as that in the base `pyproject.toml` in the repo.

Update mypy in baselines template pyproject

---

datasets/pyproject.toml

Fix the Python version specified for ruff in FDS.

Fix Python version specified for ruff

---

doc/source/contributor-how-to-install-development-versions.rst
doc/source/ref-changelog.md

Add docs to install whl on Colab

---

README.md

Fixing the tutorial broken links in the README.md
[Renaming Tutorial Link - PR 2309](https://github.com/adap/flower/pull/2309)

Updated the broken links

---

datasets/doc/source/ref-api-flwr-datasets.rst
datasets/flwr_datasets/partitioner/iid_partitioner.py

Apply the feedback from https://github.com/adap/flower/pull/2336 (that should be a draft because it has the documentation in a different style than the base Framework).

Fix the reference API documentation

---

datasets/pyproject.toml

Fix repository URL for datasets

---

.github/workflows/e2e.yml

Set AWS_REGION correctly for CI job

---

examples/android-kotlin/pyproject.toml

The pyproject.toml build-system section in android example is incorrectly placed.
To make pyproject.toml to be uniform, the build-system section is moved to top.

Update android-kotlin requirements

---

examples/mt-pytorch/pyproject.toml
examples/mt-pytorch/requirements.txt

Pyproject.toml and requirements.txt in mt-pytorch example is not synced.
Update both pyproject.toml and requirements.txt in mt-pytorch and make them synced.

Update mt-pytorch requirements

---

examples/advanced-pytorch/requirements.txt

Pyproject.toml and requirements.txt in advanced-pytorch example is not synced.
Sync pyproject.toml and requirements.txt in advanced-pytorch example by adding validators as dependency in requirements.txt

Update advanced-pytorch requirements

---

examples/android/pyproject.toml
examples/android/requirements.txt

Pyproject.toml and requirements.txt in android example is not synced.
Sync pyproject.toml and requirements.txt in android example

Update android requirements

---

examples/advanced-tensorflow/requirements.txt

Pyproject.toml and requirements.txt in advanced-tensorflow example is not synced.
Sync pyproject.toml and requirements.txt in advanced-tensorflow example by switching dependencies order.

Update advanced-tensorflow requirements

---

pyproject.toml

Upgrade mypy to 1.5.1

---

.github/workflows/docs.yml
.github/workflows/e2e.yml

Based on GitHub documentation, if the condition does not work as expected, it might be missing curly braces. Unfortunately, the docs seem a bit inconsistent.

Fix issue with if condition in GitHub action

---

.github/workflows/e2e.yml
.github/workflows/swift.yml

The E2E workflow skips upload on forks, but doesn't skip download.
N/A
Skip download as well.
N/A

Fix E2E workflow

---

doc/source/tutorial-quickstart-pytorch-lightning.rst

Clarify that it is 'horizontal FL' in pytorch-lightning doc (dev test)

---

.github/workflows/update-pr.yml

The current workflow fails due to a version error.
N/A
Use the correct version to fix the error.
N/A

Fix update PR action version

---

.github/workflows/update-pr.yml

The update PR workflow errors out.
N/A
Use the correct token.
N/A

Fix update PR workflow

---

doc/locales/pt_BR/LC_MESSAGES/framework-docs.po
doc/locales/pt_BR/LC_MESSAGES/sphinx.po

It has been requested to add Portuguese Brazilian translations on the Weblate project.
N/A
Add the empty files so Weblate can detect the new language and allow translations.
N/A

Add the possibility to make Portuguese Brazilian translations

---

src/py/flwr/driver/__init__.py
src/py/flwr/driver/app.py
src/py/flwr/driver/driver.py
src/py/flwr/driver/driver_client_proxy.py
src/py/flwr/driver/grpc_driver.py

Move `GrpcDriver` class to a separate file `driver/grpc_driver.py`

Move GrpcDriver into `driver/grpc_driver.py`

---

datasets/flwr_datasets/federated_dataset.py

Fix spacing in FederatedDataset docs

---

examples/whisper-federated-finetuning/README.md

Small formatting fix for readme.

Update README.md for Whisper example

---

datasets/README.md

The FDS README is outdated.
Update the readme:
* fix the download badge
* update the progress

Update FDS README

---

baselines/baseline_template/README.md
baselines/baseline_template/baseline_template/main.py

Update content of template_baseline

---

doc/locales/zh_Hans/LC_MESSAGES/framework-docs.po
doc/locales/zh_Hans/LC_MESSAGES/sphinx.po

We have no Chinese translation for the docs.
N/A
Add the necessary files for weblate to add Chinese to the translation project.
N/A

Add files for Chinese translation

---

doc/source/tutorial-quickstart-xgboost.rst

- Add youtube tutorial link to xgboost doc
- Fix a few warnings

Add youtube tutorial link to xgboost doc

---

doc/source/ref-changelog.md

Remove unreleased section in changelog

---

doc/source/contributor-how-to-release-flower.rst

Fix release doc

---

baselines/doc/source/conf.py
doc/source/conf.py
doc/source/contributor-how-to-install-development-versions.rst
examples/doc/source/conf.py
pyproject.toml

Update version to 1.7.0

---

doc/source/ref-changelog.md

Add unreleased to changelog

---

examples/quickstart-pytorch/client.py

A small fix. Labels were not sent to device.

Fix quickstart-pytorch example

---

doc/source/explanation-differential-privacy.rst

It improves some minor issues in differential privacy doc [page](https://flower.dev/docs/framework/explanation-differential-privacy.html).

Improve DP doc page

---

examples/xgboost-quickstart/pyproject.toml
examples/xgboost-quickstart/requirements.txt

Update required `flwr` version from `nightly` to 1.6.0.

Update required flwr version from nightly to 1.6.0

---

e2e/jax/pyproject.toml

Currently Poetry breaks the Jax E2E CI by taking too much time to resolve it.
N/A
Fix Jax to a specific version to make Poetry faster.
N/A

Fix version of Jax to solve Poetry resolve issue

---

e2e/strategies/pyproject.toml
e2e/tabnet/pyproject.toml
e2e/tensorflow/pyproject.toml

Try fixing io-gcs-filesystem version

---

.github/workflows/update-pr.yml

We are passing a PAT to the `update-pr-branch` action.
We use the commit sha instead of the tag as recommended in the [security guide](
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

Pin update-pr-branch action to commit sha

---

.github/workflows/_docker-build.yml

We upgraded the download artifact action without upgrading the upload artifact action. Both must have the same major version. 
- updated upload artifact action to v4

upgrade upload artifact action

---

baselines/hfedxgboost/README.md

Fix README for `hfedxgboost` baseline

---

examples/android/README.md

Android readme has outdated instructions that confuses user.
Fixes #2714.
Change the readme to reflect current Android example.
<general>

Fix outdated readme

---

doc/source/how-to-install-flower.rst

The `flwr` package is available on the `conda-forge` but we have no install instructions for it in our docs.
N/A
Add a section in the docs explaining how to install `flwr` using `conda`.
<general>
N/A

Add conda install instructions

---

examples/advanced-tensorflow/README.md
examples/advanced-tensorflow/client.py
examples/advanced-tensorflow/pyproject.toml
examples/advanced-tensorflow/requirements.txt
examples/advanced-tensorflow/run.sh
examples/advanced-tensorflow/server.py

Migrate advanced tensorflow to use FDS.
<examples>

Migrate advanced TensorFlow to use FDS

---

doc/source/how-to-save-and-load-model-checkpoints.rst

modified checkpoint loading instructions

---

src/proto/flwr/proto/recordset.proto
src/proto/flwr/proto/task.proto
src/py/flwr/common/serde.py
src/py/flwr/common/serde_test.py
src/py/flwr/proto/recordset_pb2.py
src/py/flwr/proto/recordset_pb2.pyi
src/py/flwr/proto/task_pb2.py
src/py/flwr/proto/task_pb2.pyi

- Added `RecordSet` message
- Added `RecordSet recordset` field to `Task` message
- Added serde functions for RecordSet

Add `RecordSet` to `Task` proto

---

src/py/flwr/common/recordset_compat.py
src/py/flwr/common/recordset_compat_test.py
src/py/flwr/common/recordset_test.py

This necessitates revisiting some tests (those involving the `keep_input` mechanism)

Remove default input arguments

---

src/py/flwr/common/serde.py

- The old `type(value) == dtype` is updated to `isinstance(value, dtype)` to make the function more inclusive. For example, the function now recognizes `numpy.float64` as `float`.

Fix a bug in `serde._record_value_to_proto`

---

src/proto/flwr/proto/task.proto
src/py/flwr/proto/task_pb2.py
src/py/flwr/proto/task_pb2.pyi
src/py/flwr/server/state/sqlite_state.py
src/py/flwr/server/state/sqlite_state_test.py

- Removed `legacy_*_message` fields
- Updated sqlite state to facilitate the change

Remove `legacy_*_message` fields from `Task` message

---

src/proto/flwr/proto/task.proto
src/py/flwr/common/serde.py
src/py/flwr/common/serde_test.py
src/py/flwr/proto/task_pb2.py
src/py/flwr/proto/task_pb2.pyi

- Removed `sa` field.
- Removed the `SecureAggregation` message and the  `Value` message.
- Removed unused serve functions and unit tests.

Remove `sa` field from `Task` message

---

src/py/flwr/client/app.py
src/py/flwr/client/grpc_client/connection.py
src/py/flwr/client/grpc_client/connection_test.py
src/py/flwr/client/grpc_rere_client/connection.py
src/py/flwr/client/message_handler/message_handler.py
src/py/flwr/client/rest_client/connection.py

- Updated `receive` and `send` in three `connection.py`.
- Updated `client/app.py` accordingly.

Make `receive` / `send` based on `Message`

---

.github/actions/bootstrap/action.yml

All CI jobs are showing the following warnings:
By updating the setup-python version this should be resolved.
<general>

Updating setup-python action as v4 is using a deprecated node version

---

doc/source/tutorial-series-get-started-with-flower-pytorch.ipynb

Some minor improvement for documentation.
<!--
Describe the problem addressed by this PR.

Docs improvment

---

.github/workflows/docker-client.yml
.github/workflows/docker-server.yml
doc/source/contributor-how-to-build-docker-images.rst
doc/source/how-to-run-flower-using-docker.rst
examples/flower-via-docker-compose/requirements.txt

- Verified that docker examples in the documentation works with flwr 1.7.0.
- Published 1.7.0 flwr docker server images.
- Updated flwr version in docker related code,docs and examples.
<skip>

Update flwr in docker docs and examples

---

examples/xgboost-comprehensive/pyproject.toml
examples/xgboost-comprehensive/requirements.txt

Update required flwr version from nightly to 1.7.0 for XGBoost-comprehensive example.
<examples>

Update required flwr version from nightly to 1.7.0 for XGBoost example

---

doc/source/_templates/sidebar/lang.html

Add Chinese language button on framework doc page
<general>

Add Chinese language button on framework doc page

---

doc/locales/zh_Hans/LC_MESSAGES/framework-docs.po

Some translations for the Chinese version of the website were not updated due to a force reset that needed to be performed on Weblate.
N/A
I downloaded a backup before the reset and used this file for the PR.
<skip>
N/A

Add all translations from backup

---

src/py/flwr/common/telemetry.py

updates telemetry url to `telemetry.flower.ai`
<skip>

Update events URL top level domain

---

.github/workflows/e2e.yml
.github/workflows/framework-draft-release.yml
.github/workflows/framework-release.yml

- Updated the URL of the artifact bucket to `artifact.flower.ai`.
<skip>

Update artifact bucket url

---

baselines/fedbn/README.md

Update URL in fedbd README

---

examples/app-pytorch/README.md
examples/app-pytorch/pyproject.toml

Update `app-pytorch` example

---

examples/federated-kaplan-meier-fitter/README.md
examples/federated-kaplan-meier-fitter/pyproject.toml
examples/flower-in-30-minutes/tutorial.ipynb
examples/simulation-pytorch/sim.ipynb
examples/simulation-tensorflow/sim.ipynb

I missed some links in the Jupyter notebooks in `examples` and `doc`. The notebooks in `doc` are updated in #2989.

Update the top level domain in examples

---

doc/locales/fr/LC_MESSAGES/framework-docs.po
doc/locales/zh_Hans/LC_MESSAGES/framework-docs.po
doc/source/ref-changelog.md

Fix incorrect URLs for baseline doc page

---

src/py/flwr/client/app.py
src/py/flwr/common/exit_handlers.py
src/py/flwr/server/app.py

Add new common function for registering exit handlers

---

pyproject.toml

Current cryptography version has some security issues. Update to version 42.0.4.
<general>

Update cryptography version

---

src/py/flwr/server/app.py
src/py/flwr/server/superlink/driver/driver_grpc.py

Solves some future circular imports.

Move `run_driver_api_grpc`

---

src/py/flwr/server/superlink/driver/driver_servicer.py

The `DriverServicer` logs all actions with level `INFO`.

Make `DriverServicer` log as `DEBUG` most actions.

---

src/py/flwr/server/server.py
src/py/flwr/server/superlink/driver/driver_servicer.py

Set logging level `INFO` to server logs people are accustomed to see.

Update logging levels

---

examples/llm-flowertune/app.py
examples/llm-flowertune/requirements.txt

Set default round=100 for app; Update `requirements.txt`.
examples

Small change of LLM example

---

src/py/flwr/client/mod/__init__.py
src/py/flwr/client/mod/secure_aggregation/__init__.py
src/py/flwr/client/mod/secure_aggregation/secagg_mod.py
src/py/flwr/server/workflow/__init__.py
src/py/flwr/server/workflow/secure_aggregation/secagg_workflow.py

The `SecAgg` protocol is implemented as an alias of the `SecAgg+` protocol.

Add `SecAggWorkflow` and `secagg_mod`

---

examples/llm-flowertune/requirements.txt

Update LLM example: required package bitsandbytes==0.41.3
examples

Update LLM example: required package bitsandbytes==0.41.3

---

datasets/flwr_datasets/partitioner/dirichlet_partitioner.py

`self_balancing = True` is what was implemented in the paper but not in line with the description and therefore not the behavior.
Change `self_balancing` to  `False`
<skip>

Change the self_balancing to False

---

src/py/flwr/cli/new/new.py

Improve the CLI  command logs

---

.github/workflows/e2e.yml

Store latest commit in separate folder

---

src/py/flwr/cli/flower_toml.py
src/py/flwr/cli/flower_toml_test.py
src/py/flwr/cli/run/run.py

Improve the flower.toml loading module

---

src/py/flwr/cli/new/templates/app/code/client.pytorch.py.tpl

Not loading config in `flwr run`

---

datasets/pyproject.toml

Merge after this PR is merged:
https://github.com/adap/flower/pull/3103
Prior to the release, bump up the versions and change the status to 4 - beta (from 3 - alpha).
<skip>

Bump up version, set status to stable Flower Datasets

---

src/py/flwr/server/strategy/dp_adaptive_clipping.py
src/py/flwr/server/strategy/dp_fixed_clipping.py

Fix minor central DP docs

---

examples/llm-flowertune/README.md

Update LLM FlowerTune example readme, including:
1. Title
2. Text regarding FlowerTune
<examples>

Update LLM FlowerTune example readme

---

examples/quickstart-tabnet/pyproject.toml

The `requirements.txt` was already on the compatible version.

Make example Flower 1.8.0 compatible

---

examples/quickstart-mlx/requirements.txt

Installing requirements.txt in quickstart-mlx example fails due to error.
Fix the requirements.txt error.

Fix quickstart-mlx requirements

---

examples/llm-flowertune/requirements.txt

LLM example: update flwr package to 1.8.0
<examples>

LLM example: update flwr package to 1.8.0

---

examples/vertical-fl/README.md

`python3` lexer was not recognized in markdown files. 
N/A
Use `python` instead of `python3`.
<skip>
N/A

Replace python3 with python in code snippets

---

datasets/doc/source/how-to-use-with-pytorch.rst
src/py/flwr/cli/new/templates/app/code/task.pytorch.py.tpl

Set more seeds

---

src/py/flwr/common/retry_invoker.py

Spotted a silly tiny bug I wrote...

Save `Exception` to `state` in `RetryInvoker`.

---

pyproject.toml

Remove pydantic version dependency

---

doc/source/tutorial-series-get-started-with-flower-pytorch.ipynb
examples/flower-in-30-minutes/tutorial.ipynb
examples/xgboost-quickstart/README.md

Multiple instances of the same typo throughout docs

Simple Typo Fix: "stated" to "started"

---

.github/workflows/release-nightly.yml

When we release flwr nightly on PyPi, the package seems not immediately available for installation.
The issue was resolved by now waiting until the package was available on PyPI and only then proceeding with the Docker image.

fix(nightly) wait on PyPI

---

.gitignore

When locally testing tutorial series notebooks, `doc/source/dataset` folder gets created.
Add `doc/source/dataset` to `.gitignore`.
- ~~[ ] Write tests~~
- ~~[ ] Update [documentation](https://flower.ai/docs/writing-documentation.html)~~
<general>

Add dataset to gitignore

---

.github/workflows/swift.yml
dev/build-swift-api-ref.sh

Swift github actions are outdated.
Bump actions to v2 and change simulator version to ios 16.2.
<general>

Bump up Swift CI version to v2

---

src/cc/flwr/include/flwr/proto/fleet.grpc.pb.cc
src/cc/flwr/include/flwr/proto/fleet.grpc.pb.h
src/cc/flwr/include/flwr/proto/fleet.pb.cc
src/cc/flwr/include/flwr/proto/fleet.pb.h

The compiled proto files for the C++ SDK are not up to date with the files present in `src/proto`.
N/A
Recompile the proto files.
<skip>
N/A

feat(sdk:cpp): Update proto files with latest version

---

.github/workflows/_docker-build.yml
.github/workflows/release-nightly.yml

- adds CI for building the nightly SuperNode Docker image

feat(nightly) Add CI for nightly SuperNode Docker image

---

src/py/flwr/cli/new/templates/app/README.md.tpl

fix(framework:cli): Fix `flwr new` generated README

---

src/py/flwr/cli/new/templates/app/code/client.tensorflow.py.tpl
src/py/flwr/cli/new/templates/app/code/server.tensorflow.py.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

fix(framework:cli): Fix tensorflow template

---

src/docker/serverapp/Dockerfile

- Adds Dockerfile for the ServerApp image.

feat(docker) add ServerApp Dockerfile

---

.github/workflows/release-nightly.yml

- Adds the Docker SuperApp Image in the nightly release CI.

chore(ci) add ServerApp Docker image in the nightly release CI

---

.github/workflows/docker-serverapp.yml

chore(ci) add CI for ServerApp Docker image

---

doc/source/ref-api-cli.rst

The `flower-simulation` is not listed in `ref-api-cli` documentation.
Related to #3382.
Add `flower-simulation` to `ref-api-cli` via `sphinx-argparse`.
- ~~[ ] Write tests~~
<skip>
N/A

Add `flower-simulation` to `ref-api-cli` docs

---

src/py/flwr/server/history.py
src/py/flwr/server/server.py

fix(framework:logging) Remove formatting characters from history logging

---

src/py/flwr/server/workflow/default_workflows.py

Currently, when using the default `Workflow`, if a client returns an error, the app will crash with the following error:
```py
File "/Users/main/.pyenv/versions/flower-3.10/lib/python3.10/site-packages/flwr/server/workflow/default_workflows.py", line 63, in __call__
default_init_params_workflow(driver, context)
File "/Users/main/.pyenv/versions/flower-3.10/lib/python3.10/site-packages/flwr/server/workflow/default_workflows.py", line 135, in default_init_params_workflow
paramsrecord = next(iter(msg.content.parameters_records.values()))
File "/Users/main/.pyenv/versions/flower-3.10/lib/python3.10/site-packages/flwr/common/message.py", line 255, in content
raise ValueError(
ValueError: Message content is None. Use <message>.has_content() to check if a message has content.
```
N/A
Only …

fix(framework:skip) Fix workflow when receiving failures

---

doc/locales/ko/LC_MESSAGES/framework-docs.po
doc/locales/ko/LC_MESSAGES/sphinx.po

Korean was requested as a new language for translations over on Weblate.
N/A
Add files necessary for Weblate to add Korean as a possible translation language.
<skip>
N/A

doc(framework:skip) Add empty Korean translation files

---

baselines/doc/source/_templates/sidebar/search.html
datasets/doc/source/_templates/sidebar/search.html
doc/source/_templates/sidebar/search.html

Revert "docs(*) Remove placeholder search text to Flower documentation"

---

doc/build-versioned-docs.sh
e2e/pytorch-lightning/pyproject.toml

We still have an error on checkout because files are not removed properly.
#3438 
Run `git clean -fd` before checkout.
<skip>
N/A

doc(framework:skip) Clean all git history before checkout

---

pyproject.toml

fix(*) Fix `setuptools` to `pyproject.toml`

---

src/docker/base/ubuntu/Dockerfile

- Removes most of the Ubuntu vulnerabilities.

fix(framework:skip) Use sqlite3 lib without dev headers

---

.github/CODEOWNERS

ci(*:skip) Update code owners for translations

---

examples/tensorflow-privacy/client.py

Change tensorflow-privacy example dataset to MNIST.

fix(examples) Update TensorFlow-Privacy example dataset and model

---

src/py/flwr/client/client_app.py
src/py/flwr/server/server_app.py

docs(framework:skip) Fix typo in docstrings

---

src/py/flwr/client/app.py

The diff for #3090 is messy because of an indentation change.
#3090 
Add the indent change without modifying the functionality of the code in order to make the diffs for #3090 easier to review.
N/A

refactor(framework:skip) Add no-op indent level to `_start_client_internal`

---

src/py/flwr/client/app.py

fix(framework:skip) Remove create_node call on reconnect

---

doc/source/ref-changelog.md

docs(framework) Add Flower 1.9 changelog

---

src/py/flwr/cli/config_utils.py
src/py/flwr/cli/install.py
src/py/flwr/client/supernode/app.py
src/py/flwr/common/config.py

We have duplicate code to get the home directory of Flower.
N/A
Add new util function and use it.
N/A

refactor(framework:skip) Add function to get flwr dir

---

src/py/flwr/cli/run/run.py

feat(framework) Add SuperExec to flwr run CLI

---

src/py/flwr/cli/run/run.py

docs(framework:skip) Use correct description for CLI arg

---

examples/vertical-fl/README.md

Typo in readme document: pyhton --> python
Typo: pyhton --> python
Typo in readme document: pyhton --> python
pyhton --> python
Correct spelling

fix(examples:skip) Fix typo in one example

---

dev/changelog_config.toml

ci(*:skip) Allow amend to be use as a valid verb for title

---

datasets/flwr_datasets/__init__.py
datasets/flwr_datasets/partitioner/__init__.py
datasets/flwr_datasets/preprocessor/__init__.py
datasets/flwr_datasets/visualization/__init__.py
datasets/flwr_datasets/visualization/bar_plot.py
datasets/flwr_datasets/visualization/heatmap_plot.py

The order in the list in __ all__ is not sorted.
Sort the lists.
(also fix the new line format error)

fix(datasets) Fix sorting in `__all__` 

---

src/py/flwr/common/config.py

We have some code duplication when trying to get the `flwr_dir` because we don't perform a check inside the utility function.
N/A
Add argument to the utility function and use it to check if the default value should be used or not
N/A

feat(framework:skip) Add argument to `get_flwr_dir`

---

datasets/doc/source/conf.py
datasets/doc/source/how-to-install-flwr-datasets.rst
datasets/pyproject.toml

Update:
* pyproject.toml
* conf.py (docs)
* installation guide

docs(datasets) Update Flower Datasets version to 0.2.0

---

doc/build-versioned-docs.sh

docs(framework:skip) Fix versioned docs script

---

dev/build-example-docs.py
examples/vertical-fl/README.md

docs(examples:skip) Fix README metadata

---

dev/changelog_config.toml

Add `benchmarks` tag for PR title definition.

ci(*:skip) Add `benchmarks` tag for PR title definition

---

datasets/README.md
datasets/doc/source/index.rst

Keep the list of the Partitioner up to date in two places => add a reference to `PathlogicalPartitioner`:
* `README.md`
* `index.rst`
Additionally, apply a common convention for naming.

docs(datasets:skip) Update the partitioner list in README and index

---

src/py/flwr/client/app.py

refactor(framework) Log warnings on SuperNode retry attempts

---

src/py/flwr/superexec/app.py

fix(framework:skip) Update certificate check

---

src/py/flwr/cli/new/templates/app/code/client.hf.py.tpl
src/py/flwr/cli/new/templates/app/code/client.jax.py.tpl
src/py/flwr/cli/new/templates/app/code/client.mlx.py.tpl
src/py/flwr/cli/new/templates/app/code/client.numpy.py.tpl
src/py/flwr/cli/new/templates/app/code/client.pytorch.py.tpl
src/py/flwr/cli/new/templates/app/code/client.sklearn.py.tpl
src/py/flwr/cli/new/templates/app/code/client.tensorflow.py.tpl
src/py/flwr/cli/new/templates/app/code/task.hf.py.tpl
src/py/flwr/cli/new/templates/app/code/task.mlx.py.tpl
src/py/flwr/cli/new/templates/app/code/task.pytorch.py.tpl

Update templates to new `client_fn`

refactor(framework) Update `flwr new` templates with new `client_fn` signature

---

src/py/flwr/superexec/deployment.py

fix(framework:skip) Use correct arguments

---

src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.hf.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl
src/py/flwr/cli/run/run.py

feat(framework) Use federations config in `flwr run`

---

src/py/flwr/cli/run/run.py
src/py/flwr/client/supernode/app.py

feat(framework) Add secure channel support for SuperExec

---

src/py/flwr/cli/build.py
src/py/flwr/cli/config_utils.py
src/py/flwr/cli/config_utils_test.py
src/py/flwr/cli/install.py
src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.hf.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl
src/py/flwr/common/config.py
src/py/flwr/common/config_test.py

refactor(framework) Move `tool.flwr` to `tool.flwr.app`

---

src/py/flwr/common/config.py

feat(framework:skip) Add config function for fusing dicts

---

pyproject.toml
src/py/flwr/cli/build.py
src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.hf.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

feat(framework) Remove federations field from FAB

---

datasets/pyproject.toml

ci(datasets:skip) Fix pyarrow version

---

src/py/flwr/cli/run/run.py
src/py/flwr/client/supernode/app.py
src/py/flwr/server/run_serverapp.py
src/py/flwr/superexec/simulation.py

fix(framework:skip) Fix TOML fields renaming

---

src/py/flwr/cli/run/run.py

fix(framework) Display correct federation error message

---

src/py/flwr/cli/install.py
src/py/flwr/superexec/deployment.py

feat(framework) Install Python package(s) on `flwr install`

---

examples/ios/scenarios.ipynb

docs(examples) Fix typo in iOS example notebook

---

src/py/flwr/client/supernode/app.py
src/py/flwr/common/config.py
src/py/flwr/simulation/run_simulation.py
src/py/flwr/superexec/app.py

fix(framework:skip) Pass list of strings to parsing func

---

.devcontainer/Dockerfile
.github/actions/bootstrap/action.yml
dev/bootstrap.sh

- Upgrade pip to 24.1.2 and setuptools to 70.3.0.

ci(*:skip) Upgrade pip and setuptools

---

src/py/flwr/cli/new/new.py
src/py/flwr/cli/new/new_test.py
src/py/flwr/cli/new/templates/app/code/flwr_tune/app.py.tpl
src/py/flwr/cli/new/templates/app/code/flwr_tune/server.py.tpl
src/py/flwr/cli/new/templates/app/pyproject.hf.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

feat(framework:skip) Add `app` suffix to `client` and `server`

---

src/py/flwr/superexec/simulation.py

Replaces `subprocess.Popen` with `subprocess.run` for `SuperExec`'s simulation plugin.

feat(framework) Update subprocess launch mechanism for simulation plugin

---

src/py/flwr/cli/new/templates/app/code/client.hf.py.tpl
src/py/flwr/cli/new/templates/app/code/client.mlx.py.tpl
src/py/flwr/cli/new/templates/app/code/client.pytorch.py.tpl
src/py/flwr/cli/new/templates/app/code/client.sklearn.py.tpl
src/py/flwr/cli/new/templates/app/code/client.tensorflow.py.tpl
src/py/flwr/cli/new/templates/app/pyproject.hf.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

feat(framework) Add run_config to templates

---

src/py/flwr/cli/run/run.py

fix(framework:skip) Send correct override_dict to simulation

---

src/py/flwr/cli/new/templates/app/pyproject.hf.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl

fix(framework:skip) Fix flwr new templates config

---

doc/source/conf.py
pyproject.toml

- Add [sphinx substitution extension](https://github.com/adamtheturtle/sphinx-substitution-extensions).

docs(*:skip) Add sphinx substitution extension

---

src/py/flwr/common/telemetry.py

refactor(framework:skip) Support `partner_id`

---

src/py/flwr/superexec/app.py

refactor(framework:skip) Improve SuperExec docs

---

src/py/flwr/superexec/simulation.py

feat(framework:skip) Improve error handling with simulation plugin

---

doc/source/ref-changelog.md

docs(framework:skip) Update the changelog for 1.10 release

---

baselines/doc/source/conf.py
doc/source/conf.py
doc/source/contributor-how-to-build-docker-images.rst
doc/source/how-to-install-flower.rst
doc/source/how-to-run-flower-using-docker.rst
doc/source/ref-changelog.md
examples/doc/source/conf.py
pyproject.toml

docs(framework) Bump Flower dev version to 1.11.0

---

examples/quickstart-mlx/README.md

docs(*:skip) Update minor formatting

---

datasets/doc/source/index.rst

The FDS description lacks info about how the HF Hub dataset availability relates to the dataset usage in FDS.
Add that information to emphasise the benefits of Flower Datasets.

docs(datasets) Add info about dataset availability to FDS docs

---

doc/source/conf.py
doc/source/contributor-how-to-build-docker-images.rst
doc/source/how-to-install-flower.rst
doc/source/how-to-run-flower-using-docker.rst

docs(framework:skip) Rename stable version variable

---

datasets/doc/source/index.rst

* Misformatted short description
* Incorrect (markdown style) link

docs(datasets) Fix index docs formatting

---

src/py/flwr/cli/new/templates/app/code/task.jax.py.tpl

fix(framework:skip) Replace deprecated function in JAX template

---

.github/workflows/e2e.yml
src/py/flwr/cli/new/templates/app/code/task.jax.py.tpl

ci(framework:skip) Make sure E2E template tests fail on ERROR

---

src/proto/flwr/proto/driver.proto
src/proto/flwr/proto/fleet.proto
src/proto/flwr/proto/run.proto
src/py/flwr/client/grpc_rere_client/grpc_adapter.py
src/py/flwr/proto/driver_pb2.py
src/py/flwr/proto/driver_pb2.pyi
src/py/flwr/proto/driver_pb2_grpc.py
src/py/flwr/proto/driver_pb2_grpc.pyi
src/py/flwr/proto/fleet_pb2.py
src/py/flwr/proto/fleet_pb2_grpc.py
src/py/flwr/proto/fleet_pb2_grpc.pyi
src/py/flwr/proto/run_pb2.py
src/py/flwr/proto/run_pb2.pyi
src/py/flwr/server/superlink/driver/driver_servicer.py
src/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer.py

feat(framework) Update proto files for FAB delivery

---

src/py/flwr/common/serde_test.py

ci(framework) Add tests for FAB serde functions

---

src/py/flwr/server/superlink/ffs/disk_ffs.py
src/py/flwr/server/superlink/ffs/ffs.py
src/py/flwr/server/superlink/ffs/ffs_test.py

refactor(framework) Make `ffs.get` return optional

---

src/py/flwr/client/app.py

fix(framework:skip) Update run with `fab_id` and `fab_version`

---

src/py/flwr/client/app.py
src/py/flwr/client/supernode/app.py

Start the SuperExec:
```bash
flower-superexec --insecure
```
Start the SuperLink:
```bash
flower-superlink --insecure
```
Start the first SuperNode (try `--isolation subprocess` to compare):
```bash
flower-supernode --insecure --supernode-address 0.0.0.0:9098 --node-config "partition-id=0,num-partitions=2" --isolation process
```
For the first SuperNode, start the independent `ClientApp` process:
```bash
flwr-clientapp --supernode 0.0.0.0:9098
```
Start the second SuperNode (try `--isolation subprocess` to compare):
```bash
flower-supernode --insecure --supernode-address 0.0.0.0:9099 --node-config "partition-id=1,num-partitions=2" --isolation process
```
For the second SuperNode, start the independent `ClientApp` process:
```bash
flwr-clientapp --supernode 0.0.0.0:9099
```
```bash
flwr …
```

feat(framework) Support different `--isolation` modes

---

src/py/flwr/common/__init__.py

Export `MetricsRecordValues` and `ConfigsRecordValues` in `common/__init__.py`

feat(framework:skip) Export `MetricsRecordValues` and `ConfigsRecordValues`

---

src/py/flwr/cli/new/templates/app/README.md.tpl

Updates the readme template for apps created via `flwr new`.

refactor(framework) Update `README.md` template

---

doc/source/docker/tutorial-quickstart-docker-compose.rst

- Incorporates the changes made in the Docker compose file

docs(*:skip) Incorporate Docker Compose changes

---

doc/source/conf.py
examples/doc/source/conf.py

Fix redirect issue for ViT example.

fix(examples:skip) Fix redirect issue for ViT example

---

.github/CODEOWNERS

This PR adds @Moep90 and @Robert-Steiner as CODEOWNER for
* The .devcontainer directory in root
* All Dockerfiles

ci(*:skip) Add Robert and Danny as codeowners

---

src/docker/base/README.md
src/docker/clientapp/README.md
src/docker/serverapp/README.md
src/docker/superexec/README.md
src/docker/superlink/README.md
src/docker/supernode/README.md

- Adds flwr 1.11.0 to Docker READMEs

docs(framework:skip) Add flwr 1.11.0 to Docker READMEs

---

doc/source/docker/index.rst
doc/source/docker/run-as-subprocess.rst
doc/source/docker/tutorial-quickstart-docker.rst

- Updates the Docker docs for Flower 1.11.0.

docs(framework:skip) Update Docker docs for 1.11.0

---

.github/CODEOWNERS

This makes Javier a codeowner for the /benchmarks directory.

ci(*:skip) Add Javier as codeowner to /benchmarks

---

doc/source/contributor-explanation-architecture.rst

Very little text documentation on [Flower Architecture](https://flower.ai/docs/framework/contributor-explanation-architecture.html). 
Adding small description about different underlying engines. 
N/A
Write a bit more text about it. 
Describing the engines in Flower architecture. 
- [ x] Implement proposed change
- [ x] Write tests
- [ x] Update [documentation](https://flower.ai/docs/writing-documentation.html)
- [ x] Ping maintainers on [Slack](https://flower.ai/join-slack/) (channel `#contributions`)

docs(framework) Update Flower Architecture documentation

---

.github/workflows/_docker-build.yml

- updates the `docker/build-push-action` to 6.7.0.

ci(framework:skip) Update docker/build-push-action to 6.7.0

---

.github/workflows/_docker-build.yml

- Replaces QEMU with the new ARM runner.

ci(framework:skip) Replace QEMU with ARM runner

---

.github/workflows/framework-release.yml

- Determines flwr version by tag instead of poetry.

fix(framework:skip) Determine flwr version by tag instead of poetry

---

.github/CODEOWNERS

Adds @Moep90 and @Robert-Steiner as codeowners for 'src/docker'

ci(*:skip) Add new Docker codeowners

---

benchmarks/flowertune-llm/evaluation/general-nlp/README.md

Fix a git clone depth issue for generalNLP challenge

fix(benchmarks:skip) Fix a git clone depth issue for generalNLP challenge

---

src/py/flwr/client/client_app.py

fix(framework:skip) Check list length before access

---

dev/changelog_config.toml

Add the new "glossary" project to the changelog. Julian will add the first glossary entries in a separate PR.

ci(*:skip) Add new project to changelog configuration

---

doc/source/ref-changelog.md

docs(framework:skip) Update changelog with latest patch version

---

benchmarks/flowertune-llm/evaluation/medical/README.md

Update medical evaluation readme to indicate using `quantization=4` for the evaluation when submitting to the LLM Leaderboard.

fix(benchmarks) Update medical evaluation readme

---

src/docker/base/README.md
src/docker/clientapp/README.md
src/docker/serverapp/README.md
src/docker/superexec/README.md
src/docker/superlink/README.md
src/docker/supernode/README.md

- Adds `1.11.1` tag to Docker READMEs.

docs(framework:skip) Add 1.11.1 tag to Docker READMEs

---

src/docker/base/README.md
src/docker/clientapp/README.md
src/docker/serverapp/README.md
src/docker/superexec/README.md
src/docker/superlink/README.md
src/docker/supernode/README.md

- Adds unstable tag to Docker READMEs

docs(framework:skip) Add unstable tag to Docker READMEs

---

doc/source/conf.py

docs(framework:skip) Update stable version

---

pyproject.toml

ci(framework:skip) Add an upper bound to gRPC version

---

doc/source/conf.py
pyproject.toml

docs(framework:skip) Add `sphinxext-opengraph` to dev dependencies

---

src/py/flwr/cli/new/templates/app/code/flwr_tune/client_app.py.tpl
src/py/flwr/cli/new/templates/app/code/flwr_tune/models.py.tpl
src/py/flwr/cli/new/templates/app/code/flwr_tune/server_app.py.tpl
src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl

Update get/set parameter functions for FlowerTune template.

refactor(framework) Update get/set parameter functions for FlowerTune template

---

doc/source/docker/run-quickstart-examples-docker-compose.rst

docs(framework:skip) Update docker quickstart example table

---

benchmarks/flowertune-llm/README.md

Update FlowerTune LLM Leaderboard instructions.

refactor(benchmarks) Update FlowerTune LLM Leaderboard instructions

---

pyproject.toml

ci(framework) Update typer to ^0.12.5

---

benchmarks/flowertune-llm/evaluation/code/requirements.txt
benchmarks/flowertune-llm/evaluation/finance/requirements.txt
benchmarks/flowertune-llm/evaluation/medical/requirements.txt

Update dependencies for LLM evaluation pipelines.

fix(benchmarks) Update dependencies for LLM evaluation pipelines

---

benchmarks/flowertune-llm/README.md

fix(benchmarks) Update LLM Leaderboard readme

---

src/py/flwr/common/constant.py

feat(framework) Add FAB constants

---

dev/test.sh
pyproject.toml
src/py/flwr/cli/config_utils.py
src/py/flwr/client/app.py
src/py/flwr/client/grpc_rere_client/connection.py
src/py/flwr/common/message.py
src/py/flwr/common/recordset_compat.py
src/py/flwr/common/retry_invoker.py
src/py/flwr/server/client_manager.py
src/py/flwr/server/superlink/fleet/grpc_bidi/grpc_server.py
src/py/flwr/server/superlink/state/sqlite_state.py
src/py/flwr/server/superlink/state/utils.py

fix(framework:skip) Fix parameters and returns in docstrings

---

src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl

Update the version of `transformers` package for FlowerTune template, to avoid a crash due to their recent changes.

fix(framework) Update package version for FlowerTune template

---

src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl

Update Flower version for FlowerTune template.

refactor(framework:skip) Update Flower version for FlowerTune template

---

src/docker/base/README.md
src/docker/clientapp/README.md
src/docker/serverapp/README.md
src/docker/superexec/README.md
src/docker/superlink/README.md
src/docker/supernode/README.md

Add flwr 1.12.0 to Docker READMEs.

docs(framework:skip) Update Docker READMEs

---

doc/source/docker/enable-tls.rst

docs(framework:skip) Fix Docker TLS chown cmd

---

examples/flower-authentication/README.md
examples/flower-authentication/generate.sh

fix(examples:skip) Fix cmd in auth example

---

src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

fix(framework) Add upper bound to TF version in template

---

src/py/flwr/cli/new/templates/app/code/flwr_tune/dataset.py.tpl

Fix a dataset reformat issue for FlowerTune template.

fix(framework) Fix a dataset reformat issue for FlowerTune template

---

src/docker/serverapp/Dockerfile

feat(framework:skip) Update ServerApp entrypoint

---

src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl

Fix torch version for FlowerTune template to avoid dependency conflicts.

fix(framework) Fix torch version for FlowerTune template

---

benchmarks/flowertune-llm/README.md
src/py/flwr/cli/new/templates/app/code/flwr_tune/dataset.py.tpl

Update readme to reflect a solved issue -- dataset processing for FlowerTune template.

fix(benchmarks) Update readme to reflect a solved issue

---

.github/workflows/_docker-build.yml

feat(framework:skip) Update docker/build-push-action to v6.9.0

---

benchmarks/flowertune-llm/evaluation/finance/benchmarks.py

Fix an empty output issue for finance evaluation pipeline.

fix(benchmarks) Fix an empty output issue for finance evaluation pipeline

---

pyproject.toml

fix(framework) Pin gRPC version to `^1.60.0,!=1.64.2,<=1.64.3`

---

src/py/flwr/server/superlink/linkstate/in_memory_linkstate.py
src/py/flwr/server/superlink/linkstate/linkstate.py
src/py/flwr/server/superlink/linkstate/linkstate_test.py
src/py/flwr/server/superlink/linkstate/sqlite_linkstate.py

This is aimed to implement `flwr ls` command.

feat(framework) Add `get_run_ids` method to `LinkState` and `*LinkState`

---

src/py/flwr/cli/build.py
src/py/flwr/cli/install.py

Merge after https://github.com/adap/flower/pull/4475

refactor(framework) Install app from `.whl` in `FAB`

---

doc/source/explanation-federated-evaluation.rst

docs(framework) Update federated evaluation page

---

doc/locales/fr/LC_MESSAGES/framework-docs.po
doc/locales/ko/LC_MESSAGES/framework-docs.po
doc/locales/pt_BR/LC_MESSAGES/framework-docs.po
doc/locales/zh_Hans/LC_MESSAGES/framework-docs.po

docs(framework:skip) Update translation source text

---

doc/source/docker/run-quickstart-examples-docker-compose.rst
doc/source/docker/tutorial-deploy-on-multiple-machines.rst
doc/source/docker/tutorial-quickstart-docker-compose.rst
src/docker/complete/compose.yml

docs(framework:skip) Update Docker Compose docs for 1.13.0

---

dev/update_version.py
examples/advanced-tensorflow/pyproject.toml

fix(*:skip) Skip exact versions in bumping script

---

.github/workflows/docker-readme.yml

- The job [GitHub Actions Run](https://github.com/adap/flower/actions/runs/11952352647/job/33317900921) failed because the filter also included deleted files. I updated the filter to include only added or modified README files.

fix(framework:skip) Ignore deleted Docker READMEs

---

.gitignore

refactor(*:skip) Ignore Pyright config file

---

doc/source/contributor-ref-good-first-contributions.rst

The text on the good first contributions page could be refined to make it clearer.
Minor modifications in the text and remove requests for outdated usage examples.
Edit the text
The text was refined to reflect the framework's maturity. Some sentences were shortened for brevity, and old reference example requests were removed.

docs(framework) Edit Good First Contributions page 

---

src/docker/base/README.md
src/docker/clientapp/README.md
src/docker/serverapp/README.md
src/docker/superlink/README.md
src/docker/supernode/README.md

docs(framework:skip) Add flwr 1.13.1 to docker READMEs

---

datasets/doc/source/index.rst

fix(datasets) Fix minor typos in datasets docs

---

framework/docs/build-versioned-docs.sh

docs(framework) Fix docs versioned script with new path

---

framework/docs/build-versioned-docs.sh

ci(framework) Fix docs deployment

---

framework/docs/build-versioned-docs.sh

ci(framework) Fix multi version docs

---

framework/docs/build-versioned-docs.sh

ci(framework) Fix CI docs deployment

---

.github/workflows/docs.yml

ci(*:skip) Update deploy script for all docs

---

src/py/flwr/client/app.py
src/py/flwr/client/grpc_adapter_client/connection.py
src/py/flwr/client/grpc_client/connection.py
src/py/flwr/client/grpc_rere_client/connection.py
src/py/flwr/client/rest_client/connection.py

feat(framework) Update fleet connections to include `run_id` in `get_fab`

---

src/py/flwr/cli/log.py
src/py/flwr/cli/login/login.py
src/py/flwr/cli/ls.py
src/py/flwr/cli/run/run.py
src/py/flwr/cli/stop.py
src/py/flwr/cli/utils.py

Removed the server address from the file name.

refactor(framework) Update credentials file name format

---

framework/docs/source/how-to-run-flower-on-azure.rst

docs(framework) Fix typo

---

.github/workflows/docs.yml

docs(framework) Fix other versions on website

---

.github/workflows/docs.yml

ci(framework) Fix docs deployement workflow

---

src/py/flwr/cli/log.py
src/py/flwr/cli/ls.py
src/py/flwr/cli/run/run.py
src/py/flwr/cli/stop.py
src/py/flwr/cli/utils.py

feat(framework) Add prompt for `flwr login` when authentication fails

---

datasets/README.md
datasets/dev/format.sh

* formatting script references the old name of docs directory `doc` (lacking `s` at the end)
* README references an image with doc (also lacks `s`)
Update references.

fix(datasets) Update outdated docs references

---

examples/quickstart-huggingface/pyproject.toml

Update the flwr version in pyproject.toml

refactor(framework) Update flwr version in quickstart hf

---

framework/docs/build-versioned-docs.sh

fix(framework) Improve check in docs generation

---

framework/docs/source/docker/enable-tls.rst
framework/docs/source/docker/persist-superlink-state.rst
src/docker/base/alpine/Dockerfile
src/docker/complete/compose.yml

docs(framework:skip) Improve Docker docs

---

baselines/fjord/requirements.txt

Complements https://github.com/adap/flower/pull/4784

refactor(baselines:skip) Update `torch` version if `FjORD` baseline

---

baselines/fednova/pyproject.toml

fix(baselines:skip) Bump `numpy` version to 1.22.0

---

baselines/dasha/pyproject.toml
baselines/fedmeta/pyproject.toml
baselines/fedpft/pyproject.toml
baselines/flanders/pyproject.toml
baselines/hfedxgboost/pyproject.toml
baselines/moon/pyproject.toml
baselines/statavg/pyproject.toml
examples/vertical-fl/pyproject.toml

fix(baselines) Bump `scikit-learn` versions to 1.5.0

---

baselines/fedwav2vec2/pyproject.toml
examples/whisper-federated-finetuning/pyproject.toml
examples/whisper-federated-finetuning/requirements.txt

ci(examples) Update `transformers` dependency

---

src/py/flwr/client/grpc_rere_client/client_interceptor_test.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor_test.py

Please review #4791 first, and then review this PR.
After this PR is reviewed, the base branch should be changed to `main`.

feat(framework) Implement signature-based authentication

---

src/py/flwr/common/differential_privacy.py

fix(framework) Fix gaussian noise addition for int64

---

framework/docs/source/how-to-authenticate-supernodes.rst

Remove additional comment that doesn't allow public keys to have comments.

docs(examples) Fix SuperNode authentication docs

---

benchmarks/flowertune-llm/evaluation/code/README.md
benchmarks/flowertune-llm/evaluation/code/requirements.txt
benchmarks/flowertune-llm/evaluation/finance/README.md
benchmarks/flowertune-llm/evaluation/finance/requirements.txt
benchmarks/flowertune-llm/evaluation/general-nlp/README.md
benchmarks/flowertune-llm/evaluation/general-nlp/requirements.txt
benchmarks/flowertune-llm/evaluation/medical/README.md
benchmarks/flowertune-llm/evaluation/medical/requirements.txt

Update dependencies for LLM evaluation pipelines, including:
- For coding challenge, use a fork of `bigcode-evaluation-harness` for easy maintenance.
- Update `peft==0.14.0`.
- Update `bitsandbytes==0.45.1`.
- Update recommended Python version to `3.11`.

refactor(benchmarks) Update dependencies for LLM evaluation pipelines

---

src/py/flwr/cli/new/new.py

The original coding dataset is not available in HF.
We update it using a new dataset with exactly same content.

fix(framework) Update dataset for FlowerTune coding template

---

src/py/flwr/server/superlink/driver/serverappio_servicer.py

SuperLink fails to release RAM which causes an accumulated RAM increase over time.
Enable RAM release mechanism in ServerApp servicer.

fix(framework) Erase messages in `LinkState` on `ServerAppIO` pull

---

framework/docs/source/index.rst

Updating one of the documents to try out the project
N/A
Updating one of the documents to try out the project
First onboarding PR to start with the project

docs(framework:skip) Update framework/docs/source/index.rst

---

framework/docs/source/conf.py

docs(framework) Add Flower AI Summit 2025 announcement to docs

---

framework/docs/source/how-to-use-built-in-mods.rst

docs(framework) Update the `How to Use Built-in Mods` guide

---

dev/changelog_config.toml

ci(*:skip) Add new project for PR title check

---

.github/workflows/intelligence-ts.yml
intelligence/dev/get_api_key.sh
intelligence/ts/src/constants.ts
intelligence/ts/src/engines/remoteEngine.test.ts
intelligence/ts/src/engines/remoteEngine.ts
intelligence/ts/src/flowerintelligence.test.ts

ci(*:skip) Update variables

---

intelligence/docs/source/index.rst

docs(intelligence) Add console logs to examples

---

intelligence/ts/src/engines/engine.ts

feat(intelligence) Add isSupported engine method

---

.github/CODEOWNERS

ci(*:skip) Update codeowners

---

intelligence/ts/README.md

refactor(intelligence) Remove incompatible README section

---

.github/workflows/intelligence-ts.yml
intelligence/dev/check-copyright.sh
intelligence/ts/src/constants.ts
intelligence/ts/src/engines/common.ts
intelligence/ts/src/engines/engine.ts
intelligence/ts/src/engines/flwrWasmEngine.ts
intelligence/ts/src/engines/flwrWebgpuEngine.ts
intelligence/ts/src/engines/onnxEngine.ts
intelligence/ts/src/engines/remoteEngine.test.ts
intelligence/ts/src/engines/remoteEngine.ts
intelligence/ts/src/engines/transformersEngine.ts
intelligence/ts/src/engines/webllmEngine.ts
intelligence/ts/src/flowerintelligence.test.ts
intelligence/ts/src/flowerintelligence.ts
intelligence/ts/src/index.ts
intelligence/ts/src/typing.ts
intelligence/ts/src/vite-env.d.ts

ci(intelligence) Add copyright checks

---

framework/docs/source/conf.py

docs(framework) Fix docs config

---

.github/workflows/intelligence-release.yml
.github/workflows/intelligence-ts.yml
intelligence/ts/README.md

ci(intelligence) Fix release workflow

---

intelligence/ts/.npmignore
intelligence/ts/LICENSE
intelligence/ts/README.md
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

refactor(intelligence) Add license

---

intelligence/ts/README.md

docs(intelligence) Update README

---

.github/workflows/e2e.yml
.github/workflows/framework.yml

ci(framework) Skip jobs instead of ignoring them

---

.github/workflows/e2e.yml
.github/workflows/framework.yml

ci(framework) Skip by steps instead of jobs

---

.github/workflows/e2e.yml

ci(framework) Fix conditions

---

intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/browser-extension/pnpm-lock.yaml

ci(intelligence) Fix open vulnerabilities in example

---

src/py/flwr/cli/new/templates/app/code/flwr_tune/client_app.py.tpl

Update doc string of FlowerClient in FlowerTune template.

fix(framework) Update doc string of FlowerClient in FlowerTune template

---

intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/encrypted/pnpm-lock.yaml
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/streaming/package.json

ci(intelligence) Remove unused dependency

---

intelligence/ts/vite.config.ts

refactor(intelligence) Remove unused build config

---

intelligence/ts/src/constants.ts

refactor(intelligence) Update the SDK name constant

---

intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

refactor(intelligence) Revert SDK name change

---

intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/streaming/package.json
intelligence/ts/examples/web-chat/package.json
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

ci(intelligence) Bump version to 0.1.4

---

intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

ci(intelligence) Bump version to 0.1.5

---

.github/workflows/intelligence-docs.yml

ci(intelligence) Fix docs CI

---

intelligence/ts/examples/browser-extension/pnpm-lock.yaml
intelligence/ts/examples/encrypted/pnpm-lock.yaml
intelligence/ts/examples/web-chat/pnpm-lock.yaml

ci(intelligence) Update example lock files

---

intelligence/dev/bump.sh
intelligence/docs/source/conf.py

docs(intelligence) Update docs version

---

intelligence/ts/examples/nextjs-web-chats/lib/chat.ts

fix(intelligence) Add small fix to nextjs example

---

intelligence/ts/package.json

fix(intelligence) Ignore Node dependencies in browsers

---

intelligence/ts/README.md

docs(intelligence) Update project README

---

intelligence/ts/package.json

fix(intelligence) Remove crypto from browser ignored deps

---

.github/workflows/e2e.yml
benchmarks/flowertune-llm/evaluation/medical/benchmarks.py
src/py/flwr/client/heartbeat_test.py
src/py/flwr/common/record/parametersrecord.py

- Fixed an issue in the FastAI E2E test caused by a low Python version  
- Fixed the unit test for the heartbeat protocol  
- Formatted the FlowerLLM benchmark file

ci(*:skip) Fix CI

---

intelligence/ts/src/engines/webllmEngine.ts

fix(intelligence) Remove context-window-size for webllm

---

intelligence/docs/source/conf.py
intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/streaming/package.json
intelligence/ts/examples/web-chat/package.json
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

ci(intelligence) Bump to 1.7.0 post 1.6.0 release

---

.github/workflows/e2e.yml
pyproject.toml

ci(framework) Pin setuptools to 70.3.0

---

src/docker/base/README.md
src/docker/clientapp/README.md
src/docker/serverapp/README.md
src/docker/superlink/README.md
src/docker/supernode/README.md

docs(framework) Update Docker Readmes for 1.17.0

---

.github/workflows/framework-android-release.yml
.github/workflows/framework-cache-cleanup.yml
.github/workflows/framework-devtools.yml
.github/workflows/framework-docker-build-main.yml
.github/workflows/framework-docker-readme.yml
.github/workflows/framework-docs-update-translations.yml
.github/workflows/framework-docs.yml
.github/workflows/framework-draft-release.yml
.github/workflows/framework-e2e.yml
.github/workflows/framework-flower-swift-sync.yml
.github/workflows/framework-release.yml
.github/workflows/framework-swift.yml
.github/workflows/framework.yml

ci(*:skip) Rename Flower CI jobs

---

.github/workflows/framework-docker-build-main.yml

ci(framework) Fix Docker image building job

---

intelligence/docs/source/conf.py
intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/nextjs-web-chats/package.json
intelligence/ts/examples/streaming/package.json
intelligence/ts/examples/web-chat/package.json
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

refactor(intelligence) Bump version to 0.1.8

---

intelligence/ts/.npmignore

ci(intelligence) Update npmignore file

---

framework/py/flwr/cli/new/templates/app/code/task.sklearn.py.tpl

Update path from the legacy `mnist` to `ylecun/mnist`.

refactor(framework) Update dataset path for `sklearn` template

---

.github/dependabot.yml

fixes: https://github.com/adap/flower/actions/runs/14588888088

fix(framework) Fix Dependabot framework updates

---

.github/workflows/release-nightly.yml

Test run: https://github.com/adap/flower/actions/runs/14591097942

fix(framework) Fix nightly release CI

---

framework/dev/build-docker-image-matrix.py

Docker Build Matrix:
```
"namespace_repository": "flwr/superlink",
"tags_encoded": "1.18.0-py3.12-ubuntu24.04\nlatest"
"namespace_repository": "flwr/superlink",
"tags_encoded": "1.18.0-py3.12-alpine3.19\n1.18.0"
"namespace_repository": "flwr/supernode",
"tags_encoded": "1.18.0-py3.9-ubuntu24.04"
"namespace_repository": "flwr/supernode",
"tags_encoded": "1.18.0-py3.10-ubuntu24.04"
"namespace_repository": "flwr/supernode",
"tags_encoded": "1.18.0-py3.11-ubuntu24.04"
"namespace_repository": "flwr/supernode",
"tags_encoded": "1.18.0-py3.12-ubuntu24.04\nlatest"
"namespace_repository": "flwr/supernode",
"tags_encoded": "1.18.0-py3.12-alpine3.19\n1.18.0"
"namespace_repository": "flwr/serverapp",
"tags_encoded": "1.18.0-py3.9-ubuntu24.04"
"namespace_repository": "flwr/serverapp",
"tags_encoded": …
```

feat(framework) Add `latest` tag to Flower Docker images for Ubuntu 24.04 and latest supported Python version

---

.github/workflows/_docker-build.yml

ci(framework) Update docker/build-push-action to 6.15.0

---

.github/ISSUE_TEMPLATE/feature_request.yml

Feature request issue option doesn't show. 
With empty title, it causes this error. 
#5223 
Remove title from feature request issue template - not necessary and not used elsewhere.

ci(*:skip) Remove title from feature request

---

intelligence/kt/gradle.properties

feat(intelligence) Bump Kotlin SDK version to v0.1.8

---

framework/py/flwr/superexec/exec_user_auth_interceptor_test.py

feat(framework) Add test to auth interceptor for authorization protocol

---

framework/py/flwr/supernode/start_client_internal.py

Remove the outer while loop as it's not needed.

refactor(framework) Trim unnecessary code in `flwr.supernode.start_client_internal`

---

framework/py/flwr/supernode/nodestate/in_memory_nodestate.py
framework/py/flwr/supernode/nodestate/nodestate_test.py

feat(framework) Implement `NodeState`

---

intelligence/ts/package.json
intelligence/ts/pnpm-lock.yaml

ci(intelligence) Update WebLLM in TS SDK

---

framework/docker/base/alpine/Dockerfile

feat(framework) Bump version of Alpine base image to 3.22

---

intelligence/ts/src/engines/remoteEngine.ts

fix(intelligence) Correct typo in toolCall response

---

intelligence/docs/source/conf.py
intelligence/kt/gradle.properties
intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/nextjs-web-chats/package.json
intelligence/ts/examples/streaming/package.json
intelligence/ts/examples/web-chat/package.json
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

refactor(intelligence) Bump version

---

intelligence/docs/source/conf.py
intelligence/kt/gradle.properties
intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/nextjs-web-chats/package.json
intelligence/ts/examples/streaming/package.json
intelligence/ts/examples/web-chat/package.json
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

refactor(intelligence) Bump versions after 0.1.12 release

---

framework/py/flwr/supernode/start_client_internal.py
framework/py/flwr/supernode/start_client_internal_test.py

This serves as a temporary step to enable a seamless transition to `ObjectStore`-based communication among SuperLink <> SuperNode <> ClientApp.
The message will be duplicated for now. Very soon, we will let the SuperNode pull objects into `ObjectStore` without inflation.

feat(framework) Store the received message from `SuperLink` in `SuperNode`'s `ObjectStore`

---

framework/docs/source/docker/persist-superlink-state.rst

docs(framework) Fix database path

---

framework/docs/source/ref-exit-codes/101.rst

docs(framework) Update SuperLink exit code `101`

---

framework/py/flwr/server/superlink/utils.py

We moved `store_mapping_and_register_objects` to `flwr/supercore` in https://github.com/adap/flower/pull/5604 but forgot to delete it. Let's delete it.

refactor(framework) Remove duplicated function

---

framework/docs/source/build.rst
framework/docs/source/how-to-authenticate-users.rst
framework/docs/source/how-to-configure-audit-logging.rst
framework/docs/source/how-to-login-to-superlink.rst

docs(framework) Add user authentication guide

---

intelligence/ts/examples/embedding/src/index.ts
intelligence/ts/examples/encrypted/src/index.ts
intelligence/ts/examples/hello-world-js/src/index.js
intelligence/ts/examples/hello-world-ts/src/index.ts
intelligence/ts/examples/streaming/src/index.ts
intelligence/ts/examples/tool-calling/src/index.ts
intelligence/ts/examples/web-chat/src/main.ts

refactor(intelligence): Improve examples

---

framework/py/flwr/server/superlink/serverappio/serverappio_servicer.py
framework/py/flwr/server/superlink/serverappio/serverappio_servicer_test.py

feat(framework): Implement `ListAppsToLaunch` and `RequestToken` RPCs for `ServerAppIoServicer`

---

intelligence/swift/examples/streaming-cli/main.swift

ci(intelligence): Enhance CI security

---

framework/docs/source/helm/how-to-deploy-superlink-using-helm.md

docs(framework): Add audit logging configuration to Helm docs

---

framework/e2e/e2e-tensorflow/pyproject.toml

ci(framework): Bump TensorFlow version in E2E test

---

framework/docs/source/helm/how-to-deploy-superlink-using-helm.md

docs(framework): Document how to set a custom secretKey

---

intelligence/ts/examples/tool-calling/src/index.ts
intelligence/ts/src/engines/engine.ts
intelligence/ts/src/engines/remoteEngine.ts
intelligence/ts/src/engines/remoteEngine/chat.ts
intelligence/ts/src/engines/remoteEngine/remoteUtils.ts
intelligence/ts/src/engines/webllmEngine.ts
intelligence/ts/src/flowerintelligence.ts
intelligence/ts/src/typing.ts

feat(intelligence): Add toolChoice argument to chat

---

examples/quickstart-pytorch/pytorchexample/client_app.py
examples/quickstart-pytorch/pytorchexample/server_app.py
examples/quickstart-pytorch/pytorchexample/task.py

refactor(examples): Format quickstart-pytorch

---

intelligence/docs/source/conf.py
intelligence/kt/flwr/src/main/java/ai/flower/intelligence/Constants.kt
intelligence/kt/gradle.properties
intelligence/swift/src/Constants.swift
intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/embedding/package.json
intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/nextjs-web-chats/package.json
intelligence/ts/examples/streaming/package.json
intelligence/ts/examples/web-chat/package.json
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

ci(intelligence): Bump to 0.2.3 (post 0.2.2 release)

---

intelligence/ts/src/index.ts

fix(intelligence): Add `ToolChoice` type export

---

framework/docs/source/tutorial-quickstart-pytorch.rst
intelligence/ts/examples/tool-calling/src/index.ts
intelligence/ts/src/engines/remoteEngine/chat.ts
intelligence/ts/src/engines/remoteEngine/typing.ts
intelligence/ts/src/index.ts
intelligence/ts/src/typing.ts

feat(intelligence): Add Usage to response

---

intelligence/docs/source/conf.py
intelligence/kt/flwr/src/main/java/ai/flower/intelligence/Constants.kt
intelligence/kt/gradle.properties
intelligence/swift/src/Constants.swift
intelligence/ts/examples/browser-extension/package.json
intelligence/ts/examples/embedding/package.json
intelligence/ts/examples/encrypted/package.json
intelligence/ts/examples/hello-world-js/package.json
intelligence/ts/examples/hello-world-ts/package.json
intelligence/ts/examples/nextjs-web-chats/package.json
intelligence/ts/examples/streaming/package.json
intelligence/ts/examples/web-chat/package.json
intelligence/ts/package.json
intelligence/ts/src/constants.ts
intelligence/ts/src/flowerintelligence.test.ts

ci(intelligence): Bump to 0.2.4 (post 0.2.3 release)

---

framework/docs/source/how-to-design-stateful-clients.rst

docs(framework): Fix how to design stateful `ClientApp` guide

---

framework/py/flwr/serverapp/strategy/fedavg.py

refactor(framework): Merge to `fix-strategy` branch

---

examples/quickstart-huggingface/huggingface_example/client_app.py
examples/quickstart-huggingface/huggingface_example/server_app.py
examples/quickstart-huggingface/huggingface_example/task.py
examples/quickstart-huggingface/pyproject.toml

refactor(examples): Migrate `quickstart-huggingface` example to `Message` API

---

examples/custom-mods/README.md
examples/custom-mods/custom_mods/client_app.py
examples/custom-mods/custom_mods/mods.py
examples/custom-mods/custom_mods/server_app.py
examples/custom-mods/custom_mods/task.py
examples/custom-mods/pyproject.toml

feat(examples): Update custom mods example

---

examples/quickstart-huggingface/huggingface_example/server_app.py

refactor(examples): Add saving of final model for Hugging Face quickstart

---

framework/docs/source/how-to-upgrade-to-flower-1.13.rst

Correct highlight lines in "how to upgrade to Flower 1.13" guide.

docs(framework): Correct highlight lines in "how to upgrade to Flower 1.13" guide

---

examples/xgboost-quickstart/xgboost_quickstart/client_app.py
framework/py/flwr/cli/new/templates/app/code/client.xgboost.py.tpl

Refactor a variable name for XGB quick-start example and template.

refactor(framework): Refactor a variable name for XGB quick-start example and template

---

framework/docs/source/how-to-use-built-in-mods.rst

Update tutorial of how to use built-in Mods.

docs(framework): Update tutorial of how to use built-in Mods

---

framework/docs/source/how-to-implement-fedbn.rst

Update how to implement FedBN tutorial.

docs(framework): Update how to implement FedBN tutorial

---

framework/docs/source/how-to-save-and-load-model-checkpoints.rst

Update how to save checkpoints tutorial.

docs(framework): Update how to save checkpoints tutorial
