adap/flower

dev/deploy-docs.sh

Previous change in docs generation missed the adjustment needed in the docs deployment script.

Fix the docs deployment script

---

doc/source/index.rst
doc/source/quickstart.rst
doc/source/quickstart_keras.rst
doc/source/quickstart_pytorch.rst

1. Link Quickstart PyTorch to index 
2. Rename Quickstart to Quickstart Keras
3. Fix warnings (Title underline too short)

Modify pytorch doc

---

src/py/flwr_experimental/baseline/command.py
src/py/flwr_experimental/baseline/common/config.py
src/py/flwr_experimental/baseline/run.py
src/py/flwr_experimental/baseline/setting.py
src/py/flwr_experimental/baseline/tf_cifar/settings.py
src/py/flwr_experimental/baseline/tf_fashion_mnist/settings.py
src/py/flwr_experimental/baseline/tf_hotkey/settings.py
src/py/flwr_experimental/ops/cluster.py
src/py/flwr_experimental/ops/cluster_test.py
src/py/flwr_experimental/ops/instance.py

Move the dataclass auf of a module so it can be imported by other modules without the dependencies of the cluster.py module becoming required.

Seperate dataclass for easier import

---

dev/deploy-docs.sh

We are adding a new landing page and the docs will be available under https://flower.dev/docs in the future.

Move docs to enable top-level landing page

---

README.md

After we moved the docs into a sub path /docs we forgot to update the links in the README.md

Fix broken links which result in 404s

---

doc/source/implementing-strategies.rst
src/py/flwr/server/server.py
src/py/flwr/server/strategy/fast_and_slow.py
src/py/flwr/server/strategy/fault_tolerant_fedavg.py
src/py/flwr/server/strategy/fault_tolerant_fedavg_test.py
src/py/flwr/server/strategy/fedavg.py
src/py/flwr/server/strategy/fedfs_v0.py
src/py/flwr/server/strategy/fedfs_v1.py
src/py/flwr/server/strategy/qffedavg.py
src/py/flwr/server/strategy/strategy.py

Please review #483 first
This PR unifies the naming of Flower's public APIs. Other public methods/functions (e.g., every method in `Client`, but also `Strategy.evaluate`) do not use the `on_` prefix, which is why we're removing it from the four methods in `Strategy`.

Rename strategy methods

---

doc/source/quickstart_tensorflow.rst

Adjust tensorflow quickstart documentation:
- change dataset to cifar
- change Client to NumPyClient
- change code 
- change link to flower quickstarter example

update tf quickstart documentation

---

.github/workflows/flower.yml
dev/format.sh
dev/test.sh
src/proto/flwr/proto/transport.proto

This PR will add clang-format to `test.sh` and `format.sh` in the Flower repository. Refers to #583 .

Proto Linter | Add clang-format to Flower

---

examples/simulation/pyproject.toml
examples/simulation/simulation.py

The "simulation" example in flower had an issue in which the dependency resolution failed due to an outdated version of numpy. This PR will fix this issue by updating the numpy version inside the `example/simulation/pyproject.toml`.

Examples | Simulation Fix

---

pyproject.toml

Adding PyTorch 1.8.0, torchvision 0.9.0 and python 3.6.2 (needed by PyTorch 1.8.0)

Updating PyTorch to 1.8.0 

---

doc/source/fedbn-example-pytorch-from-centralized-to-federated.rst

I followed the Example: PyTorch - From Centralized To Federated (https://flower.dev/docs/example-pytorch-from-centralized-to-federated.html) and extend it to a fedbn vertion.

add document for fedbn example

---

doc/source/quickstart_pytorch.rst

Fixes:
AttributeError: 'CifarClient' object has no attribute 'testloader'

Fix pytorch quickstart

---

README.md
doc/source/good-first-contributions.rst
examples/sklearn-logreg-mnist/README.md
examples/sklearn-logreg-mnist/client.py
examples/sklearn-logreg-mnist/pyproject.toml
examples/sklearn-logreg-mnist/server.py
examples/sklearn-logreg-mnist/utils.py

Adding a scikit-learn logistic regression example using MNIST dataset.
The openml helper in scikit-learn is broken, so I used the openml python library directly.
I tried to make this as simple as possible following the quickstart examples but it turned out little complicated since model initialisation and parameter setting is a not so obvious with scikit-learn.

Adding sklearn logreg example

---

pyproject.toml
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

This took a long time. Ray changed the way it structures the internal imports. Now one should call directly the submodule `ray.worker` to access `get`.

Fixing script to work with Ray ^1.6.0 without mypy `--no-implicit-reexport` issues.

---

src/py/flwr/simulation/app.py

Pass `ignore_reinit_error=True` to `ray.init()`. The flag prevents an error raised by Ray when calling `ray.init()` repeatedly. The error should not be raised in common command-line scenarios, however, in notebooks (such as Colab), it will happen quite often.

Improve notebook compatibility

---

.github/workflows/flower.yml
dev/aws-ami-bootstrap-tf.sh
examples/advanced_tensorflow/pyproject.toml
examples/quickstart_tensorflow/pyproject.toml
examples/simulation/Dockerfile
pyproject.toml
src/docker/default.Dockerfile
src/docker/sshd.Dockerfile

This PR updates the TF version of all the examples in the code base which should also fix the dependabot security warning.

Upgrade TF version in examples

---

doc/source/conf.py
doc/source/evaluation.rst
doc/source/saving-progress.rst

While learning about flower, I saw this typo in the docs.
I also noticed that the "Suggest edit" functionality in the docs currently causes a 404 because there is a component missing in the URL. E.g., on the "evaluation" page, the link points to https://github.com/adap/flower/edit/main/doc/evaluation.rst although the actual file is located at https://github.com/adap/flower/edit/main/doc/**source**/evaluation.rst. The responsible HTML partial does not seem to be in the public flower repo but I would assume that the bug is in topbar.html:
https://github.com/lbhm/flower/blob/a5b21ca4204d1138bf49d2efbc333171056e8ac1/doc/source/_templates/layout.html#L37

Fix typos & edit link in docs

---

doc/source/quickstart_pytorch.rst

So I was working with this repo : https://github.com/amirhosseinh77/UNet-AerialSegmentation
I cloned it and refactored it to train the model over flower. I used the code provided in the flower pytorch quickstart example.
However, the load_state_dict method threw the following error :
```IndexError: index 0 is out of bounds for dimension 0 with size 0```
Seemed like an issue of shape mismatch. So I changed the set_parameters method to the following to analyse the situation:
```py
def set_parameters(self, parameters):
params_dict = zip(model.state_dict().keys(), parameters)
state_dict = OrderedDict({k: torch.Tensor(v) for k, v in params_dict})
it1 = model.state_dict().items()
it2 = state_dict.items()
l1 = len(it1)
l2 = len(it2)
if l1!=l2 :
print(f"{l1} : {l2} length do not match")
else : …
```

Changed tensor convertor from torch.Tensor() to torch.tensor()

---

examples/dp-sgd-mnist/README.md

This reverts commit 892e3705c4c939c6c3250712ace4c1c3f044cb9f.
This is because the commit was made using a private email by mistake.

Revert "adding testing result"

---

doc/source/example-pytorch-from-centralized-to-federated.rst
doc/source/quickstart_pytorch.rst
examples/pytorch_from_centralized_to_federated/cifar.py
examples/pytorch_from_centralized_to_federated/client.py
examples/quickstart_pytorch/client.py

- change num_examples from len(trainloader) to len(trainset)
- update Pytorch: From centralized to federated example
-  update Pytorch quickstarter
- update doc (Pytorch: from centralized to federated)
- update doc (Pytorch quickstarter)

correct num_examples calculation

---

examples/quickstart_pytorch/README.md

A typo was fixed in the _PyTorch_ example while working on https://github.com/adap/flower/issues/570.

Updated PyTorch Quickstart Example comment

---

doc/source/getting-started-for-contributors.rst

The documentation has been updated for the case where developers could run CI actions locally on their computers. This has been widely useful in https://github.com/adap/flower/pull/952.
An issue has not been created for this purpose as small changes are appended to this pull request.

Add Act instructions for developers

---

.github/workflows/baselines.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_ops.yml
.github/workflows/flower_tool.yml

Some tests in current Python patch versions failed in a recent PR because the GitHub CI wasn't able to install our current version. We had this issue a while ago and updating fixed it at that time. I thought its a good idea to update the patch versions again.
Example from #952 => https://github.com/adap/flower/runs/4638198208
Merging this PR should fix that issue.

Update CI Python patch versions to latest

---

baselines/pyproject.toml
pyproject.toml
src/py/flwr/__init__.py

Added `__version__` using `importlib.metadata` to retrieve installed package information. This pull request accomplishes https://github.com/adap/flower/issues/883 duty.
A screenshot of the testing process is attached below.

Added __version__ to Flower

---

src/py/flwr/server/server.py
src/py/flwr/server/server_test.py

Related to https://github.com/adap/flower/pull/978.
There was an error about the default value for the optional `max_workers` parameter when running `mypy` as pointed out by our _Continuous Integration_ system.
The proposed fix has been tested successfully in a local environment without inconvenience.

Fixed max_workers mypy related error

---

.github/workflows/baselines.yml
.github/workflows/docs.yml
.github/workflows/examples.yml
.github/workflows/flower.yml
.github/workflows/flower_nightly.yml
.github/workflows/flower_tool.yml

This PR will make the naming of CI workflows and actions more consistent and easier to recognize using the action name online. Also some workflow names are kind of wrong e.g. "Build Core"

Make CI workflows and actions naming consistent

---

doc/source/_templates/layout.html
doc/source/getting-started-for-contributors.rst

none
Fixes a linter error where the line under a heading was to short.

Fix linter error in docs

---

doc/source/quickstart_tensorflow.rst

This typo was introduced in #522 
Removes an extra space after the `code:` block which prevented the code from being formatted properly.

Fix typo in tf quickstart doc

---

src/py/flwr/client/client.py
src/py/flwr/client/grpc_client/message_handler.py
src/py/flwr/client/keras_client.py
src/py/flwr/client/numpy_client.py
src/py/flwr/server/client_proxy.py
src/py/flwr/server/grpc_server/grpc_client_proxy.py
src/py/flwr/server/server_test.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

The different clients implementation (and client wrappers) had different method ordering. This PR aligns them by putting the new `get_properties` first.

Align order of client methods

---

src/py/flwr/client/grpc_client/connection.py
src/py/flwr/server/grpc_server/grpc_server.py

This PR resolves the issue which was reported on Slack.
Some cloud providers kill idle TCP connections, for example, Azure after 4min on Virtual Machines. The keepalive is now set to a default of 4min. This will most probably cover all cloud providers. We also expose in this PR a possibility to the user to set it higher. In some cases a keepalive of 4min might be bad of battery lifetime.

Decrease default gRPC keepalive time

---

pyproject.toml

Ray seems to have issues with the latest version of gRPC (1.44): https://github.com/ray-project/ray/issues/22518
They ray requirements.txt has since been [updated](https://github.com/ray-project/ray/pull/22608/commits/949e53dce4a70cf4e7f1ba6b35b0507c552fdb52) to limit gRPC to versions <=1.43.0. This fix, however, is not available in a public ray release yet.
This PR introduces the same version limiter to work around the underlying ray issue and prevent Flower users from having to manually revert `grpcio` to a prior version. It will be reversed once there are updated ray versions available.

Limit grpcio dependency to <=1.43.0

---

baselines/flwr_baselines/publications/adaptive_federated_optimization/cifar/client.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

`get_resource_ids()` is deprecated https://docs.ray.io/en/latest/_modules/ray/worker.html

Removing deprecated `get_resource_ids()

---

examples/quickstart_pytorch/client.py

Fix a problem where the label tensor was not properly converted to a CUDA tensor leading to an error.
Running the `quickstart_pytorch/run.sh` with a CUDA-enabled GPU yields to an exception 
```
[...]
File "/examples/quickstart_pytorch/client.py", line 42, in test
correct += (torch.max(outputs.data, 1)[1] == labels).sum().item()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
This is due to `labels` not being on the CUDA device. This PR fixes this issue.

Fix an error in the quickstart_pytorch example on GPU.

---

doc/source/conf.py
pyproject.toml

The current docs are broken on mobile (sidebar nav cannot be closed):
This PR fixes the docs on mobile devices by switching to the Furo theme:
By switching to Furo, we can also add an announcement banner at the top of the page:
The last change is a copy button on code blocks:

Fix docs on mobile / switch to Furo theme

---

src/py/flwr/simulation/app.py

This a short PR enabling the user to decide whether `start_simulation` should do `ray.shutdown()` if an existing Ray runtime is already initialized. In some settings, we might want to have Ray already running before calling `start_simulation` if, for example, some other tasks have to run first before FL.

option to not shutdown ray if already initialised

---

examples/timeouts/README.md
examples/timeouts/pyproject.toml
examples/timeouts/server.py
src/py/flwr/server/grpc_server/flower_service_servicer.py

This PR updates #1162 with the following minor changes:
- Updated wording of comments
- Remember & re-raise `StopIteration`
- Use different key names in dicts to reduce potential for ambiguity

Update request timeouts draft

---

src/py/flwr/server/server.py

Add round numbers to fit and eval debug messages in server.py to make them more informative.
Used rnd variable and %s operator in keeping with existing style.

Add round number to fit and eval debug messages

---

doc/source/quickstart-pytorch.rst

There is no associated issue or PR
I could not run the code blocks from the PyTorch tutorial as it threw an IndentationError.
I have indented the required doc strings. 
Thanks for the great package. This is just a small contribution, but it is my small thanks.

Indent function docstring in PyTorch tutorial

---

pyproject.toml

* Work toward Flower 1.0
Update the minimum required version of `grpcio` and `grpcio-tools` to 1.43.0 (latest would be 1.47.0)
Unfortunately upgrading to the latest version of `grpio` is not possible due to a conflict with Ray.
See:
```shell
Updating dependencies
Resolving dependencies... (1.1s)
SolverProblemError
Because ray (1.13.0) depends on grpcio (>=1.28.1,<=1.43.0)
and no versions of ray match >1.13.0,<1.14.0, ray (>=1.13.0,<1.14.0) requires grpcio (>=1.28.1,<=1.43.0).
So, because flwr depends on both grpcio (^1.47.0) and ray (~1.13.0), version solving failed.
```

Update `grpcio` dependency version to more current one

---

examples/sklearn-logreg-mnist/client.py
examples/sklearn-logreg-mnist/pyproject.toml
examples/sklearn-logreg-mnist/server.py

Fixes #1346
Fixes both the server and the client implementations. 
Changes the evaluate_fn passed to built-in strategies like FedAvg to take the three parameters required by Flower 1.0.0.
Changes the naming of Weights to NDArrays.
Adds a configuration object of type flwr.server.ServerConfig in the start_server function, containing the num_rounds instead of the old config dictionary.
I tested it with the run.sh script and it works now

Update sklearn example's server and client

---

examples/quickstart_pytorch_lightning/client.py
examples/quickstart_pytorch_lightning/pyproject.toml
examples/quickstart_pytorch_lightning/server.py

#1343
Flower 1.0.0 requires config in `get_parameters()`, keyword arguments in `start_numpy_client()` and the object `ServerConfig()` in `start_server()`. This fix updates quickstart_pytorch_lightning.py to run with the new version.
I tested it and it's working now.

Lightning example

---

.github/workflows/docs.yml
doc/source/apiref-flwr.rst
doc/source/conf.py
doc/source/examples.rst
doc/source/index.rst
doc/source/quickstart-huggingface.rst
doc/source/quickstart-mxnet.rst
doc/source/quickstart-pytorch-lightning.rst
doc/source/quickstart-pytorch.rst
doc/source/quickstart-scikitlearn.rst
doc/source/quickstart-tensorflow.rst
doc/source/saving-progress.rst
doc/source/ssl-enabled-connections.rst
doc/source/tutorial/Flower-1-Intro-to-FL-PyTorch.ipynb
doc/source/tutorial/Flower-2-Strategies-in-FL-PyTorch.ipynb
pyproject.toml

This is a draft to restructure the Flower docs:
- Introduce four categories: tutorials / how-to guides / explanations / reference
- Include Jupyter Notebook tutorials
- Update dev dependencies

Restructure docs

---

examples/simulation_pytorch/main.py
pyproject.toml
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

NA
Upgrades Ray version to 2.0.0
Fixed the Private Variable Access warning by `ray.worker.get()` to `ray.get()`  as suggested by the API.

Upgrading to Ray 2.0

---

doc/source/changelog.md
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

This change will ensure exceptions in the VCE are logged by default when using the `ray_client_proxy.py`

Log exceptions in VCE by default

---

doc/source/tutorial/Flower-1-Intro-to-FL-PyTorch.ipynb

There seems to be a tiny bug in the tutorial notebook, the `train` function sums up the loss values for each value in the *train* dataset but then divides by the number of *test* samples.

Fixed epoch_loss calculation in intro tutorial

---

src/py/flwr/client/rest_client/connection.py
src/py/flwr/server/rest_server/rest_api.py

Change GET tasks to POST so that we can in the future include data in the GetTaskRequest without leaking anything through the URL

Restless change to POST for the HTTP stack.

---

doc/source/conf.py
doc/source/save-progress.rst

For our documentation, we’ve started to use the Diátaxis framework: [https://diataxis.fr/](https://diataxis.fr/)
Our “How to” guides should have titles that continue the sencence “How to …”, for example, “How to upgrade to Flower 1.0”.
This PR is about changing the title “Saving Progress” to “Save Progress”. 
Before: ”How to saving progress” ❌
After: ”How to save progress” ✅

Change docs title to 'Save Progress'

---

doc/source/conf.py
doc/source/configure-clients.rst

For our documentation, we’ve started to use the Diàtaxis framework: [https://diataxis.fr/](https://diataxis.fr/)
Our “How to” guides should have titles that continue the sencence “How to …”, for example, “How to upgrade to Flower 1.0”.
Most of our guides do not follow this new format yet, and changing their title is (unfortunately) more involved than one might think.
This issue is about changing the title “Configuring Clients” to “****Configure Clients****”. Does this pass our check?
Before: ”How to c****onfiguring clients****” ❌
After: ”How to c****onfigure clients****” ✅

Change docs title to 'Configure Clients'

---

doc/source/index.rst

Problem:
There are two recently renamed how-to guides missing from the website.
Explanation:
The newly changed names of how-to guides (names of files in docs/source/\*.rst) were changed but left the same in index.rst in the toctree structure. 
Solution:
The names in the index.rst were changed to reflect the names in the docs/source/\*.rst.

Rename the recently changed how guides in index.rst (toctree)

---

src/py/flwr/server/strategy/aggregate.py
src/py/flwr/server/strategy/krum.py
src/py/flwr/server/strategy/krum_test.py
src/py/flwr/server/strategy/multikrum_test.py

Fixes  #1482 and fixes #1483
Implement the Krum + MultiKrum strategy as explained in the issue.
Added the strategy class with a new (optional) parameter named num_malicious_clients. Krum, in fact, assumes that the number of malicious clients is known a priori.
Added the aggregation function and tests.
Instead of creating two separate classes and aggregation functions for Krum and MultiKrum I decided to include the latter in the same class of the former by including a parameter `num_clients_to_keep` in the strategy class which defaults to 0. If an integer != 0 is passed, parameters are aggregated according to MultiKrum (i.e. evaluate parameters vectors assigning a score to each of them using Krum, then average the `num_clients_to_keep` smallest ones).

Implement Krum and MultiKrum

---

baselines/dev/venv-create.sh
baselines/dev/venv-delete.sh
dev/venv-create.sh
dev/venv-delete.sh

The `dev/venv-create.sh` and `baselines/dev/venv-create.sh` scripts didn't work with versions of Python that were not `3.7.12`.  Now the scripts will also install the right Python version through `pyenv install $version` before creating the virtual environment.
By default the Python version used is `3.7.12`, but an other version can be given as argument of the script, for example :
`./dev/create-venv.sh 3.8.10` will create the virtual environment `flower-3.8.10` using `Python 3.8.10`.
Note that the `dev/venv-delete.sh` and `baselines/dev/venv-delete.sh` will work in the same fashion. By default, it will delete the virtual environment that is using `Python 3.7.12` but an argument can be given to delete a virtual environment that uses another version. If we continue with our previous …

Add Python version modularity in venv scripts

---

baselines/dev/bootstrap.sh
baselines/dev/setup-defaults.sh
dev/setup-defaults.sh

After thorough testing the install script now works completely, before the environment variables were not set which caused errors when trying to run the `venv-create.sh` and `bootstrap.sh` scripts.
The user now has to run the `bootstrap.sh` script themselves after `setup-defaults.sh`, this is because the shell needs to be changed between the execution of the two scripts. This was not taken into account before.  
I will be adding info in the docs after this branch is merged into main.

Fix scripts

---

baselines/dev/bootstrap.sh

Before the `bootstrap.sh` in `baselines/` was resetting the virtual environment, which was not the case in the root `dev/bootstrap.sh` script. Resetting the virtual environment is now left to `venv-reset.sh` and the 2 bootstrapping scripts have the same behavior.

Align scripts from baselines to scripts on root

---

doc/source/tutorial/Flower-1-Intro-to-FL-PyTorch.ipynb

It fixes access to the trainloader required to display a batch of CIFAR10 images.
Before:
```python
images, labels = iter(trainloaders[0]).next()
```
Gives: AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'
Now:
```python
images, labels = next(iter(trainloaders[0]))
```
Additionally, it creates a more appealing plot of images (bigger plot, space between images, labels directly above the images).
Before (with the iterator access fix):
After:

Fix access to the interator and display a better plot

---

baselines/dev/venv-reset.sh
dev/venv-reset.sh

Before the reset script was not modular like the other scripts with regards to the Python version. Now we can choose which venv to reset by providing a version.

Add modularity to reset script

---

README.md

Adds the new FedAvg MNIST to the README.

Add FedAvg MNIST Baseline to README

---

examples/simulation_tensorflow/README.md

The Colab links were not correctly updated when the example names changed.

Fixes Colab link for simulation_tensorflow example

---

doc/source/tutorial/Flower-1-Intro-to-FL-PyTorch.ipynb
doc/source/tutorial/Flower-2-Strategies-in-FL-PyTorch.ipynb
doc/source/tutorial/Flower-3-Building-a-Strategy-PyTorch.ipynb
doc/source/tutorial/Flower-4-Client-and-NumPyClient-PyTorch.ipynb

Support GPU out-of-the-box GPU in simulations(when a user specifies "cuda" as the device) in the following tutorials:
* An Introduction to Federated Learning
* Strategies in Federated Learning
* Building a Strategy
* Client and NumPyClient
How:
Specify GPU in start_simulation, by giving client_resources argument with {num_gpus=1}, in case of using CUDA
Other changes:
Also adds .to(DEVICE) when it was missing (2nd tutorial)

Proper gpu in tutorials

---

examples/dp-sgd-mnist/server.py

Makes this example compatible with the versions `>=1.0.0` of `flwr` by using the correct type for parameters.

DP-SGD example version compatibility

---

examples/opacus/dp_cifar_main.py
examples/opacus/server.py

Makes this example compatible with the versions `>=1.0.0` of `flwr`.

Opacus example version compatibility

---

doc/source/tutorial/Flower-2-Strategies-in-FL-PyTorch.ipynb

No issue mentions this.
Spelling mistake, train was spelled traing. 
Nah 🌱

Remove small spelling error in tutorial 2 🌱

---

src/py/flwr/server/app.py
src/py/flwr/server/driver/driver_client_manager.py
src/py/flwr/server/driver/driver_servicer.py
src/py/flwr/server/driver/state.py

With this PR, the Driver API dependency on the `ClientManager` is dropped. Going forward, the streaming gRPC stack is the only component that relies on `ClientManager`, other transport stacks (e.g. REST) will be able to run without it.
The dependency on `ClientManager` is dropped by keeping a record about available client nodes (node IDs) in the `DriverState` (instead of having the `DriverServicer` read this directly from the `DriverClientManager`). Other transport stacks (e.g., REST) will be able to register client nodes with the `DriverState` in the same way.
Disentangling Driver API (`DriverServicer`) and `DriverClientManager` is an important step to eventually have Driver API and Fleet API run in different processes, maybe even on different machines.

Isolate ClientManager in the streaming gRPC stack

---

doc/source/tutorial/Flower-3-Building-a-Strategy-PyTorch.ipynb

I left one [wip] section unchanged in the tutorial, now it's fixed.

Add a missing description to Flower-3-Building-a-Strategy-PyTorch

---

baselines/flwr_baselines/publications/fedavg_mnist/client.py

Some unused parameter was passed to the `get_parameters` function in `client.py`. Some function also didn't have type hints for their return values.

Improve typing for FedAvg baseline

---

pyproject.toml

The current form of how dev dependencies are defined in the `pyproject.toml` is deprecated. This PR updates the definition to the new format.

Update dev dependency definition in pyproject.toml to new format

---

baselines/flwr_baselines/publications/fedavg_mnist/client.py
baselines/flwr_baselines/publications/fedavg_mnist/dataset.py
baselines/flwr_baselines/publications/fedavg_mnist/docs/conf/config.yaml
baselines/flwr_baselines/publications/fedavg_mnist/main.py
baselines/flwr_baselines/publications/fedavg_mnist/tests/data_test.py
baselines/flwr_baselines/publications/fedavg_mnist/tests/model_test.py

Add better testing and a way to balance the classes in the dataset.

[FedAvg] Balance classes  in dataset

---

examples/quickstart_pytorch/client.py

#1604 
Makes the total testing loss in the `quickstart_pytorch` example more consistent by changing the reduction method of the criterion from `mean` to `sum`.

Correct testing loss in the quickstart_pytorch example

---

doc/source/secagg.rst

The diagrams in https://flower.dev/docs/secagg.html are broken, this adds a space after the empty arrows to fix them.

Fix diagrams in docs

---

README.md

Add FedProx to the main README next to other baselines. And change links to abstracts instead of pdfs.

Add FedProx to README

---

doc/source/good-first-contributions.rst

Mention baselines in the [`Good First Contributions`](https://flower.dev/docs/good-first-contributions.html) doc.

Add baselines to good first contributions doc

---

pyproject.toml
src/py/flwr/simulation/app.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

#1516, #1394 
Upgrade Ray to `2.3.0` in order to fix storage issues caused by object spilling.

Upgrade Ray to `2.3.0`

---

dev/format.sh
doc/source/tutorial/Flower-1-Intro-to-FL-PyTorch.ipynb
doc/source/tutorial/Flower-3-Building-a-Strategy-PyTorch.ipynb

Currently the `format.sh` script is not removing the metadata generated by VSCode in notebooks.

Remove VSCode metadata from notebooks

---

src/py/flwr/simulation/ray_transport/ray_client_proxy.py

Fixes #1752 
Changes loglevel in RayClientProxy as explained in the issue.

Change loglevel for client errors in simulated

---

examples/ios/scenarios.ipynb
examples/ios/server.py

Applies formatting to the Python files of the iOS example and strips the notebook of its metadata

Fix formatting for iOS example

---

src/py/flwr/simulation/app.py

Currently, the simulation requires client_fn of type `Callable[[str], Client]`; however, it works on both Client and NumpyClient (also, the example on the website show function with the return type of NumpyClient).
This PR changes the type to `ClientLike`, which is `Union[Client, NumPyClient]`.
The problem was mentioned in https://github.com/adap/flower/issues/1176
Both type work because the simulation uses `RayClientProxy` that calls this function
https://github.com/adap/flower/blob/57a4365f24727ecf7f0887bdaab9438c4b0142c8/src/py/flwr/client/app.py#L249-L253

Fix the return type of client_fn in simulation

---

doc/source/faq.rst

This commit fixes a broken link that can cause frustration for new users, including myself when I first started. Although it's a small fix, it greatly improves the usability of the application.

FAQ refactor - Fixed broken link to improve usability for new users

---

pyproject.toml

The `XGBoost` optional dependency was actually not in use in the main project. It can therefore be removed.

Remove unnecessary XGBoost dependency

---

src/py/flwr/server/app.py

The missing dependencies error messages for the REST API were not displayed when they originated from background threads.

Display error message when running REST background thread

---

src/py/flwr/server/server.py

Currently when a loss is `0.0` it won't be stored in the `History` object. 
The PR also makes the check for `None` objects consistent.

Fix behavior with null loss

---

pyproject.toml
src/py/flwr/server/strategy/__init__.py
src/py/flwr/server/strategy/aggregate.py
src/py/flwr/server/strategy/fedmedian.py
src/py/flwr/server/strategy/fedtrimmedavg.py

#1610
A strategy that removes the indicated percentage of the largest and smallest weights from the local models received by the server and finally averages their values to create a new global model
Please check TODO comments and I would also need some guidance in fixing CI ;)

Add FedTrimmedMean strategy

---

src/py/flwr/server/strategy/fault_tolerant_fedavg.py
src/py/flwr/server/strategy/fedavgm.py
src/py/flwr/server/strategy/fedmedian.py
src/py/flwr/server/strategy/fedxgb_nn_avg.py
src/py/flwr/server/strategy/krum.py
src/py/flwr/server/strategy/qfedavg.py

Strategies subclassing FedAvg still define `fit_metrics_aggregation_fn` and `evaluate_metrics_aggregation_fn` as attributes via self. 
Also, QFedAvg does the same with almost all attributes that are passed to the FedAvg subclass initializer.
The redundancy is removed.

Remove redundant attributes in strategies subclassing FedAvg

---

src/py/flwr/server/app.py
src/py/flwr/simulation/app.py

The future `start_driver` function will need to use the `_fl` and `_init_defaults` from the `flwr.app.server.app` module, but those functions are prefixed with an underscore which conventionally indicate that the functions are private (not accessible from other modules).
#1697 
Rename `_fl` into `fl` and `_init_defaults` into `init_defaults`.
N/A

Expose some server functions to other modules

---

src/py/flwr/server/app.py

A import error caused by a package that doesn't exist after a renaming.
#1863 
Rename `rest_server` into `fleet.rest_rere`
N/A

Fix rest_server renaming

---

src/py/flwr/server/strategy/aggregate.py

Just realized I wrote a wrong comment here. So, `aggregate_krum` does not return the index of the best model, but the best model itself.

Fix code documentation in aggregate_krum()

---

src/py/flwr_experimental/baseline/tf_hotkey/client.py

Fix updated formatting

---

.github/workflows/flower.yml

The check-requirements-txt.sh is unstable so it needs to be made optional for the time being.

Make check-requirements-txt.sh optional

---

.github/workflows/flower.yml

It seems continue-on-error will still mark the test as failed. I missed that in the review of the previous PR which made it optional.
* #1905

Avoid CI job to marked as failure if requirements.txt check fails

---

src/py/flwr/simulation/app.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

The CI is breaking because of Ray 2.5.0, probably related to this: https://github.com/ray-project/ray/issues/36252.
N/A
Before Ray releases a patch, we need to ignore the typing for the lines that raise issues.
N/A

Ignore typing for Ray to fix CI

---

src/py/flwr/client/numpy_client_test.py

The return value `Properties()` of `get_properties` would lead to an error if the method is called. 
Note that the test didn't fail because the has_get_properties function checks types only and didn't run the get_properties. Yet, it still might be misleading, and in the case of expanding on the test, it would lead to an error.
The `Properties` is a custom type and cannot be instantiated.
Return an empty dict `{}`.
The empty dict meets the Properties type and follows what other methods were mocking - the most straightforward implementation of NumPyClient.

Fix return value in get_properties in numpy_client_test

---

.flake8
src/py/flwr/server/strategy/fedadagrad.py
src/py/flwr/server/strategy/fedadam.py
src/py/flwr/server/strategy/fedavg.py
src/py/flwr/server/strategy/fedavg_android.py
src/py/flwr/server/strategy/fedavgm.py
src/py/flwr/server/strategy/fedopt.py
src/py/flwr/server/strategy/fedprox.py
src/py/flwr/server/strategy/fedtrimmedavg.py
src/py/flwr/server/strategy/fedyogi.py
src/py/flwr/server/strategy/krum.py

The changes from https://github.com/adap/flower/pull/1934 broke the documentation - the new line in hint types was treated as a new attribute (I must have checked it wrong when I built if for testing in that PR), yet the changes introduced in that PR are necessary for Ruff linter to work.
https://github.com/adap/flower/pull/1934
I bring back the pylint `line-too-long` to the code.
I fix the flake8 (and future ruff problems) by adding per-file specific type ignores (E501 = line too long) to the flake8 config (per file specific ignore is file is not possible for flake8).

Fix treating hint-types new lines as a new attributes

---

src/py/flwr/server/strategy/dpfedavg_adaptive.py
src/py/flwr/server/strategy/dpfedavg_fixed.py
src/py/flwr/server/strategy/fault_tolerant_fedavg.py
src/py/flwr/server/strategy/fedadagrad.py
src/py/flwr/server/strategy/fedadam.py
src/py/flwr/server/strategy/fedavg.py
src/py/flwr/server/strategy/fedavg_android.py
src/py/flwr/server/strategy/fedavgm.py
src/py/flwr/server/strategy/fedmedian.py
src/py/flwr/server/strategy/fedopt.py
src/py/flwr/server/strategy/fedprox.py
src/py/flwr/server/strategy/fedtrimmedavg.py
src/py/flwr/server/strategy/fedxgb_nn_avg.py
src/py/flwr/server/strategy/fedyogi.py
src/py/flwr/server/strategy/krum.py
src/py/flwr/server/strategy/qfedavg.py

CAUTION: Please review this PR in the order mentioned https://github.com/adap/flower/pull/1920 for your easy review process.
Fix docstrings of the strategies:
* D105 Missing docstring in magic method
* D205 1 blank line required between summary line and description
D205 meant the summary didn't fit into single line and required shortening 
* D301 Use `r"""` if any backslashes in a docstring
I checked, and adding r""" didn't break anything in the documentation.
* D400 [*] First line should end with a period
* D202 [*] No blank lines allowed after function docstring (found 1)

Fix the docstrings of the strategies

---

dev/format.sh
dev/test.sh
pyproject.toml

CAUTION: Please review this PR in the order mentioned https://github.com/adap/flower/pull/1920 for your easy review process.
The current checks for the docstrings are not exhaustive enough. 
https://github.com/adap/flower/pull/1702 (it builds on top of it - test.sh, format.sh, pyproject.toml with a few minor changes)
Add ruff linter to the `test.sh` and `format.sh` and the settings and download to `pyproject.toml`.
`format.sh` the `--fix` flag enables some to automate some easy fixes (check out which ones https://beta.ruff.rs/docs/rules/#pydocstyle-d)
`pyproject.toml` - the version is fixed because the update might add some new rule that the code would fail (manual version updates should be applied). The `exclude = [` adds proto `proto` to the defaults. The convention of the docstrings …

Add Ruff linter for docstring checks

---

doc/source/changelog.md

Python 3.7 reached its end of life, therefore support for it needs to be deprecated in the next release.
Add deprecation of Python 3.7 to the changelog.

add python 3.7 deprecation in changelog.md

---

pyproject.toml

The version of `ray` impacts the typing checks made during the CI, therefore it would be better to use a fixed version and to update it manually when new versions come out.
N/A
Set a fixed version (`2.5.1`) of `ray` in `pyproject.toml`.
N/A

Fix `ray` version to 2.5.1

---

.github/workflows/flower-swift_sync.yml

The CI fails because of this error.
Do what the error message suggests

Fixes GitHub CI issue because of behaviour change

---

dev/test.sh

At the end of lines in test.sh there is always a `&&` symbol. It is redundant.
NA
NA
Remove `&&` from the end of the lines.
In Bash scripts, && is a logical AND operator.
It's used in the following way:
```
command1 && command2
```
It doesn't change the execution if applied as follows (no next command to be chained)
```
command1 &&
```
I thought about it while creating the code equality tests for baselines by adapting this script.

Remove && from the end of lines

---

examples/advanced_pytorch/pyproject.toml
examples/advanced_pytorch/requirements.txt
examples/mt-pytorch/pyproject.toml
examples/mt-pytorch/requirements.txt
examples/pytorch_federated_variational_autoencoder/pyproject.toml
examples/pytorch_federated_variational_autoencoder/requirements.txt
examples/pytorch_from_centralized_to_federated/pyproject.toml
examples/pytorch_from_centralized_to_federated/requirements.txt
examples/quickstart_pytorch/pyproject.toml
examples/quickstart_pytorch/requirements.txt
examples/quickstart_pytorch_lightning/pyproject.toml
examples/quickstart_pytorch_lightning/requirements.txt
examples/simulation_pytorch/pyproject.toml
examples/simulation_pytorch/requirements.txt

There are some inconsistencies with the examples that uses pytorch as its dependencies, resulting in error when poetry tries to resolve the dependencies. One example is the torchvision dependency requires newer torch version then the specified version in pyproject.toml file.
Helps to fix #1980.
Following changes in pyproject.toml and requirements.txt are made to the examples that uses pytorch as its dependencies:
1. Fix torch version to 1.12.0 and torchvision to 0.13.0
2. Opacus' and embedded device's pytorch version are not changed.
3. Fix python version to >=3.8, <3.11.
4. ^ on other dependencies are removed.
5. Flwr local dependency path is changed to the latest flwr-nightly version.
6. Flwr version is fixed to >=1.0, <2.0.

Update torch examples dependency versions

---

baselines/flwr_baselines/flwr_baselines/publications/leaf/femnist/dataset/nist_preprocessor.py

The CI was failing because of the following PyLint error in Baselines: `E1101: Module 'PIL.Image' has no 'LANCZOS' member (no-member)`.
N/A
Use `PIL.Image.Resampling.LANCZOS` instead of `PIL.Image.LANCZOS`.
N/A

Fix Baselines CI PyLint error by using Resampling

---

pyproject.toml

Simulations currently crash with the latest version of the packages. This is caused by a `pydantic` error from `ray`.
#1974 
Fix the `pydantic` version to `<2.0.0` as described [here](https://github.com/ray-project/ray/pull/37000).
N/A

Fix simulation error caused by Pydantic version in Ray

---

baselines/dev/create-baseline.sh

The create-baseline script doesn't fully work on Linux. It leads to `sed: can't read : No such file or directory` on linux - it doesn't change the name in pyproject.toml. 
NA
The sed works slightly differently on Mac and Linux. The fix causes the script to work differently on Linux and Mac.

Fix baseline creation on linux-base systems

---

baselines/baseline_template/baseline_template/main.py

Currently, the baseline template fails flake8 check:  `E266 too many leading '#' for block comment`
Remove double ## in main.py.
In order to introduce the flake8 tests the current code should meet its standards.

Fix flake8 error E266 in baseline template

---

.github/workflows/e2e.yml
e2e/pytorch/client.py

PyTorch E2E test's client file ran the training when importing.
#1974 
Only run training when file is called directly.
N/A

Update PyTorch E2E test

---

.github/workflows/e2e.yml
e2e/bare/client.py

The bare E2E test needs to be updated to work with simulation.
#1974 
Only trigger training when the `client.py` file is called directly.
N/A

Update bare E2E test client

---

.github/dependabot.yml

We would like to have the latest versions of frameworks tested with E2E tests.
#2078 
Add dependabot to E2E tests.
N/A

Add dependabot to E2E tests

---

.github/workflows/baselines.yml

The new directory `doc` in `baselines` makes the pipeline fail.
https://github.com/adap/flower/pull/2060 (it makes this change fail the tests)
Exclude the `baseline/doc` from checks.
The check didn't take into account the possibility of new directories, therefore it's detected as a change and then the tests fail. This solves it by excluding this directory therefore no changes should be detected.

Exclude baselines/doc from tests in CI

---

.github/workflows/e2e.yml

The E2E tests were quite redondant.
N/A
Use matrix in the Ci job to automate the process of E2E tests.
N/A

Simplify E2E tests with matrix

---

examples/quickstart_fastai/client.py

The `quickstart_fastai` example could have some issues depending on the hardware used to run it.
N/A
Disable parallelism for the data loading and use `cpu()` before converting tensor to numpy. 
N/A

Fix quickstart-fastai example

---

README.md
baselines/doc/source/using-baselines.rst

The link to FedProx MNIST baseline results in `404 - page not found`.
Update link to FedProx MNIST.
The FedProx MNIST was restructured and the link was not updated to the new version. The link points to the legacy version (that is now deleted).

Fix FedProx MNIST link

---

.github/workflows/docs.yml

Some environment variables are declared for the docs building job but never used inside. Also the job is misleadingly named "Build and Deploy docs", whereas it only builds.
N/A
- Remove the unused env variables
- Rename job to "Build docs"
N/A

Rename docs building job and remove unused envs

---

e2e/mxnet/pyproject.toml

Reverts adap/flower#2085
This actually breaks `mxnet` I think this was able to be merged because the E2E tests are not set as required.

Revert "Update numpy requirement from 1.23.1 to 1.24.4 in /e2e/mxnet"

---

.github/dependabot.yml

Dependabot was opening PRs for updating the NumPy version of the MXNet E2E example eventhough this breaks MXNet.
N/A
Exclude `numpy` from those checks.
N/A

Remove `numpy` from dependabot's `mxnet` check

---

.flake8

Black and Flake8 were incompatible due to E203. 
N/A
Ignore E203 in the Flake8 config.
N/A

Make Flake8 compatible with Black

---

.github/workflows/e2e.yml

The Scikit-Learn E2E test breaks the CI due to this issue: https://github.com/openml/OpenML/issues/1196.
#2142 Reverts this change
Remove it temporarily.
N/A

Remove SciKit-Learn E2E test from CI

---

README.md

Fixes link to `30-minute` colab/notebook tutorial.

Fix Colab Links

---

examples/quickstart-pytorch-lightning/README.md
examples/simulation-pytorch/README.md
examples/simulation-tensorflow/README.md

Some examples' titles were inconsistent with the rest.
#2133 
Use better titles for some examples.
N/A

Make examples' titles more consistent

---

doc/source/changelog.md
examples/mt-pytorch/README.md
pyproject.toml
src/py/flwr/server/app.py
src/py/flwr/server/fleet/rest_rere/rest_api.py

This PR changes the implementation of the experimental REST API to use Starlette instead of FastAPI. FastAPI is a wrapper around Starlette, and using Starlette directly avoids the overheads introduced by FastAPI.
None

Migrate from FastAPI to Starlette

---

src/py/flwr/common/serde.py

Fix type hint error in `serde.py`

---

doc/source/changelog.md
src/py/flwr/server/fleet/grpc_bidi/grpc_server.py

A user reported the following error while running a federation locally in separated terminals:
```
Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings".
```
It is a gRPC error, but it is hard to pin point exactly where the error came from (probably not a framework bug, as this is the first instance of such an issue, but it could be from the execution environment or some parts of the user's code).
N/A
Setting the gRPC option `grpc.keepalive_permit_without_calls` to 0 in `src/py/flwr/server/fleet/grpc_bidi/grpc_server.py` fixed the issue for the user. This channel argument if set to 1 (0 : false; 1 : true), allows keepalive pings to be sent even if there are no calls in flight (from https://grpc.github.io/grpc/core/md_doc_keepalive.html) or in an …

Add option to the grpc_server

---

doc/source/_templates/sidebar/versioning.html
doc/source/conf.py
pyproject.toml

Our docs only show the current state of the main branch of the repo.
N/A
Add a way to switch between different versions of the framework (after 1.0.0).
Nothing will be deployed on the docs yet, the visual changes will be part of a subsequent PR.

Allow for docs versioning

---

src/py/flwr/simulation/app.py

Wraps `run_fl` in `start_simulation` inside a try/except statement. If an exception is encountered, an error message is shown suggesting users to adjust the `client_resources`.

Wrap VCE's `run_fl` in try/except

---

src/py/flwr/common/serde.py
src/py/flwr/common/serde_test.py

Value can be scalar or a list of scalar. But currently, the serde functions for Value do not work when Value is an empty list.

Fix bugs in serde function for Value

---

examples/simulation-pytorch/README.md
examples/simulation-tensorflow/README.md

The new simulation examples link to the new documentation page for simulation. The url was incorrect and now is fixed.

Fix URL to Simulation Docs

---

examples/simulation-pytorch/requirements.txt
examples/simulation-tensorflow/requirements.txt

fixes `requirements.txt` for the updated simulation examples. Now `requirements.txt` point to flower in `main` branch (just like `pyproject.toml` does)

Fix simulation requirements.txt

---

e2e/pytorch-lightning/mnist.py

The Pytorch-Lightning e2e test used `num_workers=16` when creating dataloaders. That seems to be the cause of recent segmentation faults when running the tests. Here I reduce the value down to ~`num_workers=2`~ `num_workers=0` (i.e. disable multi-process data loading) which seem to make it run.

Fix pytorch-lightning e2e test

---

doc/build-versioned-docs.sh

From https://github.com/adap/flower/actions/runs/6029993574/job/16360943081, we have `build-versioned-docs.sh: 125: [[: not found`.
N/A
The issue is that we use `bash` syntax with `sh`, if we switch to POSIX compliant syntax (i.e `[` instead of `[[`) we will resolve the issue.
N/A

Make versioned script POSIX compliant to fix error

---

doc/source/how-to-run-simulations.rst

The simulation video playlist can be very helpful for those researching the topic, but it cannot be found on the docs.
N/A
Add an embedding of the introduction video with the playlist link.
N/A

Add the simulation video tutorial to the docs

---

pyproject.toml

We need `sphinx-intl` to prepare docs translations, right? Maybe it got discarded unintentionally from https://github.com/adap/flower/pull/2201

Add sphinx-intl to pyproject

---

.github/workflows/docs.yml
dev/build-docs.sh
dev/deploy-docs.sh
doc/build-versioned-docs.sh

The currently deployed docs only show the main branch of the repo because during the CI, only this branch is visible to the machine.
N/A
Add the `fetch-depth: 0` argument to the checkout action.
I also added another change that was necessary to have the versions functioning properly, i.e, restoring the git state correctly in between checkouts.
I also realised that lines that were very long to execute were actually useless, so I removed them.
And finally I modify the `build-docs.sh` script so it calls the `build-versioned-docs.sh` script. This is because otherwise, this new script (that is deployed) was not tested.

Make tags visible for GitHub action to fix docs versions

---

datasets/pyproject.toml

Flower datasets need to have the possibility to work on the image and audio datasets, yet currently, the extras installation is not available (therefore, the image and audio datasets might not work correctly).
Add the Hugging Face datasets' extras to Flower Datasets.
Installation of datasets[vision] is impossible via poetry, therefore the remaining option was to check the dependencies of the Datasets project and map them to this pyproject.toml.

Add Flower Datasets extras

---

src/py/flwr/simulation/app.py

The VCE only shows the full error trace if something fails on the client side, others (e.g. in strategies) are very quietly shown which might make them difficult to pinpoint where there originate. Now the full error trace is shown.

Show complete error trace

---

.github/workflows/baselines.yml
.github/workflows/deprecated_baselines.yml

Jobs under `Baselines` and `Deprecated-Baselines` don't have names.
N/A
Add name to these jobs so all workflows and jobs are consistent in their naming.
N/A

Add names to unnamed workflow jobs

---

baselines/baseline_template/pyproject.toml
doc/source/ref-changelog.md

Updates the `pyproject.toml` in the template directory for new baselines to `flwr=1.5.0` with simulation.

Update baselines template to flwr to 1.5

---

doc/source/index.rst
doc/source/ref-changelog.md

We accidentally removed the docs from the navbar and this PR is re-adding them.

Re-add the tutorials to the docs navbar

---

doc/source/ref-changelog.md
src/py/flwr/client/app.py

Remove deprecated experimental arg rest

---

datasets/README.md

The formatting of the Flower Datasets README was off.
N/A
Add the bash block termination to fix the formatting.
N/A

Close bash block in order to fix README formatting

---

doc/source/ref-changelog.md
src/py/flwr/client/__init__.py
src/py/flwr/client/app.py
src/py/flwr/client/app_test.py
src/py/flwr/client/numpy_client_wrapper.py
src/py/flwr/client/typing.py
src/py/flwr/simulation/app.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

Refactored Flower client:
* created a `typing.py` in client where types used throughout flower (ClientLike and ClientFn) are defined. It makes easier to access them like this instead that from client app where many things are imported.
* Moved all the numpy wrapping logic to `numpy_client_wrapper.py`, again so we can access important functions such as `to_client()` w/o having to worry about circular imports due to it being previously defined in client app

Refactor Flower client

---

.github/workflows/android-release.yml
.github/workflows/baselines.yml
.github/workflows/deprecated_baselines.yml
.github/workflows/devtools.yml
.github/workflows/docs.yml
.github/workflows/e2e.yml
.github/workflows/flower-swift_sync.yml
.github/workflows/framework.yml
.github/workflows/release.yml

This PR ensures that going forward only the latest commit on a PR branch will use the CI and the previous pipeline will be aborted in case of a new commit.

Abort CI pipelines for PR branches in case of new commits

---

examples/quickstart-fastai/README.md

The FastAI example README redirects to an outdated link.
N/A
Use up to date link or even remove irrelevant part.
N/A

Use new link for FastAI doc article

---

baselines/doc/source/_templates/base.html
examples/doc/source/_templates/base.html

The canonical URLs for Examples and Baselines are incorrect.
Use the correct canonical URLs.
N/A

Fix canonical URLs for Baselines and Examples

---

doc/source/how-to-configure-clients.rst

A 404 is generated by a link in the docs.
N/A
Use the correct link.
N/A

Fix typo in URL for docs (leading to 404)

---

doc/source/index.rst
doc/source/tutorial-quickstart-android.rst
doc/source/tutorial-quickstart-fastai.rst
doc/source/tutorial-quickstart-huggingface.rst
doc/source/tutorial-quickstart-ios.rst
doc/source/tutorial-quickstart-jax.rst
doc/source/tutorial-quickstart-mxnet.rst
doc/source/tutorial-quickstart-pandas.rst
doc/source/tutorial-quickstart-pytorch-lightning.rst
doc/source/tutorial-quickstart-pytorch.rst
doc/source/tutorial-quickstart-scikitlearn.rst
doc/source/tutorial-quickstart-tensorflow.rst
doc/source/tutorial-quickstart-xgboost.rst

Our quickstart tutorials doc pages lack description metadata tags.
N/A
Add tags to quickstart tutorial docs.
N/A

Add description tags for quickstart tutorials

---

doc/source/index.rst
doc/source/tutorial-quickstart-android.rst
doc/source/tutorial-quickstart-fastai.rst
doc/source/tutorial-quickstart-huggingface.rst
doc/source/tutorial-quickstart-ios.rst
doc/source/tutorial-quickstart-jax.rst
doc/source/tutorial-quickstart-mxnet.rst
doc/source/tutorial-quickstart-pandas.rst
doc/source/tutorial-quickstart-pytorch-lightning.rst
doc/source/tutorial-quickstart-pytorch.rst
doc/source/tutorial-quickstart-scikitlearn.rst
doc/source/tutorial-quickstart-tensorflow.rst
doc/source/tutorial-quickstart-xgboost.rst

The meta tags in french cause some duplication, which is bad for SEO.
N/A
Remove the descriptions in french.
N/A

Remove description meta tags in french

---

datasets/flwr_datasets/partitioner/iid_partitioner_test.py

Use automatic format.sh script to fix the formatting of IidPartitioner in FDS.

Fix IidPartitioner formatting

---

.github/workflows/release-nightly.yml

Rename nightly release workflow in preparation of an actual release workflow

---

examples/flower-in-30-minutes/tutorial.ipynb

Wrong youtube link in colab notebook for tensorflow quickstart.
The `examples/flower-in-30-minutes/tutorial.ipynb` contains the pytorch youtube link for the tensorflow quickstart. Hence, both pytorch and tensorflow quickstart redirects to pytorch only!
Changed the YouTube link to - https://www.youtube.com/watch?v=FGTc2TQq7VM for quickstart-tensorflow.

Fix video link in colab notebook of flower-in-30-minutes

---

.github/workflows/docs.yml
dev/build-docs.sh

* Extend the build-docs.sh script by adding the commands to build the Flower Datasets docs.
* Extend the docs GitHub workflow to make them in sync with AWS S3 bucket

Make Flower Datasets docs publishable

---

.github/workflows/docs.yml

Only main is displayed as an available version on the website.
N/A
Add `fetch-depth` argument to `actions/checkout` in order to have access to other branches inside the job.
N/A

Add parameter to actions/checkout to fix doc versions

---

examples/secaggplus-mt/driver.py

Add `create_workload()` call before FL, and set `workload_id` fields in TaskIns.

Adapt `examples/secaggplus-mt/driver.py` to the current flower main

---

doc/source/index.rst

The videos on the Framework docs landing page were too small to be indexed by Google.
N/A
Make the videos larger to fix the issue.
N/A

Make videos bigger to allow for index

---

.github/workflows/e2e.yml

It turns out changing to `AWS_REGION` isn't necessary and doesn't fix the core issue.
Reverts #2454 
Use `AWS_DEFAULT_REGION` instead of `AWS_REGION`.
N/A

Revert to AWS_DEFAULT_REGION

---

.github/workflows/e2e.yml

Currently the wheel is not build on forks and therefore the tests that depend on it are not ran.
N/A
Only check if the current CI is running on a fork for the wheel uploading.
N/A

Build wheel but skip upload on forks

---

examples/opacus/pyproject.toml
examples/opacus/requirements.txt

Pyproject.toml and requirements.txt in opacus example is not synced.
Sync pyproject.toml and requirements.txt in opacus example.

Update opacus requirements

---

.github/workflows/docs.yml
.github/workflows/e2e.yml
.github/workflows/swift.yml

Even though the publishing jobs are correctly skipped on forks, when a pull request is opened from a fork, it will still try to run them.
#2468 
Skip the publishing workflows based on the PR's origin.
N/A

Skip publishing jobs on fork PRs

---

dev/get-latest-changelog.sh

Currently the `get-latest-changelog` script, will get the latest changelog based on the creation date. But that means that if we release bug fixes as patch versions to already released minor versions after the next minor version has been released, the script wouldn't work.
N/A
Use the actual version in order to sort the list of tags.
N/A

Sort tags by versions to get changelog

---

.github/workflows/e2e.yml

On main, the current upload job would upload the artifacts to a URL containing `//`.
The current PR is required for #2499 to work.
Use the `ref_name` instead of the `head_ref` when the `head_ref` is not defined.
N/A

Fix artifact URL on main

---

.github/workflows/e2e.yml
.github/workflows/framework-release.yml

The current artifact store is a bit messy.
N/A
We want to have all commits to main under a `main/` folder, all commits to branches under `pr/<branch-name>/`, and all releases under `release/<version>/`.
N/A

Reorganize artifact folders

---

doc/source/contributor-how-to-release-flower.rst

The formatting of a list in the release doc was wrong.
N/A
Fix the formatting.
N/A

Fix release doc format

---

e2e/fastai/pyproject.toml

The CI is failing due to a new torch version that doesn't install the CUDA libraries automatically.
N/A
Fix the torch version to under 2.1.0.
N/A

Fix CI by downgrading torch on fastai E2E

---

src/cc/flwr/.gitignore
src/cc/flwr/CMakeLists.txt
src/cc/flwr/cmake/StartLibConfig.cmake.in
src/cc/flwr/cmake/flwrConfig.cmake.in

The current C++ SDK couldn't be built in a standalone manner.
N/A
Add a `CMakeLists.txt` file to make the C++ SDK easily compilable.
N/A

Add CMake file for C++ SDK

---

.github/workflows/cpp.yml

No tests were made on the C++ SDK.
N/A
Add tests for C++ to the CI.
N/A

Add C++ workflow file

---

doc/source/ref-changelog.md
examples/embedded-devices/README.md

Update `embedded_devices` example

---

doc/source/ref-changelog.md
src/py/flwr/client/app.py
src/py/flwr/simulation/ray_transport/utils.py

Comments the deprecation warning if users make us of `NumPyClient` either via `start_numpy_client` or in simulation. It is commented instead of removed because the plan is to bring it back soon.

Remove deprecate warning for `numpyclient`

---

doc/source/ref-changelog.md
pyproject.toml

Python 3.12 is out but we don't officially support it.
N/A
Add the mention that we support Python 3.12
N/A

Add support for Python 3.12

---

baselines/doc/source/conf.py

On the Baselines docs, the math from the markdown text would not be rendered correctly. 
N/A
Add the `dollarmath` myst extension following this: https://myst-parser.readthedocs.io/en/latest/syntax/math.html#dollar-delimited-math
N/A

Fix the rendering of math in baselines docs

---

datasets/flwr_datasets/__init__.py
datasets/flwr_datasets/common/version.py

The version cannot be accessed in the flwr-datasets, yet it's expected behavior.
Add the version functionality exactly as in flwr.
It also includes the flwr-datasets-nightly, which is not currently published, but when it will then can be used. The lack of it won't cause any problems.

Add __version__ to Flower Datasets

---

baselines/flwr_baselines/pyproject.toml
baselines/flwr_baselines/requirements.txt

The CI was failing due to some `virtualenv` error. It seems that `virtualenv` was being downgraded to a previous version by another dependency (not sure which one).
N/A
Explicitly set `virtualenv`'s version in `pyproject.toml`.
N/A

Fixing deprecated-baselines CI

---

src/py/flwr/client/grpc_rere_client/connection.py

When we delete a node on the server-side it is not deleted in the context manager
When we delete a node on the server-side it is not deleted in the context manager.
N/A
Delete the node from the locally stored dict.
N/A

Delete node locally in gRPC-rere

---

src/cc/flwr/src/grpc_rere.cc

When we delete a node on the server-side it is not deleted in the context manager.
N/A
Delete the node from the locally stored map.
N/A

C++ SDK: Delete local node for gRPC-rere

---

datasets/flwr_datasets/partitioner/iid_partitioner.py
datasets/flwr_datasets/partitioner/iid_partitioner_test.py

The https://github.com/adap/flower/pull/2588 introduces shuffling. Therefore, now the `contiguous=False` does not make sense.
`contiguous` tells whether the shards=partitions are from the contiguous block. 
Change back to `contiguous=True`.
This is necessary for the future introduction of more performance boosts. The `flatten_idices` that might be introduced in the future will happen prior to partitioning; therefore, we later want a contiguous block of memory.
This will also be consistent with v0.0.1 where `shuffle=False` (the contiguous=True was changed after the release).

Change the settings for IidPartitioner

---

datasets/flwr_datasets/federated_dataset.py

The `partitioners` parameter description in docs is not comprehensive.
Clarify that there might be one or multiple partitioners specified and that at most, one per split.
"At most one Partitioner per split" makes also sense from the dictionary point of view - the keys need to be unique.

Clarify partitioners parameter description in docs

---

datasets/flwr_datasets/partitioner/iid_partitioner.py
datasets/flwr_datasets/partitioner/natural_id_partitioner.py
datasets/flwr_datasets/partitioner/partitioner.py
datasets/flwr_datasets/resplitter/merge_resplitter.py
datasets/flwr_datasets/utils.py

Some of the docs lack the space before the colon describing parameter type
Add missing spaces

Fix spacing around : in parameters in docs

---

datasets/flwr_datasets/common/__init__.py
datasets/flwr_datasets/federated_dataset.py
datasets/flwr_datasets/resplitter/__init__.py
datasets/flwr_datasets/resplitter/resplitter.py
datasets/flwr_datasets/utils.py

The new resplitter package was created for the resplitters. Though the def was not moved.
Move the definition and update the imports.

Move the Resplitter type definition to resplitter package

---

datasets/doc/source/conf.py
datasets/flwr_datasets/federated_dataset.py

* The version in the `conf.py` was not updated.
* The sequence "`Partitioner`s" (the s right after the backtick with no spaces) is misinterpreted and leads to a warning in docs.
Warning: `flower/datasets/flwr_datasets/federated_dataset.py:docstring of flwr_datasets.federated_dataset.FederatedDataset:16: WARNING: Inline interpreted text or phrase reference start-string without end-string.`
* update the version
* Rephrase the docs to convey plural. 
Before:
(the backticks are present)
After:

FDS small docs fix

---

README.md

List all baselines in the top-level readme of the repo.

Add baselines to readme

---

baselines/fedbn/README.md
baselines/fedbn/fedbn/client.py
baselines/fedbn/fedbn/conf/client/fedavg.yaml
baselines/fedbn/fedbn/conf/client/fedbn.yaml
baselines/fedbn/fedbn/dataset.py
baselines/fedbn/fedbn/main.py
baselines/fedbn/fedbn/models.py
doc/source/ref-changelog.md

Minor changes to the recently merged `FedBN` baseline.

Do minor fixes to FedBN

---

doc/source/tutorial-quickstart-xgboost.rst
examples/xgboost-comprehensive/README.md
examples/xgboost-comprehensive/client.py
examples/xgboost-quickstart/README.md
examples/xgboost-quickstart/client.py

Update xgboost examples based on the comments from all-hands meeting, including:
- Add more description at the start of readme for quick start example.
- Add more description at the start of readme for comprehensive example.
- Use a small subset of the dataset in quick start example to speed up data loading.
- Add logs to show data loading/re-formatting process
- Update the tutorial document accordingly.

Update xgboost examples

---

src/py/flwr/client/grpc_rere_client/connection.py
src/py/flwr/common/logger.py

Every now and then, we introduce experimental features in Flower. So far, there is no consistent way to inform the user about the experimental nature of a feature.
Once this PR is merged, PR #2393 can be updated to use `warn_experimental_feature`
This PR introduces a utility function `warn_experimental_feature` that we can use to log a warning every time a user uses an experimental feature. In addition to that, once we use the utility throughout the codebase, it will also allow us to easily search for experimental features.

Introduce experimental feature warning

---

src/kotlin/flwr/src/main/java/dev/flower/android/Typing.kt

Android SDK status Code int value starts at 1, but it should starts at 0.
Fix the status Code int value to starts with 0 instead of 1.

Fix wrong status Code int value in Android SDK

---

doc/source/tutorial-quickstart-xgboost.rst
examples/xgboost-comprehensive/client.py
examples/xgboost-comprehensive/pyproject.toml
examples/xgboost-comprehensive/requirements.txt
examples/xgboost-quickstart/client.py
examples/xgboost-quickstart/pyproject.toml
examples/xgboost-quickstart/requirements.txt

Fix `node_id` issue to fit FDSv0.0.2. The changes includes:
- quick start client.py, change `idx` to `node_id`
- comprehensive start client.py, change `idx` to `node_id`
- Tutorial document
- Temporarily change required package to `flwr-nightly` before flwr 1.6.0

XGBoost -- Fix node_id issue to fit FDSv0.0.2

---

examples/quickstart-pytorch/client.py

`examples/quickstart-pytorch/client.py` is somehow not formatted in the main branch. It is always listed as one of modified files after running `format.sh`. 
Format the file.

Tiny PR to format `examples/quickstart-pytorch/client.py`

---

dev/add-shortlog.sh
doc/source/ref-changelog.md

Update changelog for 1.6

---

examples/vertical-fl/pyproject.toml
examples/vertical-fl/requirements.txt
examples/vertical-fl/simulation.py

A couple of minor fixes: Install `flwr[simulation]` and fix saving of results.

Fix vertical-fl example

---

dev/get-latest-changelog.sh

The script didn't output the list of contributors' names.
N/A
Remove the token before passing the text to `awk`.
N/A

Fix get-latest-changelog script

---

.github/workflows/android-release.yml
.github/workflows/cpp.yml
.github/workflows/framework-release.yml
.github/workflows/update-pr.yml

We sometimes used `ubuntu-latest` in our worflows.
N/A
Use `ubuntu-22.04` everywhere.
N/A

Use specific Ubuntu version for workflows

---

src/docker/server/Dockerfile

Official Flower Docker images
- Added some environment variables that are common for running python in docker.
- Added `--no-cache-dir` because of [DL3042](https://github.com/hadolint/hadolint/wiki/DL3042)
- Made the Ubuntu version configurable.
- Removed installation of poetry. We install the server via `pip` therefore there is no `pyproject.toml` poetry can read from. @tanertopal can you please check if this is correct.

Small improvements to the current server dockerimage

---

datasets/doc/source/how-to-use-with-tensorflow.rst
doc/source/contributor-how-to-develop-in-vscode-dev-containers.rst
doc/source/contributor-how-to-write-documentation.rst
doc/source/contributor-tutorial-get-started-as-a-contributor.rst

- fix rst links 
- fixed docker link by using rst syntax instead of markdown

Fix various RST links 

---

.github/workflows/_docker-build.yml
.github/workflows/docker-base.yml
.github/workflows/docker-server.yml
src/docker/base/Dockerfile
src/docker/server/Dockerfile

Building the server images for non-native platforms (e.g. arm) can take a long time because they run in an emulator. Most of the time is spent installing/compiling python. We want to keep our release CI fast therefore we need to find a way to speed it up.
A python version change will occur less frequently than releasing a new Flower version. The idea is to move this installation to a base image and use that image later when building the server image. This should reduce the build time of the server images. The base image can also be used later for the client images.
This PR moves the installation of system dependencies, python and  general python dependencies into its own Dockerfile. This change significantly reduces the build time of the server images. Building the a server images takes …

Create docker base images

---

.github/workflows/docker-base.yml
.github/workflows/docker-server.yml

We want to provide base images for 3.8, 3.9 and 3.10.
- adjusts the ci job so that we build base images not just for python 3.11 but also for 3.8, 3.9 and 3.10
- renames the job name `Summary` to `Build images` so that the title of the github workflow summary is `Build images summary` instead of `Summary summary`

Add base image for other python versions

---

.github/workflows/docs.yml
baselines/doc/source/conf.py
datasets/doc/source/conf.py
dev/test-copyright.sh
doc/source/conf.py
examples/doc/source/conf.py

The copyright year is currently hardcoded. This PR adds a bit of python code to make it dynamic.

Make copyright year in Flower docs dynamic

---

.github/workflows/_docker-build.yml
.github/workflows/docker-base.yml

The values (python versions) in the matrix were interpreted as floats. When the value `3.10` was passed to the build argument `PYTHON_VERSION` the zero was cut off. This lead the docker build command to fail because it tried to install python `3.1`. 
- convert python version to strings
- turned the value for `fail-fast` to `false`. if one build fails, we still can push the other.
- make artifact name unique (hash of the build args) to prevent jobs from overwriting each other's artifacts

Fix build of docker base image

---

datasets/doc/source/_templates/autosummary/base.rst

In `flwr-datasets`, the base template was not added (when introducing new docs type) because I didn't see the need for that. I didn't see the need because it affects the public functions, and there are not yet any public functions that could have been documented.
The lack of a base template means inconsistent naming. 
The base template dictates the basic behavior regarding the generation of the docs for functions.
The same base template is used here https://github.com/adap/flower/pull/2644 
Add the same template to `flwr-dataset` (here) and to `flwr` (https://github.com/adap/flower/pull/2644 ) for docs consistency.

Add base template for consistent naming convention for functions

---

.github/workflows/e2e.yml

Dependabot does not have access to secrets. Therefore the `Upload wheel` step in the `E2E` workflow is failing.
The issue is fixed by skipping the `upload wheel` step if the actor is dependabot.

Skip upload wheel step for dependabot

---

dev/format.sh

The metadata from running the jupyter notebooks is kept in case of running them in PyCharm.
See this diff for an example of the metadata diff https://github.com/adap/flower/pull/2480/commits/aceeef7bbf903f3ea17b0968b49fc3a5e6030ed5
Extend `--extra-keys` in the `format.sh` script to strip the PyCharm metadata form cells.

Strip pycharm metadata in the format.sh script

---

.github/CODEOWNERS

Adding @jafermarq as codeowner for the doc/source/ref-changelog.md file.

Add Javier as codeowner for the changelog file in docs

---

.github/workflows/e2e.yml

in #2732 we skipped the upload step if the actor is dependabot. ~However, the uploaded artifacts are required for the following jobs. We revert #2732 and allow dependabot upload/downloading the artifacts.~ We forgot to do the same for the install flwr wheel from artifact store step. The CI will still work because flwr is installed in the previous step. 
- ~revert #2732~
- skip install flwr wheel from artifact store step

Fix dependabot pr ci

---

datasets/e2e/tensorflow/pyproject.toml

The python version in pyproject.toml was specified as `python = "^3.8"` which disables the successful versions resolution.
A few new PRs fail due to that reason.
Change to `python = ">=3.8,<3.11"` which is used in many examples to successfully find the proper dependency versions.

Narrow down Python version in FDS TF e2e test

---

pyproject.toml

Docformatter and Ruff create conflicts on multi-line single-sentence docstrings. Ruff requires a blank line between summary line and description (D205) and that closing quotes should be on a separate line (D209).
`docformatter` format:
```py
def foo():
"""Here is a multiline docstring, that is a docstring that has to be split on two lines
but that is still in a single sentence."""
print("Hello")
```
`ruff` format:
```py
def foo():
"""Here is a multiline docstring, that is a docstring that has to be split on two lines
but that is still in a single sentence.
"""
print("Hello")
```
N/A
Ignore the `ruff` checks.
<general>
N/A

Favor Docformatter for multi-line docstrings

---

examples/advanced-pytorch/README.md
examples/advanced-pytorch/client.py
examples/advanced-pytorch/pyproject.toml
examples/advanced-pytorch/requirements.txt
examples/advanced-pytorch/run.sh
examples/advanced-pytorch/server.py
examples/advanced-pytorch/utils.py

Use Flower Datasets in advanced-pytorch example.
* Use proper centralized data for evaluation. 
* Keep the rest conceptually the same.
* Run the server with toy argument.
* Fix the type of torch device.
<examples>

Migrate advanced-pytorch example to use FDS

---

doc/source/contributor-how-to-release-flower.rst

The release doc was outdated.
N/A
Update the documentation to follow the current workflow.
<skip>
N/A

Update release doc

---

doc/source/contributor-tutorial-contribute-on-github.rst

The quote from the PR description comment is hard to read as there is some horizontal scrolling to do.
N/A
Instead of using a code block, we can just use a quote block to get this result:
<skip>
N/A

Make quote in contributor docs easier to read

---

src/py/flwr/common/configsrecord.py
src/py/flwr/common/metricsrecord.py
src/py/flwr/common/parametersrecord.py
src/py/flwr/common/recordset_test.py

* Data in `*Record` can be access via `__getitem__`
* `keep_input` is now just a method argument (not an attribute of a `*Record` dataclass).

Recordset basic enhancements

---

examples/quickstart-huggingface/README.md
examples/quickstart-huggingface/client.py
examples/quickstart-huggingface/pyproject.toml
examples/quickstart-huggingface/requirements.txt
examples/quickstart-huggingface/run.sh

Migrate quickstart huggingface to flwr-datasets
* divide the dataset into 1000 iid partitions
* update script
* solve warnings
* import AdamW from pytorch instead of transformer
<examples>

Migrate quickstart HuggingFace to flwr-datasets

---

src/py/flwr/common/configsrecord.py
src/py/flwr/common/metricsrecord.py
src/py/flwr/common/recordset_test.py

* Empty lists are tested for and allowed
* `MetricsRecord` and `ConfigsRecords` can have list of their respective valid types as long as all elements in the list are of the same type.

Improve records type checking

---

src/py/flwr/server/app.py
src/py/flwr/server/fleet/grpc_rere/fleet_servicer.py

When starting a `flower-server` with SQLite, we get an error saying that SQLite objects created in a specific thread can only be used in that thread.
N/A
The issue is caused by the fact that we pass the same SQLite `State` object to all the `FleetServicer` functions that are called on different threads. Instead, we should create the `State` object in each of the `FleetServicer` functions.
<general>
Should this be an extensive changelog entry?

Fix error when using SQLite with gRPC-rere

---

.github/workflows/e2e.yml
e2e/bare/pyproject.toml
e2e/test_driver.sh
src/py/flwr/client/app.py

The current client callable cannot instantiate REST clients.
N/A
Add a new argument to the callable that instantiates a REST client. Also adds new E2E tests for REST clients.
<general>
N/A

Add REST transport to client callable

---

src/py/flwr/server/fleet/grpc_bidi/flower_service_servicer.py

When running flower behind a proxy, the peer can be the same for different clients (i.e. ip:port) so we use a uuid that is unique. This makes impossible to use flower behind some reverse proxies, like Traefik
Fixes #1972
The peer ID is not used outside the join method, so we can rely on an uuid for each of the clients, so they do not overlap.

Do not use gRPC context peers to identify clients

---

examples/mt-pytorch/driver.py
examples/secaggplus-mt/driver.py
src/py/flwr/driver/app.py
src/py/flwr/driver/driver.py
src/py/flwr/driver/grpc_driver.py

This PR is to make the naming in Driver consistent with other places in `flwr`.
- Renamed the args and variables to `root_certificates` from `certificates` in `Driver` class and `GrpcDriver` class.
- Updated two files in `examples/`

Rename `certificates` to `root_certificates` in `Driver` class and `GrpcDriver` class

---

.github/workflows/framework-release.yml

Currently, the release process fails as the build artifacts are not found by `poetry`.
N/A
Place the build artifacts in a newly created `dist` folder to fix the issue.
<skip>
This PR won't appear on the changelog as I used the `skip` token.

Use `dist` directory when publishing via CI

---

e2e/bare-https/driver.py
e2e/bare/driver.py
e2e/fastai/driver.py
e2e/jax/driver.py
e2e/opacus/driver.py
e2e/pandas/driver.py
e2e/pytorch-lightning/driver.py
e2e/pytorch/driver.py
e2e/scikit-learn/driver.py
e2e/tabnet/driver.py
e2e/tensorflow/driver.py
examples/quickstart-cpp/driver.py
src/py/flwr/server/__init__.py
src/py/flwr/server/app.py
src/py/flwr/server/compat/__init__.py
src/py/flwr/server/compat/app.py
src/py/flwr/server/compat/app_test.py
src/py/flwr/server/compat/driver_client_proxy.py
src/py/flwr/server/compat/driver_client_proxy_test.py
src/py/flwr/server/run_serverapp.py

This PR introduces a new sub-package `flwr.server.compat` and moves compatibility-related functions (mostly `start_driver`) into it

Create server-side compatibility package

---

src/py/flwr/server/app.py
src/py/flwr/server/compat/app.py
src/py/flwr/server/server.py
src/py/flwr/simulation/app.py

Moves `init_defaults` and `run_fl` out of `sever/app.py` and into `server/server.py`. Helps with imports for upcoming features.

Move server functions to `server.py`

---

src/py/flwr/server/compat/app.py
src/py/flwr/server/compat/app_test.py

Make `ServerApp` shutdown at the end.

---

src/py/flwr/server/superlink/fleet/vce/backend/backend.py
src/py/flwr/server/superlink/fleet/vce/backend/raybackend.py
src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/simulation/ray_transport/ray_actor.py

Introducing some components to gracefully terminate a simulation:
* `terminate()` method for Backends. In the case of the `RayBackend` it will manually terminate each actor
* Pass a `asyncio.Event` to the entry function that starts the simulation. This will be used to terminate tasks when the event is (externally) set.

Add `terminate` method to backends and introduce `asyncio` stopping event.

---

baselines/fedpara/README.md

The URL in the FedPara README is wrong.
N/A
Replace it with the correct URL.
<skip>
N/A

Fix incorrect link in FedPara README

---

src/py/flwr/client/mod/centraldp_mods.py

In central DP mods, there needs to be a check if the msg has error before performing the clipping on the content.

Add an error msg check in central DP mods

---

src/py/flwr/common/logger.py

The indent for feature warnings is not aligned with the rest.
N/A
Use correct indent for these warnings.
<skip>
N/A

Use correct indent for logging feature warnings

---

examples/app-pytorch/task.py
src/py/flwr/client/app.py

`flower-client-app` logs are not particularly useful.
N/A
Add `group_id`, `run_id`, `msg_id`, and `msg_type` to logs.
<skip>
N/A

Improve flower-client-app logs

---

src/py/flwr/server/superlink/state/in_memory_state.py

The `InMemoryState` is not thread safe, but this only became apparent when running FL w/ 100K+ nodes.

Make `InMemoryState` thread-safe (again)

---

src/py/flwr/common/pyproject.py
src/py/flwr/common/pyproject_test.py

For the Flower CLI new command we are asking the user for a project name. We expect that project name to be compatible with the `pyproject.toml` file's `name` property as its based on the same PEP
Add a new module in src/py/flwr/common to the Flower project. Name the module `pyproject.py` (as well as wrting tests for it in the `pyproject_test.py`) and add a function to it which can validate the name property. Reference the respective PEP in the function description.

[feat] Validate the name property in `pyproject.toml` file

---

src/py/flwr/client/mod/secure_aggregation/secaggplus_mod.py
src/py/flwr/server/workflow/secure_aggregation/secaggplus_workflow.py

- Fixed a bug that causes empty `FitIns` to be sent to clients.
- Updated the workflow and the mod to pass all `FitRes` from clients to the `aggregate_fit` method.

Fix `SecAggPlusWorkflow` and `secaggplus_mod`

---

src/py/flwr_tool/update_changelog.py

The script to generate the changelog broke with certain characters in titles, and some of the formatting was wrong with some description formats.
N/A
Remove breaking characters and add indent consistently.
<skip>
N/A

Improve formatting for changelog generating script

---

src/py/flwr/server/superlink/fleet/message_handler/message_handler.py

Nodes can now be negative but a check in the `message_handler` ignored this.
N/A
Remove the obsolete check.
<skip>
N/A

Remove legacy check that leads to unregistered clients

---

datasets/flwr_datasets/federated_dataset.py
datasets/flwr_datasets/partitioner/shard_partitioner.py
datasets/flwr_datasets/utils.py

No newline before the code examples causes this kind of problem in the docs
Add new lines before missing python code examples
<skip>

Fix federated dataset docs

---

datasets/doc/source/conf.py

The docs website is showing the `0.0.2` version.
Update the version that is displayed on the website to `0.1.0`
<skip>

Bump up the release version to 0.1.0 in docs

---

src/proto/flwr/proto/task.proto
src/py/flwr/proto/task_pb2.py
src/py/flwr/proto/task_pb2.pyi
src/py/flwr/server/superlink/driver/driver_servicer.py
src/py/flwr/server/superlink/fleet/message_handler/message_handler.py
src/py/flwr/server/superlink/fleet/vce/vce_api_test.py
src/py/flwr/server/superlink/state/in_memory_state.py
src/py/flwr/server/superlink/state/sqlite_state.py
src/py/flwr/server/superlink/state/sqlite_state_test.py
src/py/flwr/server/superlink/state/state_test.py
src/py/flwr/server/utils/validator.py
src/py/flwr/server/utils/validator_test.py

- Adds `pushed_at` into `Task` protobuf definition
- Its value is set at the `SuperLink` (same behaviour as `created_at` but now using timestamps as opposed to iso-dates)
- `created_at` remains, since a follow up PR (https://github.com/adap/flower/pull/3174) will replace it:
- will be defined upon `Message creation`
- All tests associated with existing `created_at` will need to be revisited then.

Add `pushed_at` into `Task`

---

src/py/flwr/client/message_handler/message_handler_test.py
src/py/flwr/common/message.py
src/py/flwr/common/message_test.py

Updates:
- logic in `Message.create_reply` regarding default `ttl`
- logic in `Message.create_error_reply` and always defaulting to default ttl.
- Added test

Update default `TTL` logic in message replies

---

src/py/flwr/client/app.py
src/py/flwr/client/grpc_client/connection_test.py
src/py/flwr/common/retry_invoker.py
src/py/flwr/common/retry_invoker_test.py

- Allow overwriting `actual_wait_time` in event handlers.
- Support custom wait functions.
- Replace `time.time` with `time.monotonic`

Improve `RetryInvoker`

---

src/py/flwr/server/superlink/fleet/vce/vce_api.py

If a Simulation terminates very soon after launching it there is not enough time for the `ServerApp` to initialise itself fully. This makes it complex to terminate it. This PR adds a small time delay (10 seconds) before raising an exception in the Simulation Engine that will shut down everything.
This is an effective solution to the issue when the path to the `ClientApp` module is not found (a check done before actually starting the simulation)

Add delay to `Simulation Engine` termination

---

datasets/pyproject.toml

When updating the Flower Dataset from an older version (with older datasets) version the datasets might be installed such that it shows the following error https://github.com/huggingface/datasets/issues/6352 `"NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")"`
This problem was solved in `2.14.6`. (The other packages that we have as dependencies for audio and images match the versions; no need for an update).
Update the version to prevent the installation of the version of the datasets library that has the bug.
<skip>

Bump up datasets version in Flower Datasets

---

src/py/flwr/common/message.py
src/py/flwr/server/driver/driver.py
src/py/flwr/server/workflow/default_workflows.py
src/py/flwr/server/workflow/secure_aggregation/secaggplus_workflow.py

- Warns once if TTL is set in `create_message()` or `create_reply`.
- `create_message` now accepts optional `ttl` (mirroring `create_reply` signature and logic to set `DEFAULT_TTL`).

Warn once if `TTL` is set

---

examples/custom-mods/README.md

The URL for wandb was missing `https://`.
N/A
Use `https://wand.ai` instead of `wandb.ai`.
<skip>
N/A

Use correct URL in custom mods example

---

src/py/flwr/client/app.py

The legacy client would display an empty round number, which could be confused with an error:
N/A
Remove the logging line for legacy clients:
<skip>
N/A

Disable legacy client round logging

---

src/py/flwr/cli/example.py

It is currently possible to create a project based on the doc folder for examples.
N/A
Exclude `examples/doc` from the list of valid folders.
<skip>
N/A

Remove `doc` folder from `flwr example` cli

---

src/py/flwr/cli/new/new.py
src/py/flwr/cli/utils.py

Currently, we can successfully create an invalid project with `flwr new` if we use a name that isn't a valid Python module string.
N/A
Check if `project_name` contains characters other than `a-zA-Z0-9_`, if so, prompt the user for a new name (with the initial `project_name` sanitized as default).
<skip>
N/A

Add project name validation to `flwr new`

---

src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

Having the license for the projects by default makes it easier for users that don't know much about licensing.
N/A
Add license in `pyproject.toml`
<skip>
N/A

Add license to pyproject.toml files when using `flwr new`

---

src/py/flwr/cli/new/templates/app/README.md.tpl

We removed `poetry` from the `pyproject.toml` files but still have a mention of it in the README.
N/A
Remove mention of `poetry` in the `README` template.
<skip>
N/A

Remove `poetry` mention in README files when using `flwr new`

---

src/py/flwr/cli/new/new.py

The way the code is currently written, only `PyTorch` can have a `task.py` template file.
N/A
Make the code more modular to easily add other frameworks with `task.py` template files.
<skip>
N/A

feat(cli): allow multiple frameworks to have a `task.py` file

---

src/py/flwr/common/telemetry_test.py

This test often fails due to some randomness in the duration.
N/A
Increase the threshold to 5ms.
<skip>
N/A

Increase not_blocking test threshold

---

src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl

After the switch from `flower.toml` to `pyproject.toml`, `pyproject.toml` needs to have `flower.components` declared inside it.
N/A
Add components to `pyproject.toml`.
<skip>
N/A

fix(framework:cli): Add necessary components to `pyproject.toml`

---

src/py/flwr/cli/new/new.py
src/py/flwr/cli/new/new_test.py
src/py/flwr/cli/new/templates/app/README.md.tpl
src/py/flwr/cli/new/templates/app/code/client.pytorch.py.tpl
src/py/flwr/cli/new/templates/app/code/server.pytorch.py.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl
src/py/flwr/cli/utils.py

From [this discussion](https://github.com/adap/flower/pull/3256#discussion_r1573178415):
```
The directory name of the project should allow - (quite common in Python library names). The Python package inside will then use _ instead of - to make it a valid Python package name.
Example:
Project name: flwr-datasets (e.g., pip install flwr-datasets)
Package name: flwr_datasets
```
#3256 
Allow project names with hyphens and replace hyphens with underscores when creating the package.
<skip>
N/A

fix(framework:cli): Allow hypens in flwr new CLI

---

examples/quickstart-huggingface/client.py

``` shell
➜ flower-client-app client:app --insecure
INFO :      Long-running Flower client starting
WARNING :   Option `--insecure` was set. Starting insecure HTTP client connected to 0.0.0.0:9092.
INFO :
INFO :      [RUN -6209049818153668731, ROUND 1]
INFO :      Received: train message 72d4a2c3-a7b4-404c-a329-ff045dba4118
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Map:   0%|                                                            | 0/5 [00:00<?, ? examples/s]Asking to truncate to …
```

Add `model_max_length` to AutoTokenizer in quickstart Hugging Face example

---

src/py/flwr/client/__init__.py
src/py/flwr/client/app.py
src/py/flwr/client/supernode/__init__.py
src/py/flwr/client/supernode/app.py

- Move the `run_client_app` to `supernode/app.py`.
- Restructure the `run_client_app`.

Move `run_client_app` to `supernode.app`

---

src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor_test.py

There is no ping tests in client authentication.
Add ping tests to client authentication.
<sdk>

Add ping tests to client authentication

---

src/py/flwr/common/record/recordset.py

To be consistent with `Metadata`, `Message`, etc.

Hide the private class vars of `RecordSet` with a different approach.

---

pyproject.toml
src/py/flwr/simulation/__init__.py

w/o this change users can do `flwr.simulation.run..` and it will autocomplete with options `run_simulation` and `run_simulation_from_cli`. The latter now is hidden.

Hide `run_simulation_from_cli`

---

src/py/flwr/server/superlink/state/in_memory_state.py
src/py/flwr/server/superlink/state/sqlite_state.py
src/py/flwr/server/superlink/state/state.py
src/py/flwr/server/superlink/state/state_test.py

The order of private and public keys is inconsistent.
Reorder private and public key to private first, public second.

Switch private and public key order in State

---

src/py/flwr/common/logger.py

feat(framework:logging): Make update function more modular

---

src/py/flwr/simulation/run_simulation.py

After the new logging formatting was added, it's not sufficient to just change the Level of a log (e.g. via `logger.setLevel(DEBUG)`) to see on the terminal logs associated to that particular level (and higher). It is needed to also set the level to the `console_handler`.

Set `console_handler` based on `verbose` value for simulations

---

src/py/flwr/server/app.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor_test.py

AuthenticateServerInterceptor has expensive computations that can be optimized.
Change `AuthenticateServerInterceptor` initialization arguments by passing State and retrieve static values in memory.

Change `AuthenticateServerInterceptor` arguments

---

src/py/flwr/server/superlink/state/in_memory_state.py
src/py/flwr/server/superlink/state/sqlite_state.py
src/py/flwr/server/superlink/state/state.py
src/py/flwr/server/superlink/state/state_test.py

Current client authentication implementation does not verify whether `node_id` is assigned to a given public key.
Implement functions in `State` that enables verification of `node_id` assigned to a given public key.

Prepare `State` to enable `node_id` verification

---

doc/source/how-to-enable-ssl-connections.rst

SSL how-to-guide still use deprecated `start_server`.
Update SSL how-to-guide to use Flower Next.

Update SSL how-to-guide to use Flower Next

---

src/py/flwr/common/message.py
src/py/flwr/common/message_test.py
src/py/flwr/common/record/parametersrecord.py
src/py/flwr/common/record/recordset.py
src/py/flwr/common/record/recordset_test.py

Add `__eq__` and `__repr__` to classes

---

doc/source/how-to-authenticate-supernodes.rst
doc/source/index.rst

There is no info about how a valid CSV file should look like in authentication how-to-guide.
Add valid CSV file info in authentication how-to-guide.

Add valid CSV info in authentication guide

---

README.md

The link of LLM example in the overall readme is wrong.
Fix broken link of llm example in readme
<examples>

Fix broken link of llm example in readme

---

src/py/flwr/server/app.py

Deprecating commands. Suggesting to use `flower-superlink` instead.

Deprecate `flower-driver-api` and `flower-fleet-api` commands.

---

src/py/flwr/server/compat/app.py

It was deprecated using `start_driver` without providing a `Driver`. This PR makes it a requirement to pass a `Driver`.

Make `start_driver` require a `Driver` object

---

doc/source/conf.py

Copying this code block
```
$ python server.py
```
Pasting before update: `$ python server.py`
Pasting after update: `python server.py`
---
Copying this code block
``` bash
$ flower-simulation \
--server-app=sim:server_app \
--client-app=sim:client_app \
--num-supernodes=100
```
Pasting before update: 
``` bash
$ flower-simulation \
--server-app=sim:server_app \
--client-app=sim:client_app \
--num-supernodes=100
```
Pasting after update:
``` bash
flower-simulation \
--server-app=sim:server_app \
--client-app=sim:client_app \
--num-supernodes=100
```

docs(framework) Update copybutton behaviour in Flower documentation

---

examples/xgboost-comprehensive/pyproject.toml
examples/xgboost-comprehensive/requirements.txt

`flwr-datasets==0.2.0` in xgboost-comprehensive example will cause naming issue for `partition_id/node_id`.
Update required `flwr-datasets` version to `0.1.0`.
<examples>

Update required `flwr-datasets` version for xgboost-comprehensive example

---

baselines/doc/source/_templates/sidebar/search.html
datasets/doc/source/_templates/sidebar/search.html
doc/source/_templates/sidebar/search.html

Remove `search.html` that's preventing the correct version of docs to be built.

docs(*) Remove placeholder search text to Flower documentation

---

src/py/flwr/client/mod/localdp_mod.py
src/py/flwr/server/strategy/dp_adaptive_clipping.py
src/py/flwr/server/strategy/dp_fixed_clipping.py

Keeping the logs a bit shorter.
before:
```
INFO :      aggregate_fit: central DP noise with standard deviation: %.4f added to parameters
```
proposed change:
```
INFO :      aggregate_fit: central DP noise with %.4f stdev added.
```

Make DP noise logs shorter

---

doc/build-versioned-docs.sh

The current implementation of `build-version-docs.sh` can break silently and make the framework docs outdated in production.
N/A
Make sure that an error will make the CI fail, and force checkout to discard changes.
<skip>
N/A

doc(framework:skip) Fix versioned docs by forcing checkout

---

doc/source/contributor-how-to-build-docker-images.rst
doc/source/how-to-run-flower-using-docker.rst

- Adds documentation for the ServerApp.

docs(docker) Add ServerApps docs

---

.github/workflows/_docker-build.yml
.github/workflows/docker-base.yml
src/docker/base/alpine/Dockerfile
src/docker/base/ubuntu/Dockerfile

- Optimizes the Ubuntu base image.
- Uses `python-build` (a pyenv plugin) to install Python. That makes the `pyenv rehash` call obsolete. 🎉
- Adds a non-root `app` user.
- Uses a multi-stage build to avoid having system dependencies in the final base image that are necessary for Python compilation.
- Use a virtual environment to ensure that Python packages are installed in the same location regardless of whether the subsequent image build is run with the app or the root user (also applies for the Alpine base image).
- Increases the CI timeout to 180 min because the compilation of grpcio on alpine arm64 takes over two hours.
- Adds the Alpine base image to the build CI job.
- Adjusts the Alpine base image to be aligned with the Ubuntu base image (virtual env is under `/app/venv`).

ci(framework) Optimize Ubuntu base image

---

.devcontainer/Dockerfile
.github/actions/bootstrap/action.yml
baselines/flwr_baselines/dev/bootstrap.sh
dev/bootstrap.sh

ci(*:skip) Upgrade pip and setuptools

---

pyproject.toml

Adjusts #3482.
A followup PR (https://github.com/adap/flower/pull/3501) will evaluate if excluding `setuptools==70.0.0` can be done if updating to a more recent version of `ray` is possible.

fix(*:skip) Exclude `setuptools` version from `pyproject.toml`

---

.github/workflows/e2e.yml
e2e/bare-client-auth/pyproject.toml
e2e/bare-https/pyproject.toml
e2e/bare/pyproject.toml
e2e/fastai/pyproject.toml
e2e/jax/pyproject.toml
e2e/opacus/pyproject.toml
e2e/pandas/pyproject.toml
e2e/pytorch-lightning/pyproject.toml
e2e/pytorch/pyproject.toml
e2e/scikit-learn/pyproject.toml
e2e/tabnet/pyproject.toml
e2e/tensorflow/pyproject.toml

This PR improves the speed of the CI for E2E tests.
This PR is inspired by #1975 and [this blogpost](https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d) by Evan Pete Walsh. The CI should be triggered couple of times after that has happened to compare the impact of the caching. 
The CI cache works as follows:
Whenever a new commit or PR is made to the main branch the `Cache Python location` job in `.github/workflows/e2e.yml` will run and cache the following directory:
* `${{ env.pythonLocation }}` (Note that caching only `~/.cache/pip` will cache the wheels, but not the installation itself)
The cache will be overwritten if there is a cache miss. It is retrieved by jobs in pull requests by the following key:
`pip-${{ runner.os }}-${{ matrix.directory }}-${{ …

ci(framework:skip) Add caching to speed up E2E CI tests

---

pyproject.toml

It was added first here last year due to an issue with Ray (https://github.com/adap/flower/pull/2002), but it got removed from the dependencies list last month (https://github.com/adap/flower/pull/3265). It doesn't seem to be needed anymore?

fix(framework:skip) Remove `pydantic` from list of extras in `pyproject.toml`

---

src/py/flwr/server/app.py

This PRs removes the option of passing the `--vce` transport type when starting a `SuperLink` (and consequently the series of actions to launch the Simulation Engine). The preferred way of launching the Simulation Engine is via `flower-simulation <...>` or `flwr.run_simulation(...)`.

break(framework) Remove option to start SuperLink for simulation

---

doc/source/how-to-run-flower-using-docker.rst

- Adds section about root user.
- Updates the Python dependencies version of the SuperNode example. In the example we are using the nightly image that uses Python 3.11. `torch` 2.1.1 however, is not compatible with Python 3.11.
- Removes `pyenv rehash` from the example because it is not needed anymore.
- Removes `client:app` SSL code examples that I forgot to remove.

docs(framework:skip) Add section about root user

---

src/py/flwr/client/app.py
src/py/flwr/client/grpc_rere_client/connection.py

With #3090 we allow clients to exit gracefully but they are not deleted directly on the SuperLink, this can cause "phantom clients" being sampled.
#3090 
- Send a `delete_node` request on shutdown
- Let the daemon thread exit without trying to join (https://stackoverflow.com/a/47443226)
N/A

feat(framework:skip) Add delete node on shutdown

---

src/proto/flwr/proto/grpcadapter.proto
src/py/flwr/proto/grpcadapter_pb2.py
src/py/flwr/proto/grpcadapter_pb2.pyi

As we discussed previously with NVFlare team, the metadata should be a `Dict[str, str]`.

fix(framework) Fix the metadata type in `MessageContainer`

---

src/py/flwr/client/__init__.py
src/py/flwr/client/mod/__init__.py

This PR adds built-in mods to the flwr client docs: [page](https://flower.ai/docs/framework/ref-api/flwr.client.html#module-flwr.client)

docs(framework:skip) Add built-in mods to client doc

---

src/py/flwr/client/app.py

Introduces `RunTracker` to facilitate the graceful shutdown of `SuperNodes`. This PR doesn't change the core behaviour of `flower-client-app`, that is introduced in PRs #3090  and #3531

feat(framework) Introduce `RunTracker`

---

doc/source/how-to-run-flower-using-docker.rst

In the example we by mistake used `chmod` instead of `chown` to change the ownership of the file/directory.

docs(*:skip) Fix chown command

---

src/py/flwr/cli/build.py
src/py/flwr/cli/install.py

We need the installed directory and the filename back from the `install` and `build` functions.
N/A
Modify return types.
N/A

refactor(framework:skip) Add return types to certain CLI functions

---

datasets/pyproject.toml

The CI is failing when the dependency: `datasets` version is 2.20.0 (released on June 13th 2024). 
The default value of the `trust_remote_code` in `load_dataset` (that is used under the hood in `FederatedDataset`) is no longer `True`. 
Why and when is this a problem? 
Some dataset in HF are added as files and some as python scripts that handle downloads (and preprocessing).
In the case of the script, now the `trust_remote_code` must be set explicitly as `True`. 
It affects us bc many dataset are script-based e.g. `mnist`.
Cap the version of the datasets.
`datasets = ">=2.14.6 <2.20.0"`
That's a short term solution. In longer term we want to expose more eaisly passign all the arguments (as kwargs) to the dataset library.

fix(datasets) Limit the datasets versions

---

src/py/flwr/superexec/exec_grpc.py
src/py/flwr/superexec/exec_servicer.py
src/py/flwr/superexec/exec_servicer_test.py
src/py/flwr/superexec/executor.py

feat(framework) Add SuperExec servicer

---

src/py/flwr/cli/config_utils.py

Currently, to extract the `fab_id` and `fab_version` from a FAB file (as path or bytes), it won't work if the FAB is not installed on the environment.
N/A
Use the `check_module` parameter to skip the module verification.
N/A

fix(framework:skip) Skip module checking for metadata extraction

---

src/py/flwr/client/supernode/app.py

We have deprecated `--server` for the supernodes in favour of `--superlink`. Without this change, when launching the supernode via `flower-supernode` if the address of the superlink is specified via the expected `--superlink` the internal variable associated with `--server` is used (which isn't updated from that passed via the cli)

fix(framework) Pass `superlink` address when starting `supernode`

---

README.md

It removes the extra space in main README file.

fix(examples:skip) Fix main README

---

doc/source/_templates/sidebar/lang.html

We have Korean translations but no button that redirects to it:
N/A
Add button that redirects to the Korean version of the docs:
N/A

docs(framework) Add Korean version

---

src/py/flwr/client/app.py
src/py/flwr/client/node_state.py
src/py/flwr/client/node_state_tests.py
src/py/flwr/client/supernode/app.py
src/py/flwr/common/context.py
src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

- The `NodeState` carries the `partition-id` that the `Context` should use
- `SuperNode` gains `--partition-id` flag
- `<context>.partition_id` is unused in this PR -- it will be used in a follow up PR
:warning: TBD if we want to throw a warning when passing `--partition-id` when launching a `SuperNode`. The original motivation for doing so was so to make it clear that thinking about data partitions (in the sense of "one client gets one of the N locally available partitions") does not quite fit how deployment setups work.

feat(framework) Make `NodeState` capture `partition-id`

---

src/py/flwr/client/__init__.py
src/py/flwr/client/app.py
src/py/flwr/client/client_app.py
src/py/flwr/client/message_handler/message_handler.py
src/py/flwr/client/message_handler/message_handler_test.py
src/py/flwr/client/supernode/app.py
src/py/flwr/client/typing.py
src/py/flwr/simulation/app.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py

We are transitioning towards a `client_fn` with signature:
```
def client_fn(node_id: int, partition_id: Optional[int]) -> Client:
...
```
but without introducing breaking changes to existing codebases. In order to do that we need an "adaptor" that is capable of detecting a `client_fn` in the previous formant (i.e. expecting a single `cid:str` argument) and wrap it into a function matching the new `client_fn` signature. This PR accomplishes that.

feat(framework) Introduce `client_fn` adaptor

---

doc/source/explanation-differential-privacy.rst

This corrects a typo in a formula in the DP document.

docs(framework:skip) Fix DP formula

---

src/py/flwr/superexec/app.py

We need to provide a default plugin for the `SuperExec`.
N/A
We add `flwr.superexec.deployment:executor` as a default plugin for `SuperExec`.
N/A

feat(framework:skip) Add default executor for SuperExec

---

pyproject.toml

`black` formats imports like this:
While `isort` formats them like this:
N/A
Set `isort` to `profile = "black"`
N/A

ci(framework:skip) Make isort and black compatible

---

src/py/flwr/client/message_handler/message_handler_test.py
src/py/flwr/client/mod/secure_aggregation/secaggplus_mod_test.py
src/py/flwr/client/mod/utils_test.py
src/py/flwr/client/node_state.py
src/py/flwr/common/context.py
src/py/flwr/server/compat/legacy_context.py
src/py/flwr/server/run_serverapp.py
src/py/flwr/server/server_app.py
src/py/flwr/server/server_app_test.py
src/py/flwr/server/superlink/fleet/vce/backend/raybackend_test.py
src/py/flwr/simulation/ray_transport/ray_client_proxy_test.py

refactor(framework:skip) Add `run_config` as required `Context` parameter

---

.github/workflows/release-nightly.yml

- Extends the nightly CI job to build and publish the SuperExec Docker image.
- Depends on: #3723

ci(framework) Build SuperExec nightly Docker image

---

dev/build-docker-image-matrix.py

- Depends on: #3723 
- Test CI run: https://github.com/adap/flower/actions/runs/9856740485
- Add the SuperExec image to the Docker build CI. 
The following images are build:
- `py3.8-ubuntu22.04`
- `py3.9-ubuntu22.04`
- `py3.10-ubuntu22.04`
- `py3.11-ubuntu22.04`

ci(*:skip) Build SuperExec Docker Image in CI

---

dev/format.sh
dev/test.sh

Add `isort` to `dev/test.sh` and `dev/format.sh` for `benchmarks` directory.

ci(*:skip) Use isort for `benchmarks`

---

src/py/flwr/common/logger.py

Using the standard `warn_deprecated_feature` results in this:
The newly introduced `warn_deprecated_feature_with_example` would look like this:

feat(framework) Introduce a new deprecation function that warns users and provides an code example

---

src/py/flwr/client/app.py
src/py/flwr/client/grpc_adapter_client/connection.py
src/py/flwr/client/grpc_client/connection.py
src/py/flwr/client/grpc_rere_client/connection.py
src/py/flwr/client/message_handler/message_handler_test.py
src/py/flwr/client/mod/secure_aggregation/secaggplus_mod_test.py
src/py/flwr/client/mod/utils_test.py
src/py/flwr/client/node_state.py
src/py/flwr/client/node_state_tests.py
src/py/flwr/client/rest_client/connection.py
src/py/flwr/common/context.py
src/py/flwr/server/compat/legacy_context.py
src/py/flwr/server/run_serverapp.py
src/py/flwr/server/server_app.py
src/py/flwr/server/server_app_test.py
src/py/flwr/server/superlink/fleet/vce/backend/raybackend_test.py
src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py
src/py/flwr/simulation/ray_transport/ray_client_proxy_test.py

Changes in this PR:
- Register `node_id` and `node_config` to the `NodeState`
- The `NodeState` will register a `Context` passing its `node_id` and `node_config`
- For `grpc_rere` the `create_node()` function returns the node_id returned by the `CreateNodeResponse`. This is used to set the `<NodeState>.node_id`.
- Updated places in the code base that directly initialise a `Context`

feat(framework) Capture `node_id`/`node_config` in `Context` via `NodeState`

---

src/py/flwr/client/app.py
src/py/flwr/client/client_app.py
src/py/flwr/client/message_handler/message_handler.py
src/py/flwr/client/message_handler/message_handler_test.py
src/py/flwr/client/typing.py
src/py/flwr/server/superlink/fleet/vce/backend/raybackend_test.py
src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py
src/py/flwr/simulation/ray_transport/ray_client_proxy_test.py

Update, again, the `client_fn` signature. Adjust the functions to support the previous signature (i.e. `client_fn(cid: str)`).
Merge at some point after #3780

feat(framework) Introduce new `client_fn` signature passing the `Context`

---

src/py/flwr/client/app.py
src/py/flwr/client/node_state.py
src/py/flwr/client/node_state_tests.py
src/py/flwr/common/constant.py
src/py/flwr/common/context.py
src/py/flwr/server/superlink/fleet/vce/backend/raybackend.py
src/py/flwr/server/superlink/fleet/vce/backend/raybackend_test.py
src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/simulation/app.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py
src/py/flwr/simulation/ray_transport/ray_client_proxy_test.py

This PR:
- Removes the `partition_id` from Context (this information can be embedded in the `<Context>.node_confg`)
- Because of the above the `NodeState` class also removes the `partition_id` from its constructor.
- In simulation, the `node_config` dict carries both `partition-id` and `num-partitions` keys
- The above keys are now captured in `flwr.common.constants` to ease any further changes to these.
- Some simulation tests were creating a `Context` obj directly. Now they instead create a `NodeState` object and use it to register & retrieve the context. No shortcuts.

refactor(framework) Remove `partition_id` from `Context`

---

e2e/bare-client-auth/client.py
e2e/bare-https/client.py
e2e/bare/client.py
e2e/docker/client.py
e2e/framework-fastai/client.py
e2e/framework-jax/client.py
e2e/framework-opacus/client.py
e2e/framework-pandas/client.py
e2e/framework-pytorch-lightning/client.py
e2e/framework-pytorch/client.py
e2e/framework-scikit-learn/client.py
e2e/framework-tensorflow/client.py
e2e/strategies/client.py
e2e/strategies/test.py

`client_fn(cid)` is deprecated, we need to update e2e tests to use latest args.
Update e2e tests to use latest args.

ci(*:skip) Update client_fn args in e2e tests

---

src/py/flwr/superexec/deployment.py

On the `SuperExec` we currently install the dependencies associated with a given Flower App. This can create situations where conflicting version of `flwr` can be installed.
N/A
Use the `--no-deps` `pip` flag when installing the Flower App.
N/A

fix(framework:skip) Remove dependency installation from SuperExec

---

src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/server/superlink/fleet/vce/vce_api_test.py
src/py/flwr/simulation/run_simulation.py

Pass the `Run` object to the `Simulation Engine` and use it to pre-register the contexts before starting the actual simulation.

refactor(framework) Register `Context` early in Simulation Engine

---

src/py/flwr/cli/run/run.py

feat(framework) Add federation argument to `flwr run`

---

examples/simulation-pytorch/sim.py
src/py/flwr/client/supernode/app.py
src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/simulation/run_simulation.py

The core of the Simulation Engine has a simple mechanism to load the function that would eventually return a `ClientApp`. As Flower has rapidly evolved in terms of what's the origin of a  `ClientApp` object (e.g. a simple python file, or a full FAB) so it has the ways of loading these apps (e.g. loading an associated `pyproject.toml`)
This PR reuses the same mechanism that `flower-supernode` uses to load a function that returns a `ClientApp`. This step represent the first step towards being able to run full FABs from `flower-simulation`.
In addition, this PR caches the `ClientApp` before starting the simulation, making them more efficient to run.

refactor(framework) Improve app loading in simulation engine

---

src/py/flwr/cli/build.py
src/py/flwr/cli/config_utils.py
src/py/flwr/cli/config_utils_test.py
src/py/flwr/cli/install.py
src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.hf.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl
src/py/flwr/cli/run/run.py
src/py/flwr/client/supernode/app.py
src/py/flwr/common/config.py
src/py/flwr/common/config_test.py
src/py/flwr/server/run_serverapp.py
src/py/flwr/superexec/simulation.py

refactor(framework) Switch to `tool.flwr` instead of `flower` in `pyproject.toml`

---

src/py/flwr/client/app.py
src/py/flwr/client/node_state.py
src/py/flwr/client/supernode/app.py

When there is not a `.fab` we still want to be able to read the config in the `pyproject.toml` and potentially override some values embedded in `<Run>.override_config`. To do this we need to call `get_fused_config_from_dir()` when registering a context.

feat(framework) Update context registration when running an app directory

---

src/py/flwr/superexec/simulation.py

Check should have been removed in https://github.com/adap/flower/pull/3829

fix(framework) Enable overriding of run configs with simulation plugin

---

datasets/flwr_datasets/federated_dataset_test.py

The tests that check the expected size of the partition for IidPartitioner were incorrect in the case of uneven sizes.
Update the expected size generation for the IidPartitioner in tests in `test_multiple_partitioners` method.

fix(datasets:skip) Update tests for multiple partitioners

---

datasets/flwr_datasets/federated_dataset_test.py
datasets/flwr_datasets/utils.py

The newly supported `flwrlabs/usps` dataset does not have tests. https://huggingface.co/datasets/flwrlabs/usps
Add tests by downloading the dataset (it's a small image dataset <10,000 rows of images 16x16; <3MB)

feat(datasets) Add tests for usps dataset

---

datasets/flwr_datasets/federated_dataset_test.py
datasets/flwr_datasets/utils.py

Issue
The `Mike0307/MNIST-M` dataset needed for experiments to change the baselines to use FDS does not have tests. https://huggingface.co/datasets/Mike0307/MNIST-M
Proposal
Add tests by downloading the dataset (it's a small image dataset <60,000 rows of images 32x32; ~143 MB)

feat(datasets) Add tests for `mnist-m` dataset

---

datasets/flwr_datasets/utils.py

Feature-wise it's just like speech_commands, therefore no new tests were added

feat(datasets) Add ted-lium dataset to the tested set

---

dev/changelog_config.toml
src/py/flwr/cli/new/new.py
src/py/flwr/cli/new/new_test.py

feat(framework) Prompt user for confirmation before flwr new override

---

.github/workflows/datasets.yml

When changing the `.github/workflows/datasets.yaml` the tests for FDS do not run.
This workflow is constrained to run only if there are changes related to the datasets i.e. `- "datasets/**"` this has to change.
https://github.com/adap/flower/pull/3865 PR requires this PR to be merged to have the datasets test triggered.
Extend the path to the code that needs to be changed to trigger datasets tests. Apply it for both `push` and `pull_reqest.`

ci(datasets:skip) Extend datasets GitHub workflow to trigger test if it changes

---

datasets/flwr_datasets/federated_dataset.py
datasets/flwr_datasets/federated_dataset_test.py
datasets/flwr_datasets/metrics/utils_test.py
datasets/flwr_datasets/partitioner/natural_id_partitioner.py
datasets/flwr_datasets/partitioner/natural_id_partitioner_test.py
datasets/flwr_datasets/partitioner/partitioner.py
datasets/flwr_datasets/preprocessor/merger_test.py
datasets/flwr_datasets/utils.py
datasets/flwr_datasets/visualization/bar_plot.py
datasets/pyproject.toml

* Update the pylint version to match the core framework.
* Fix all the code that was flagged by the new version of pylint.

ci(datasets:skip) Update pylint version

---

datasets/flwr_datasets/mock_utils_test.py

Not all the datasets are perfectly resembled for tests.
Perform partial download in order to resemble datasets better.
Note there's no function to perform that in the `datasets` library; this is a solution to enable that.

feat(datasets) Add function to perform partial download of dataset for tests

---

src/py/flwr/cli/new/templates/app/code/task.hf.py.tpl
src/py/flwr/cli/new/templates/app/code/task.mlx.py.tpl
src/py/flwr/cli/new/templates/app/code/task.pytorch.py.tpl
src/py/flwr/cli/new/templates/app/code/task.tensorflow.py.tpl

Caching the `FederatedDataset` object creation and its partitioner makes simulations more efficient.
Additional changes:
* use full names of the dataset e.g. instead of `mnist` use `ylecun/mnist` (related to recent names change on HF Hub; both work, though `mnist` can't be found right now, it's available under the `ylecun/mnist` name)
* `trust_remote_code=True` in `FederatedDataset` for `mnist` dataset to avoid the warning of the dataset that does NOT have file representation on HF Hub (note the remaining dataset in the templates have file representation on HF Hub)
* explicit import of `IidPartitioner` to simplify user to switch to other partitioning schemes (instead of using the `partitioners={split-name: num_partitions}` shorter API now it's `partitioners={split-name: …

feat(framework) Use dataset caching in `flwr new` templates

---

src/py/flwr/superexec/simulation.py

The `SuperExec` uses a dictionary to store the user configs that are to be overrided from `flwr run`. In order to pass these to the `flower-simulation` we need to convert them back to the format `key=value,anotherkey=anothervalue`

fix(framework:skip) Convert `UserConfig` to `str` for simulation executor

---

src/py/flwr/cli/new/templates/app/code/client.hf.py.tpl
src/py/flwr/cli/new/templates/app/code/client.mlx.py.tpl
src/py/flwr/cli/new/templates/app/code/client.pytorch.py.tpl
src/py/flwr/cli/new/templates/app/code/client.sklearn.py.tpl
src/py/flwr/cli/new/templates/app/code/client.tensorflow.py.tpl
src/py/flwr/server/superlink/fleet/vce/vce_api.py

Remove the `str()` casting of `NodeState`'s config when pre-registering context for simulation. This effectively enables removing the `str()` casting in `client_fn` in our templates.

fix(framework) Remove `str` casting for node config

---

src/py/flwr/cli/new/templates/app/code/task.mlx.py.tpl
src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

refactor(framework:skip) Rename default federation in templates

---

doc/build-versioned-docs.sh
doc/source/conf.py

docs(framework) Remove docs before 1.8.0

---

datasets/doc/source/index.rst

The description of FDS lacks keywords `heterogeneity` and `non-iidness`, which are crucial descriptors of the library's features.
Expand the short description of Flower Datasets.

docs(datasets) Add information about heterogeneity to FDS description

---

datasets/doc/source/conf.py

When copying the code from the docs examples, everything is copied, but things like ">>> " shouldn't be copied.
The user does not need the prompt or the output to be copied.
e.g. if you go to `DiricheltPartitioner` and copy the code example you get exaclyt:
```
>>> from flwr_datasets import FederatedDataset
>>> from flwr_datasets.partitioner import DirichletPartitioner
>>>
>>> partitioner = DirichletPartitioner(num_partitions=10, partition_by="label",
>>>                                    alpha=0.5, min_partition_size=10,
>>>                                    self_balancing=True)
>>> fds = FederatedDataset(dataset="mnist", partitioners={"train": partitioner})
>>> partition = fds.load_partition(0)
>>> print(partition[0])  # Print the first example
{'image': …
```

docs(datasets) Improve docs code examples copying experience

---

datasets/flwr_datasets/mock_utils_test.py
datasets/flwr_datasets/partitioner/shard_partitioner.py

natual -> natural in ShardPartitioner implementation and one comment.

fix(datasets:skip) Fix ShardPartitioner typo

---

datasets/flwr_datasets/federated_dataset.py

The description of the int specification of the `partitioners` param of the `FederatedDataset` can be more descriptive.
Clarify what it means to specify the `partitioners` as an `int`.

docs(datasets) Clarify the partitioner parameter docs of FederatedDataset

---

datasets/doc/source/tutorial-quickstart.ipynb

Due to the key to value datasets.Dataset the behavior is slightly different of wrapping the Dataloader around it. This difference is not explained.
Add an explanation in the `tutorial-quickstart.`

feat(datasets) Clarify how the dataloader works with HF dataset

---

datasets/doc/source/index.rst

There's no info on why the user should use Flower Dataset by seeing the benefits of the library stated in an explicit manner.
Add a distinguishing features section to the index file.

docs(datasets) Add info about distinguishing features of Flower Datasets

---

doc/source/tutorial-quickstart-pytorch.rst
doc/source/tutorial-quickstart-scikitlearn.rst

Correct the description of the sample document of the client

docs(framework) Fix quickstart comments

---

src/py/flwr/superexec/simulation.py

Set verbose output to track FAB installation. To use, pass `verbose=true` to `--executor-config`, i.e. `--executor-config num-supernodes=2,verbose=true`.

feat(framework:skip) Add verbose logging for `SimulationEngine`

---

baselines/flanders/README.md

title wasn't present in the readme

fix(baselines:skip) Fix `FLANDERS` readme

---

src/py/flwr/cli/new/new.py

The new order is as set in the `MlFramework` class.

refactor(framework) Change order of frameworks shown with `flwr new`

---

pyproject.toml

A tiny reformatting of our `pyproject.toml`. We should eventually add `taplo` to our pre-commit. 
There's a Python compatible version being developed, as discussed [here](https://github.com/tamasfe/taplo/pull/549).

refactor(framework:skip) Format `pyproject.toml`

---

src/py/flwr/server/driver/grpc_driver_test.py
src/py/flwr/server/driver/inmemory_driver_test.py

ci(framework) Extend tests for `fab_hash`

---

src/py/flwr/cli/config_utils.py
src/py/flwr/server/superlink/driver/driver_servicer.py

fix(framework) Fix end-to-end FAB delivery

---

src/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor.py

Authenticated create node does not produce any log which creates confusion.
Add log to differentiate authenticated create node.

fix(framework) Add log to differentiate authenticated create node

---

.github/workflows/_docker-build.yml
src/py/flwr/client/grpc_rere_client/client_interceptor_test.py

Client interceptor tests don't work because context manager captures all exceptions, making the pytests seems to pass.
Fix client interceptor tests.

refactor(*:skip) Fix client interceptor tests

---

src/py/flwr/client/app.py
src/py/flwr/client/node_state.py
src/py/flwr/common/config.py

If `--isolation` is set, the `SuperNode` doesn't install the `FAB`. This prevents the `context` (which needs to be passed to the external process that runs the `ClientApp`) from being fully initialized with the content of the `pyproject.toml` and, optionally, any override to the `run-config`
This PR enables yet another way to process `<NodeState>.register_context()` that's first extracts the `pyproject.toml` from a `FAB` w/o installing it.

fix(framework:skip) Enable `SuperNode` to complete context registration when `FAB` is not installed

---

datasets/flwr_datasets/partitioner/partitioner.py
datasets/flwr_datasets/partitioner/partitioner_test.py

The partitioner does not check if the type of the assigned dataset is as expected.
This issue was not seen since, typically, the dataset assignment happens inside federatedDataset; however, if ppl use the partitioner alone (for local data), then as shown in the Slack channel, it can happen (then the error is completely non-informative).
Add type check for the dataset assignment. Add tests for that too.

feat(datasets) Add dataset type check for dataset assignment

---

dev/build-docker-image-matrix.py

- Adds a SuperNode Alpine Docker image.
- The version tag will from now on point to the new Alpine image instead of `py3.11-ubuntu22.04`.
Complete list of SuperNode images tags from version Flower 1.11.0:
`1.11.0-py3.8-ubuntu22.04`
`1.11.0-py3.9-ubuntu22.04`
`1.11.0-py3.10-ubuntu22.04`
`1.11.0-py3.11-ubuntu22.04`
`1.11.0-py3.11-alpine3.19`, `1.11.0`

feat(framework:skip) Add SuperNode Alpine Docker image

---

src/py/flwr/simulation/run_simulation.py

Deprecate `--server-app` and `--client-app` arguments for `flower-simulation` command.

fix(framework) Edit `flower-simulation` args

---

src/py/flwr/cli/build.py

This change is needed so if a `FAB` can be "manually" installed from `flwr install`. This is not an issue when the `FAB` is installed from `bytes` since in such setup the file name checks can't be performed.

fix(framework) Read project name from `pyproject.toml` in `flwr build`

---

doc/source/ref-api-cli.rst

Add a note to inform about the change in `flower-server-app` no longer supporting passing a path to a `SeverApp` attribute.

docs(framework) Add note to `flower-server-app` CLI ref

---

src/py/flwr/server/run_serverapp.py

Similar to #4076, this PR add extra checks in the `flower-server-app` code. If users pass a reference instead of a path to `flower-server-app`, they will receive a prompt about how to use the CLI correctly.
For example:

feat(framework:skip) Print prompts when users pass a reference instead of a path to `flower-server-app`

---

src/py/flwr/cli/app.py

Remove the `flwr example` command from the CLI while keeping the logic in `src/py/flwr/cli/example.py` so it can, in the future be extracted and integrated into the `flwr new`.

break(framework) Remove `flwr example` command

---

src/py/flwr/client/supernode/app.py

We were potentially passing a `List[None]` to a function that expects `Optional[List[str]]`

fix(framework:skip) Parse node config if set

---

src/py/flwr/simulation/run_simulation.py

fix(framework:skip) Fix parsing run config in simulation

---

src/py/flwr/superexec/app.py

fix(framework) Fix parsing `executor_config` if present

---

src/py/flwr/client/grpc_rere_client/client_interceptor.py
src/py/flwr/client/grpc_rere_client/client_interceptor_test.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor_test.py

As explained in [google protobuf documentation](https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html#google.protobuf.message.Message.SerializeToString), the `SerializeToString` method only accept keyword arguments. In some settings, as spotted by Robert and Danny, the following exception will be raised when calling `SerializeToString(True)`, i.e., a positional argument instead of a keyword argument is passed.
```
TypeError: _AddSerializeToStringMethod.<locals>.SerializeToString() takes 1 positional argument but 2 were given
```
Change `SerializeToString(True)` to `SerializeToString(deterministic=True)`.

fix(framework:skip) Specify keyword `deterministic`  in `SerializeToString` method

---

src/py/flwr/cli/new/templates/app/code/client.tensorflow.py.tpl

Since we initialize a server-side global model, `get_parameters` is redundant in `FlowerClient`.

refactor(framework:skip) Remove `get_parameters` from `flwr` TensorFlow template

---

src/py/flwr/cli/new/templates/app/code/client.huggingface.py.tpl
src/py/flwr/cli/new/templates/app/code/server.huggingface.py.tpl
src/py/flwr/cli/new/templates/app/code/task.huggingface.py.tpl
src/py/flwr/cli/new/templates/app/pyproject.huggingface.toml.tpl

Updates `HF` `flwr new` template.
needs: https://github.com/adap/flower/pull/4119

refactor(framework) Update `huggingface` template for `flwr new`

---

examples/flowertune-llm/flowertune_llm/client_app.py
examples/flowertune-llm/flowertune_llm/models.py
examples/flowertune-llm/flowertune_llm/server_app.py
examples/flowertune-llm/pyproject.toml

Update FlowerTune LLM example:
- Move get/set parameters functions from `client_app.py` to `models.py`.

refactor(examples) Update get/set parameters functions for `flowertune-llm` example

---

src/py/flwr/superexec/deployment.py
src/py/flwr/superexec/exec_servicer.py

Fixes:
* In `_capture_logs`, add `sys.stdout.write()` and `sys.stdout.flush()` to print live logs to terminal. This is necessary when `stdout` and `stderr` are piped in `subprocess.Popen`.
* Add `context.cancel()` so that gRPC server initiates cancellation of gRPC call. Using `return` does not cancel and clean up, resulting in endless print.

fix(framework:skip) Fix SuperExec log capturing

---

examples/flower-secure-aggregation/secaggexample/server_app.py

The strategy may only sample 2 clients for fit round in simulation, which might b/c the simulation engine hasn't started all SuperNodes yet.

fix(examples:skip) Specify `min_fit_clients` in `FedAvg` in the Secure Aggregation example

---

.github/workflows/e2e.yml

A fix to allow #3790 to be merged. 
Currently, the SuperExec CI relies on `flwr` installed from our artifact bucket. One of the conditions is that the PR must originate from the main repository (not a fork). Unfortunately, this prevents contributors' PRs (like #3790) from [passing our CI](https://github.com/adap/flower/actions/runs/11111502524). This PR lifts this restriction for the SuperExec CI by installing `flwr` via `pip`.

ci(*:skip) Enable SuperExec CI from fork

---

src/py/flwr/client/supernode/app.py

When spinning up a SuperNode using `flower-supernode`, users can specify the `flwr-dir` argument to point to a non-default location where Flower apps are installed. But currently, `flwr_path` is not set in the call to `start_client_internal()`. This PR fixes it.

fix(framework) Pass Flower path to the call to `start_client_internal()` in SuperNode

---

src/py/flwr/server/superlink/state/in_memory_state.py
src/py/flwr/server/superlink/state/sqlite_state.py
src/py/flwr/server/superlink/state/state_test.py

when storing a `task_res`, check that the `task_ins`'s `consumer_id` is equal to the `task_res`'s `producer_id`.

fix(framework:skip) Check `consumer_id` and `producer_id` when saving TaskRes

---

.github/workflows/e2e.yml

Add a CI test for `flwr build` and `flwr install`.

ci(framework) Add FAB build/install test

---

src/py/flwr/common/config.py

fix match error when overriding config args with '.' (like 'model.quantization')
Fixes #4317
flatten override_config to make two dicts aligned

fix(framework:skip) Update config utils to flatten overrides

---

examples/opacus/README.md

A comment copies alongside the command from a code block in readme file.
Related to #4262 and #4328
Move the comment before the code block.

refactor(examples:skip) Move a comment out of the code block in opacus example

---

src/py/flwr/client/supernode/app.py
src/py/flwr/server/app.py

- Updates the help message associated to `--flwr-dir`
- Moves the "Start SuperNode/Superlink" logs after the argparse has been processed (so they do not appear if a user does `flower-supernode --help` or `flower-superlink --help`.

refactor(framework) Make argparse processing the first action of `SuperNode` and `SuperLink`

---

src/py/flwr/client/app.py
src/py/flwr/client/node_state_tests.py
src/py/flwr/client/run_info_store.py
src/py/flwr/server/superlink/fleet/vce/backend/raybackend_test.py
src/py/flwr/server/superlink/fleet/vce/vce_api.py
src/py/flwr/simulation/ray_transport/ray_client_proxy.py
src/py/flwr/simulation/ray_transport/ray_client_proxy_test.py

This is the first step towards constructing a proper `NodeState` at the `SuperNode`

refactor(framework) Rename `NodeState` to `DeprecatedRunInfoStore`

---

pyproject.toml
src/py/flwr/superexec/app.py

A deprecation notice is shown when doing `flower-superexec` since this service now lives in the `SuperLink`.
> [!NOTE]
> Should we add a deprecation note to the CLI ref docs as we did with `flower-client-app` a while ago? https://flower.ai/docs/framework/ref-api-cli.html#flower-server-app

refactor(framework) Show deprecation notice for `flower-superexec`

---

src/py/flwr/client/app.py
src/py/flwr/client/supernode/app.py
src/py/flwr/common/constant.py

Moved `ISOLATION_MODE_SUBPROCESS` and `ISOLATION_MODE_PROCESS` to `common.constants` so they can be reused for the `superlink`

refactor(framework:skip) Set isolation modes as codebase constants

---

src/py/flwr/server/run_serverapp.py
src/py/flwr/simulation/run_simulation.py

the `flwr-serverapp` process will pass an existing `Context` to this function to load and execute a `ServerApp`. At the end, the updated `Context` will be returned.
> [!NOTE]
> The `run` function is also used by the Simulation Engine.

refactor(framework) Enable passing an existing `Context` to `ServerApp` startup function

---

src/py/flwr/server/superlink/driver/driver_servicer.py

For some reason, `HasField` method doesn't work for scalar fields. We have to get around with this by implementing a `_has_field` function.

fix(framework) Fix the bug in `HasField` method

---

examples/quickstart-pytorch/pytorchexample/task.py

An error occurs when running quickstart-pytorch using GPU:
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same.
Fixes #4384.
FL training results are guaranteed when the user is running with the GPU in this project.

fix(examples) Fix `quickstart-pytorch` GPU RuntimeError

---

examples/embedded-devices/Dockerfile

There is a typo in the code that installs 'flwr-datasets' in the Dockerfile, so the process cannot proceed.
Fix the typo "flwr-datsets" to "flwr-datasets".
- [v] Implement proposed change
- [v] Write tests
=> No need

fix(examples) Update Dockerfile

---

baselines/doc/source/how-to-contribute-baselines.rst

We stopped specifying `--run-config` with `,`-separated entries but this page wasn't updated.
Addresses: https://github.com/adap/flower/issues/4366

docs(baselines) Fix instructions on how to use baselines

---

src/py/flwr/cli/build.py

Throws inaccurate error saying that valid project name can include `underscores`. This is wrong. 
Change is small in [cli](https://github.com/adap/flower/blob/7fc4261d9d8565d95d14849634fa1db8861ef254/src/py/flwr/cli/build.py).
N/A
Change text to say that valid project name includes `hyphens` and __not__ `underscores`. 
To prevent confusion. 
- [ x] Implement proposed change
- [ x] Write tests
- [ x] Update [documentation](https://flower.ai/docs/writing-documentation.html)
- [ x] Make CI checks pass
- [ x] Ping maintainers on [Slack](https://flower.ai/join-slack/) (channel `#contributions`)

docs(framework) Change description for invalid project name

---

src/py/flwr/server/superlink/driver/driver_servicer.py
src/py/flwr/superexec/deployment.py

Creates the `Context` after the `Run` is registered at the `LinkState`. This makes `PullServerAppInputs` to always return a existing context obj

refactor(framework) Create `Context` by `Exec` servicer

---

src/py/flwr/server/app.py

`subprocess.run()` is blocking. This is not what we want in the scheduler thread.

refactor(framework) Launch `flwr-serverapp` with `subproces.popen`

---

src/py/flwr/server/superlink/driver/driver_servicer.py

The function was used to check if a scalar field of a grpc message is set to non-default value or not. It's not needed any more.

refactor(framework:skip) Remove unused internal function `_has_field`

---

src/py/flwr/simulation/run_simulation.py

The simulation engine (via `flower-simulation`) now only supports passing an app.

refactor(framework) Remove support for non-app simulations

---

src/proto/flwr/proto/exec.proto
src/py/flwr/cli/run/run.py
src/py/flwr/common/config.py
src/py/flwr/proto/exec_pb2.py
src/py/flwr/proto/exec_pb2.pyi
src/py/flwr/superexec/deployment.py
src/py/flwr/superexec/exec_servicer.py
src/py/flwr/superexec/executor.py
src/py/flwr/superexec/simulation.py

This PR replaces the `federation_config` with `federation_options`. The change brings also uses a `ConfigsRecord`.

refactor(framework) Make `federation_options` in `Exec` API use `ConfigsRecords`

---

doc/source/tutorial-series-what-is-federated-learning.ipynb

`dev/format.sh` is showing a diff in `doc/source/tutorial-series-what-is-federated-learning.ipynb`. This PR fixes that diff (although I cannot see what the diff is).

docs(framework:skip) Format notebook

---

src/py/flwr/cli/build.py

- Uses `hatchling`'s [WheelBuilder](https://hatch.pypa.io/1.13/plugins/builder/wheel/) to build a wheel in the App directory
- The relative path (i.e. within the app dir) is added under `[tool.flwr.app]` in the `pyproject.toml` of the constructed `FAB`
- The `.whl` is removed from the App directory upon successful completion of the `FAB` build process.
Assumed has been merged: https://github.com/adap/flower/pull/4473

feat(framework) Build a Python wheel when building the `FAB`

---

src/py/flwr/superexec/simulation.py

- It is no longer needed to specify the number of supernodes when launching the `SuperLink` with the simulation plugin. This means the exec w/ simulation plugin can be now launched as:
```shell
flower-superlink --insecure  --executor flwr.superexec.simulation:executor
```
- A check for `num-supernodes` in the federation options is performed before creating the Run.

refactor(framework) Remove `num-supernodes` requirement from simulation exec plugin

---

src/py/flwr/server/superlink/fleet/rest_rere/rest_api.py

Although we can easily fix this by changing just one line of code, I added casting to make future debugging easier and reduce errors, allowing our IDE to detect potential issues.

fix(framework) Fix the usage of `FfsFactory` in `rest_api.py`

---

src/py/flwr/client/app.py
src/py/flwr/client/clientapp/app.py
src/py/flwr/client/supernode/app.py
src/py/flwr/server/serverapp/app.py
src/py/flwr/simulation/app.py
src/py/flwr/superexec/deployment.py

To clearly reference the `server`/`clientappio_api_address`, rename internal variables.

refactor(framework:skip) Rename internal `*AppIo` variables

---

src/py/flwr/client/app.py
src/py/flwr/client/clientapp/app.py
src/py/flwr/client/supernode/app.py
src/py/flwr/server/app.py
src/py/flwr/server/serverapp/app.py

The usage of `--superlink` and `--supernode` args for `flwr-serverapp` and `flwr-clientapp`, respectively, doesn't accurately reflect the address they are connected to, which are the `ServerAppIO` and `ClientAppIO` API addresses. 
For clarity, we rename them as follows:
* `flwr-serverapp --superlink` is renamed to `flwr-serverapp --serverappio-api-address`
* `flwr-clientapp --supernode` is renamed to `flwr-clientapp --clientappio-api-address`

break(framework) Rename `flwr-serverapp` and `flwr-clientapp` CLI args

---

doc/source/docker/run-quickstart-examples-docker-compose.rst
examples/quickstart-tensorflow/pyproject.toml

The existing Quickstart Tensorflow example cannot be `pip` installed for `aarch64` platforms. This PR fixes the dependency.

fix(examples:skip) Fix `tensorflow` version in quickstart example for `x86_64` and `aarch64` platforms

---

dev/update_version.py

We want to make changes to the Docker Compose update as part of the Git tag, rather than changing it after a new version is released. This way, we can pin the version to the tag in the Docker Compose example page:https://github.com/adap/flower/pull/4531

feat(framework:skip) Replace Docker Compose version with next version

---

src/py/flwr/cli/run/run.py

When a `flwr run` fails at `res = stub.StartRun(req)`, the FAB file will not be deleted. This PR moves the `unlink()` just after the FAB is created.

feat(framework:skip) Delete FAB after conversion to bytes

---

datasets/doc/source/index.rst

The reference to the recommended FL datasets is missing in the index (also doctree)
Add the link to the "Reference docs"

docs(datasets:skip) Add reference to recommended datasets to the index

---

datasets/flwr_datasets/partitioner/distribution_partitioner.py

The formula in the `DistributionPartitioner` is misformatted 
Now:
Fix it by having the formula as the code block
Fixed:

docs(datasets) Fix formatting of the DistributionPartitioner docs

---

e2e/test_reconnection.sh

ci(framework) Fix process kill in E2E tests

---

src/py/flwr/server/app.py

The `load_executor` function relies on `load_app` to import the executor module. This creates issues when this has been already imported at the top of the `sever/app.py`. The fix in this PR removes the import while maintaining the same functionality.

fix(framework) Avoid reimporting simulation executor plugin

---

src/py/flwr/server/app.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor_test.py
src/py/flwr/server/superlink/linkstate/sqlite_linkstate.py

The `AuthenticateServerInterceptor` is executed a in a threadpool (https://github.com/adap/flower/blob/7504d556ccb00d5edc6d2d284a2abfa7c3a8570a/src/py/flwr/server/superlink/fleet/grpc_bidi/grpc_server.py#L265) and because of this the Executor should create a new connection for any given thread accessing the DB. This is because SQLite objects created in a thread can only be used in that same thread.
The fix is simple: pass the `state_factory` to the Interceptor constructor and create a new connection when needed (in each method that needs to interact with the underlying `state`).
This PR also removes an unnecesssary `threading.Lock` from the `SQLiteLinkState` @panh99

fix(framework) Pass state factory instead of state object to `AuthenticateServerInterceptor`

---

.github/CODEOWNERS
framework/docs/build-versioned-docs.sh

docs(framework) Update path dynamically for versioned script

---

examples/custom-metrics/pyproject.toml

In the pyproject.toml file, there is a typo in the dependencies: "tensorflows" instead of "tensorflow", 
leading to error on `pip install -e .`, which is fixed by this PR. Kindly check maintaners

fix(examples) Fix typo in `pyproject.toml` in custom-metrics example

---

src/py/flwr/common/secure_aggregation/secaggplus_utils.py

The dtype of the result of `np.random.randint` may vary cross platforms and versions. It's better to fix the dtype.

refactor(framework) Fix dtype to `np.int64` in `pseudo_rand_gen` function

---

examples/quickstart-mlx/pyproject.toml

The numpy comes with `flwr`, so we don't need to specify a numpy version here.

refactor(examples) Upgrade the `mlx` version and remove `numpy` dependency in the MLX example

---

src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl

The numpy comes with `flwr`, so we don't need to specify a numpy version here.

refactor(framework) Upgrade the `mlx` version and remove `numpy` dependency in the MLX template

---

src/py/flwr/server/superlink/linkstate/in_memory_linkstate.py
src/py/flwr/server/superlink/linkstate/linkstate.py
src/py/flwr/server/superlink/linkstate/linkstate_test.py
src/py/flwr/server/superlink/linkstate/sqlite_linkstate.py

Required for deleting `TaskIns`/`TaskRes` from `LinkState` for a stopped `run_id` in `ExecServicer`.
Merge before:
* #4684

feat(framework) Add get `TaskIns` from `run_id` to `LinkState`

---

src/py/flwr/cli/ls.py

The `flwr ls` docstrings lack description which may cause confusion to users. This PR updates the docstring and explains the details provided from the `flwr ls` command. 
The updated docstring generates the following in our `ref-api-cli`:

feat(framework) Update `flwr ls` docstring

---

examples/vertical-fl/pyproject.toml

… dependency conflict
This PR is to fix issue #4722 
Removes the `numpy` specification in `pyproject.toml`. As this was causing a dependency conflict. This issue arises because until recently flower had to use numpy<2.0 but this was removed a couple of releases ago.

fix(examples) Remove `numpy` specification in `vertical-fl`

---

examples/quickstart-pandas/pyproject.toml
examples/vertical-fl/pyproject.toml

Related to https://github.com/adap/flower/pull/4724, the `numpy` version is not supported anymore in `flwr`. We set a minimum version to `1.26.0`.

fix(examples) Update pinned `numpy` in `quickstart-pandas` and `vertical-fl` examples

---

src/py/flwr/server/superlink/linkstate/sqlite_linkstate.py

Affects only when `SuperLink` runs with `--database`
Before (note the `FAB` column):
```
(my-fancy-env) ➜  mega flwr ls
Loading project configuration...
Success
📄 Listing all runs...
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃       Run ID        ┃ FAB  ┃ Status  ┃ Elapsed  ┃      Created At      ┃      Running At      ┃ Finished At ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ 2887514479649176794 │  (v) │ running │ 00:00:01 │ 2024-12-17 19:06:12Z │ 2024-12-17 19:06:13Z │ N/A         │
└─────────────────────┴──────┴─────────┴──────────┴──────────────────────┴──────────────────────┴─────────────┘
```
After (note the `FAB` column):
```
(my-fancy-env) ➜ …
```

fix(framework) Record `fab-id` and `fab-version` also in `SQLLinkState`

---

src/py/flwr/cli/ls.py

The `flwr ls` command raises a `ValueError` on [this line](https://github.com/adap/flower/blob/470ba4a58537c70932582df0e7e1edb1d6d2b523/src/py/flwr/cli/ls.py#L316) if a run ID is not found. This won't be suppressed because the call to `restore_output` is made before the `ValueError` is raised. This PR fixes this for `flwr ls`.
To reproduce, run `flwr ls 123 --format json` before and after the fix. 
``` bash
➜ flwr ls --run-id 123 --format json
❌ Run ID 123 not found
{
"success": false,
"error-message": "Loading project configuration... \nSuccess\n Displaying information for run ID 123...\n\n"
}
```
and after:
``` bash
➜ flwr ls --run-id 123 --format json
{
"success": false,
"error-message": "Loading project configuration... \nSuccess\n Displaying information for run ID 123...\n Run ID 123 …
```

fix(framework) Suppress output when in JSON format for `flwr ls`

---

examples/xgboost-quickstart/README.md
examples/xgboost-quickstart/pyproject.toml

* The `flwr` version in `pyproject.toml` is not up-to-date. This is upgraded to the latest release, which is tested to work with Python 3.11.8.
* Added a note to run `brew install libomp` for new installation on MacOSX because by default, the `libomp` is cannot be loaded, giving the error below:
```
File "/Users/csng/.pyenv/versions/3.11.8/envs/xgb-3.11.8/lib/python3.11/site-packages/xgboost/core.py", line 222, in _load_lib
raise XGBoostError(
xgboost.core.XGBoostError:
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
* OpenMP runtime is not installed
- vcomp140.dll or libgomp-1.dll for Windows
- libomp.dylib for Mac OSX
- libgomp.so for Linux and other UNIX-like OSes
Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
* You are running 32-bit Python …
```

fix(examples) Update `flwr` version for XGBoost quickstart example and add `libomp` command for MacOSX

---

datasets/pyproject.toml

Python `3.12`, `3.13` are not added to the classifier list. 
Add them to match the `flwr` specs.

feat(datasets) Add missing Python classifiers

---

datasets/docs/source/how-to-install-flwr-datasets.rst

Instructions on the installation of `flwr-datasets` directly from GitHub are missing. However, by having multiple libraries in a single repo, a more complex URL needs to be specified for pip installation.
* Add instructions about the installation from GitHub
* Update the min required Python versions to 3.9 (outdated info about 3.8).

feat(datasets) Update installation guide

---

src/py/flwr/cli/utils.py

To prevent unintentionally committing `.credentials` to the repository, add `.gitignore` to the Flower directory and write `.credentials` to it. Alternatively, if `.gitignore` already exists in the Flower directory, append to it.

refactor(framework) Add `.credentials` to `.gitignore`

---

datasets/flwr_datasets/partitioner/vertical_even_partitioner.py
datasets/flwr_datasets/partitioner/vertical_size_partitioner.py
datasets/flwr_datasets/partitioner/vertical_size_partitioner_test.py

* column modification params in plural
* same argument types here and in VerticalEvenPartitioner 
* update incorrect docs hint types for VerticalEven and VerticalSizePartitioner
* handle case when the fractions (floats) don't sum up smoothly to 1.0 but are close

refactor(datasets) Make naming consistent in VerticalSizePartitioner

---

src/py/flwr/server/serverapp/app.py

`hash_run_id` is not set and will throw the error:
```
UnboundLocalError: cannot access local variable 'hash_run_id' where it is not associated with a value
```
This fix sets `hash_run_id` to `None` outside the `while` loop.

fix(framework) Fix `UnboundLocalError` for hashed run ID in `flwr-serverapp`

---

datasets/flwr_datasets/federated_dataset.py
datasets/flwr_datasets/preprocessor/divider.py

Flower datasets in 2 files still uses the Type Hinting Generics from typing module == `from typing import List, Tuple`
Update (as suggested by the formatter) the Type Hinting Generics from typing module to directly using standard collections (`dict`, `list`, ...)
As [PEP 585](https://peps.python.org/pep-0585/) suggests from python 3.9 the latter is possible seamlessly + the automatic change happens when using the formatting script.

refactor(datasets) Update type hinting generics based on typing module

---

.github/workflows/e2e.yml
e2e/e2e-scikit-learn/e2e_scikit_learn/client_app.py
e2e/e2e-scikit-learn/e2e_scikit_learn/utils.py
e2e/e2e-scikit-learn/pyproject.toml

The test was sourcing MNIST from `openml`. It has been replaced with MNIST from `HuggingFace` via `flwr-datasets`.

ci(framework:skip) Update dataset download source for `e2e-scikit-learn`

---

baselines/flwr_baselines/requirements.txt

fix(baselines:skip) Bump `black` version to 24.3.0

---

src/py/flwr/client/app.py
src/py/flwr/server/app.py
src/py/flwr/server/serverapp/app.py

Enabled the subprocesses to monitor the main process. If the main process exits due to `SIGKILL`, the subprocess will kill itself via `SIGKILL` too.
As the subprocess are `daemon` via `multiprocessing` library, this mechanism won't be triggered if the main process is killed by `SIGINT` / `SIGTERM` / `Ctrl+C` / etc.

feat(framework) Prevent zombie subprocesses when the main process receives `SIGKILL`

---

src/py/flwr/client/app.py
src/py/flwr/client/grpc_rere_client/connection.py
src/py/flwr/client/rest_client/connection.py
src/py/flwr/client/supernode/app.py

| Test Case                                                                 | Now | Previous
|---------------------------------------------------------------------------|-------------|-------------|
| Run SuperNode without SuperLink, then shut down SuperNode                 | ✅      | ☑️ |
| Run SuperNode with SuperLink, then shut down SuperNode                 | ✅      | ✅ |
| Run SuperNode with SuperLink, shut down SuperLink first, then SuperNode   | ✅      | ✅ |
| Run SuperNode with SuperLink, start a run, and shut down SuperNode during ClientApp execution | ✅      | ✅ |
| Run SuperNode with SuperLink, start a run, shut down SuperLink, and finally shut down SuperNode during ClientApp execution | ✅      | ☑️  |

feat(framework) Add connection cleanup for SuperNode graceful exit

---

src/py/flwr/cli/config_utils.py
src/py/flwr/cli/log.py
src/py/flwr/cli/login/login.py
src/py/flwr/cli/ls.py
src/py/flwr/cli/run/run.py
src/py/flwr/cli/stop.py
src/py/flwr/cli/utils.py

- Added `enable-user-auth` field to federation config to enable user auth feature or not. Default to `False`
- Required TLS when using user auth.

feat(framework) Add `enable-user-auth` field in TOML file and require TLS for user authentication

---

datasets/docs/source/recommended-fl-datasets-tables.rst

There was no entry in the recommended-fl-datasets table for datasets focused on aqueous solubility and multi-assay activity.
This PR adds two datasets extracted from ChEMBL to the recommended-fl-datasets table:
1. A dataset for aqueous solubility (chembl_aqsol).
2. A dataset for multi-assay activity (chembl_multiassay_activity).
No specific issue linked. This is an enhancement to improve dataset recommendations.
The addition of these datasets provides users with:
- Greater variety in datasets for Federated Learning (FL) experiments.
- Domain-specific data for drug discovery and related applications.

docs(datasets) Add two molecular datasets to `recommended-fl-datasets` table

---

framework/docs/source/conf.py
framework/docs/source/how-to-configure-logging.rst
framework/docs/source/index.rst
src/py/flwr/common/logger.py

Run as:
```shell 
(env) PYTHONLOGLEVEL=DEBUG flower-superlink --insecure
INFO 2025-01-27 09:58:35,460:      Starting Flower SuperLink
WARNING 2025-01-27 09:58:35,460:   Option `--insecure` was set. Starting insecure HTTP server.
INFO 2025-01-27 09:58:35,465:      Flower Deployment Engine: Starting Exec API on 0.0.0.0:9093
INFO 2025-01-27 09:58:35,469:      Flower ECE: Starting ServerAppIo API (gRPC-rere) on 0.0.0.0:9091
INFO 2025-01-27 09:58:35,473:      Flower ECE: Starting Fleet API (gRPC-rere) on 0.0.0.0:9092
DEBUG 2025-01-27 09:58:35,474:     Started flwr-serverapp scheduler thread.
DEBUG 2025-01-27 09:58:35,474:     Using InMemoryState
```

feat(framework) Set the log level via environment variable

---

src/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer.py

When logging requests/responses it's better to format them first using `MessageToDict()`. 
Before:
After:

refactor(framework) Improve formatting of DEBUG logs in FleetServicer

---

framework/docs/source/how-to-configure-logging.rst
src/py/flwr/common/logger.py

Renamed from `PYTHONLOGLEVEL` to `FLWR_LOG_LEVEL`

refactor(framework) Rename environment variable to control log level

---

src/py/flwr/cli/new/templates/app/README.md.tpl
src/py/flwr/cli/new/templates/app/pyproject.baseline.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.flowertune.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.huggingface.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.jax.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.mlx.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.numpy.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.pytorch.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.sklearn.toml.tpl
src/py/flwr/cli/new/templates/app/pyproject.tensorflow.toml.tpl

Updating versions in `flwr new` templates. In particular, if a `pyproject.toml` sets `torch`, we need a version that's compatible with `numpy2+`.

refactor(framework) Update package versions in templates

---

src/py/flwr/common/args.py
src/py/flwr/server/app.py

`uvicorn.run` and `requests.post` only accept paths to keys/certificates, instead of loaded bytes.

fix(framework) Fix issue preventing REST-based Fleet API from using SSL

---

src/py/flwr/common/constant.py
src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor.py

In cases of unsynchronized system time, the received timestamp may appear to be in the future relative to the server. In a test case, a Raspberry Pi was likely less than one second ahead of the SuperLink’s system time, causing the SuperLink to reject all its connections due to future timestamps.
Allows timestamps to be within the range (-2, 12) seconds instead of (0, 10) seconds.

refactor(framework) Add allowance for system time drift in the node authentication

---

dev/update_version.py
src/py/flwr/cli/auth_plugin/oidc_cli_plugin.py
src/py/flwr/cli/utils.py
src/py/flwr/common/constant.py
src/py/flwr/server/app.py

Rename constants so they don't include `_`. Using `_` isn't recommended when these keys travel in gRPC's metadata (https://www.grouparoo.com/blog/dont-use-underscores-in-http-headers).

refactor(framework) Rename constants for gRPC metadata keys for node auth / user auth

---

src/py/flwr/server/superlink/fleet/grpc_rere/server_interceptor.py

@jafermarq found that running `flwr ls` against a Fleet servicer results in an unauthenticated error triggered by the node authentication interceptor. A help message then appears, instructing users to run `flwr login`. This can be confusing, especially if the issue is simply due to a typo in the server address.  
The node authentication server interceptor now first checks whether the request is for the Fleet API. If it is not, a `FAILED_PRECONDITION` error is raised instead of `UNAUTHENTICATED`.

fix(framework) Avoid processing requests from non-FleetStub

---

framework/docs/locales/fr/LC_MESSAGES/framework-docs.po

Currently translated at 20.0% (830 of 4150 strings)
Translation: Flower Docs/Framework
Translate-URL: https://hosted.weblate.org/projects/flower-docs/framework/fr/

docs(framework) Fix weblate conflict for translation

---

src/py/flwr/cli/log_test.py

Since the `print_log` logic runs `print` once, the accompanying test needs to be updated. Only one call is expected.

fix(framework) Fix `flwr log` test

---

src/py/flwr/server/app.py

The `get_dashboard_server` cannot be imported currently, and is causing the auth plugin to break.

fix(framework) Remove dashboard plugin

---

src/py/flwr/common/object_ref.py

We added this feature (re-importing modules from the disk via reloading) when we still had `flower-server-app <module>:<app>` and `flower-client-app <module>:<app>`, so that changes in the code would be reflected.
This is no longer necessary, as we now always install apps with different hashes in separate folders. Additionally, reloading modules can cause issues, especially when a module cannot be imported twice (e.g., if the module initializes resources at the top level).

refactor(framework) Avoid reloading modules when an already imported module is imported again in the `load_app` function

---

src/py/flwr/cli/build.py

This PR introduces a change to sort the list of files before they are added to the zip archive. By sorting the files, we ensure that the order of files within the zip archive is consistent. This consistency is essential for producing the same hash value for the same set of files, regardless of the file system's order.

refactor(framework) Sort files in `flwrcli.build` before adding to zip to ensure consistent order

---

datasets/docs/source/conf.py
dev/build-docs.sh
dev/update-html-themes.py
examples/docs/source/conf.py
framework/docs/source/conf.py
intelligence/docs/source/conf.py

Moved the `html_theme_options` override to a `update-html-themes.py` script. The script will recursively update the `html_theme_options` dictionary in the following `conf.py`:
* `framework/docs/source/conf.py`
* `intelligence/docs/source/conf.py`
* `datasets/docs/source/conf.py`
* `examples/docs/source/conf.py`
* `baselines/docs/source/conf.py`
Web browser preview:
Mobile browser preview:

docs(*:skip) Add simpler theme update

---

src/py/flwr/client/message_handler/message_handler_test.py
src/py/flwr/common/message.py
src/py/flwr/server/utils/validator.py

To ease the migration of `LinkState` from `TaskIns/Res` to pure `Messages` we need to introduce this element in the metadata since it's the mechanism to determine whether a message has been pulled for processing or not.

refactor(framework) Introduce `delivered_at` in `Message` metadata

---

framework/docs/source/conf.py

PR to ensure the banner exists for `flower.ai/docs/framework`.

docs(framework:skip) Set banner for framework docs

---

src/py/flwr/server/driver/inmemory_driver_test.py
src/py/flwr/server/superlink/driver/serverappio_servicer_test.py

Add test that checks `Messages` are erased from `LinkState` once pulled

refactor(framework) Extend test for `ServerAppIo` servicer and `InMemoryDriver`

---

examples/fedrag/README.md

On `main`, Level 1 headers in the FedRAG `README.md` are currently rendered on `flower.ai/docs/examples`:
We want to display the titles of the examples only. This PR fixes it.

docs(framework) Fix heading levels in FedRAG `README.md`

---

.github/workflows/e2e.yml
.github/workflows/framework.yml

ci(framework) Skip E2E tests when no changes

---

intelligence/dev/bump.sh

ci(intelligence) Add version bumping script

---

intelligence/ts/src/flowerintelligence.ts

docs(intelligence) Improve TypeScript ref

---

intelligence/ts/examples/streaming/package.json
intelligence/ts/src/engines/common.ts
intelligence/ts/src/engines/engine.ts
intelligence/ts/src/engines/remoteEngine.ts
intelligence/ts/src/engines/transformersEngine.ts
intelligence/ts/src/engines/webllmEngine.ts
intelligence/ts/src/flowerintelligence.test.ts
intelligence/ts/src/flowerintelligence.ts

refactor(intelligence) Use engine name only in engines

---

intelligence/docs/source/index.rst

docs(intelligence) Add fetchModel explainer

---

intelligence/ts/examples/chat/app/page.tsx

Improves a padding issue on macos
instead of

Fix small padding issue

---

src/py/flwr/server/driver/grpc_driver.py
src/py/flwr/server/driver/inmemory_driver.py

We've implemented TTL mechanism in the SuperLink, and thus we don't need to log the warnings.

refactor(framework) Remove TTL warnings in `driver.create_message`

---

README.md
examples/flower-via-docker-compose/README.md
src/docker/base/README.md
src/docker/clientapp/README.md
src/docker/serverapp/README.md
src/docker/superlink/README.md
src/docker/supernode/README.md

There are a few README Markdown files with Flower logo URL broken. This PR fix it by using a current valid URL.
N/A
This PR updates the URL with a current valid one.
I was reading the repo documentation for Docker deployment and found a broken URL for the Flower's logo, then I did a search for other README Markdown files referencing the same URL. 
I think that would be a more robust change to have a `static` folder in the repo with a logo copy and using it as source.

docs(*:skip) Fix Flower logo URL in READMEs

---

framework/dev/test.sh

By default, `ruff` will respect any of the regular ignore files, like `.gitignore`. We want `ruff` to run on all files whether or not `.gitignore` is present.

fix(*:skip) Make `ruff` ignore `.gitignore`

---

examples/fl-dp-sa/fl_dp_sa/server_app.py

Avoid hard coding the number of `min_fit_clients` for the `fl-dp-sa` example

refactor(examples) Avoid hard coding `min_fit_clients` for the `fl-dp-sa` example

---

examples/flowertune-llm/flowertune_llm/client_app.py
framework/py/flwr/cli/new/templates/app/code/flwr_tune/client_app.py.tpl

There are typos in FlowerTune example and template `client_app.py` : `self.training_argumnets` .
Fixes #5271 
Rename `self.training_argumnets` to `self.training_arguments`
Omit.

fix(framework) Fix FlowerTune typos in example and template

---

.github/workflows/framework-e2e.yml

Currently, we run the wheel building and uploading only on framework changes, this can break the release process, as the process requires the artifacts from the latest commit on main in order to work, and if the latest commit didn't contain any framework changes, this won't work.

ci(framework) Fix wheel building

---

framework/docs/source/ref-changelog.md

This PR also fixes the URL in the last item. The URL should point to the `v1.18.0` version doc (not exist until release.)

refactor(framework:skip) Update the release date for `v1.18.0`

---

.github/workflows/ping-stale-under-discussion.yml

Can't dispatch workflow "Ping Stale Under Discussion Issues"
It is caused by already having declared it in `actions/github-issues@v6` workflow. 
#5257 
Remove `const fetch = require("node-fetch");` since it causes `SyntaxError: Identifier 'fetch' has already been declared`

ci(framework) Remove declaring const fetch, already in actions github-script v6

---

framework/py/flwr/common/constant.py
framework/py/flwr/common/serde.py
framework/py/flwr/common/serde_utils.py

If we want to reuse some of the serialization helpers in `serde.py` to inflate/deflate objects (e.g. so we could do `config_record_to_proto(self).SerializeToString(deterministic=True)` -- in the `.deflate()` of a `ConfigRecord` obj) we need to refactor the file in order to prevent circular imports.
The changes here proposed aren't sufficient to be able to call for example `config_record_to_proto()` from within the `ConfigRecord` class but almost (we can call the helper functions now moved to the `serde_utils.py`)

refactor(framework) Move utils functions out of `serde.py`

---

examples/advanced-pytorch/pyproject.toml
examples/app-pytorch/pyproject.toml
examples/embedded-devices/pyproject.toml
examples/fl-dp-sa/pyproject.toml
examples/fl-tabular/pyproject.toml
examples/flower-secure-aggregation/pyproject.toml
examples/flower-simulation-step-by-step-pytorch/my-awesome-app/pyproject.toml
examples/flowertune-vit/pyproject.toml
examples/opacus/pyproject.toml
examples/pytorch-federated-variational-autoencoder/pyproject.toml
examples/quickstart-fastai/pyproject.toml
examples/quickstart-pytorch-lightning/pyproject.toml
examples/quickstart-pytorch/pyproject.toml
examples/vertical-fl/pyproject.toml
examples/whisper-federated-finetuning/pyproject.toml

To address vulnerabilities found in `torch < 2.6.0`

refactor(examples) Bump version of `torch` and `torchvision` used in examples

---

framework/pyproject.toml

The latest version of `click` isn't compatible with the latest of `type`. We se an upper limit for `click`.

refactor(framework) Set upper limit for `click`

---

baselines/fedbn/pyproject.toml
baselines/feddebug/pyproject.toml
baselines/fedprox/pyproject.toml
baselines/fedrep/pyproject.toml
baselines/fjord/pyproject.toml
baselines/fjord/requirements.txt
baselines/hfedxgboost/pyproject.toml

Upgrade of `torch` (and `torchvision` if present) to 2.6 (and 0.21.0) as lower versions ( `torch< 2.6`) have a critical security vulnerability.
n/a
Bumping to correct versions in the relevant `pyproject.toml` files.
n/a

fix(baselines) Upgrade torch versions

---

framework/docs/source/docker/run-quickstart-examples-docker-compose.rst
framework/docs/source/docker/tutorial-deploy-on-multiple-machines.rst
framework/docs/source/docker/tutorial-quickstart-docker-compose.rst

Updated `src/` to `framework/` to reflect the latest(?) change in the repo.

docs(framework) Fix paths in docker docs

---

framework/docs/source/ref-simulation-deployment-runtimes.rst

- tweaked intro paragraph
- splitting `server-side` and `client-side` into two sections: about infrastructure, and about app execution

refactor(docs) Extend table comparing `Simulation` vs `Deployment` runtimes

---

framework/docs/source/ref-api-cli.rst
framework/py/flwr/supernode/cli/__init__.py
framework/py/flwr/supernode/cli/app.py
framework/py/flwr/supernode/cli/flower_supernode.py
framework/pyproject.toml

Following the structure of `flwr.cli` module, the `app.py` has been moved to the `cli` submodule in `supernode` and renamed to `flower_supernode.py` to match the CLI. The function has also been renamed to `flower_supernode` from `run_supernode`

refactor(framework) Move `flwr.supernode.app` to `flwr.supernode.cli.flower_supernode`

---

framework/py/flwr/supernode/start_client_internal.py

This PR also deletes `grpc_max_message_length` argument as it is no longer in use (it was used by `start_client` only).

refactor(framework) Centralize connection code in `start_client_internal.py`

---

framework/py/flwr/compat/client/app.py

The compat code in `compat.client.app` is to maintain backward compatibility for `start_client` API, which doesn't require `isolation` or a ClientAppIo gRPC server.
This removal allows easier modifications to the ClientAppIo.

refactor(framework) Remove unused code in `compat.client.app` to facilitate SuperNode refactoring

---

.github/workflows/label-pr-author.yaml

Bot PRs get labeled `Contributor` 
This is not accurate. 
Label bot PRs with new label `Bot` instead.

fix(framework) Add option to label bot PRs as Bot

---

framework/py/flwr/common/inflatable_grpc_utils.py
framework/py/flwr/common/inflatable_grpc_utils_test.py

- passing a `Node` -- this is required when these functions are executed by the `SuperNode` side.
- passing a list of object IDs to the push helper, so only those objects indicated by the `*Servicer` are pushed

refactor(framework) Update gRPC utils for `InflatableObjects`

---

framework/py/flwr/common/inflatable.py
framework/py/flwr/common/inflatable_test.py
framework/py/flwr/common/inflatable_utils.py

A new helper function is added that validates the structure of an Object content (`bytes`). This can be used in different places after merging (similarly to how the `validate_message` function is used)

feat(framework) Introduce validator function of object content

---

framework/py/flwr/common/inflatable.py
framework/py/flwr/common/inflatable_test.py
framework/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer.py
framework/py/flwr/server/superlink/fleet/grpc_rere/fleet_servicer_test.py
framework/py/flwr/server/superlink/serverappio/serverappio_servicer.py
framework/py/flwr/server/superlink/serverappio/serverappio_servicer_test.py
framework/py/flwr/supercore/object_store/in_memory_object_store.py
framework/py/flwr/supercore/object_store/object_store_test.py

- Make use of `validate_object_content` when pushing objects to either servicer. 
- The `check_body_len_consistency` function and associated tests have been removed. This function was introduced as a primitive consistency check for the object content. The check that this function performed (and the associated test) are captured by `validate_object_content` and its tests.

refactor(framework) Make use of new object content validator

---

framework/py/flwr/cli/ls.py
framework/py/flwr/cli/utils.py
framework/py/flwr/common/constant.py
framework/py/flwr/server/superlink/linkstate/in_memory_linkstate.py
framework/py/flwr/superexec/exec_servicer.py

fix(framework) Fix the CLI output for `flwr ls/stop/log` when run ID is not found

---

framework/py/flwr/server/app.py

The DashboardServicer is removed in favour of using the Exec API's `ListRuns` endpoint.

feat(framework) Remove `DashboardServicer`

---

framework/py/flwr/server/grid/grpc_grid.py
framework/py/flwr/server/superlink/linkstate/in_memory_linkstate.py
framework/py/flwr/server/superlink/serverappio/serverappio_servicer.py
framework/py/flwr/server/superlink/serverappio/serverappio_servicer_test.py

- The `InMemoryLinkState` now checks the existence of node ID before accessing it, avoiding raising `KeyError`
- SuperLink-generated error messages are now correctly stored in `ObjectStore`
- `ServerAppIoServicer.PullMessages` will not include message object ID unnecessarily in `object_ids_to_pull`

fix(framework) Fix bugs related to objects and node availability

---

.github/workflows/ping-stale-pr.yml
.github/workflows/ping-stale-under-discussion.yml

Sending GitHub info to one slack channel. 
Send to different ones. 
Change to direct to specific channel, leave token as secret.

ci(framework) Send GH info to correct Slack channel

---

README.md
dev/update-html-themes.py
framework/docs/source/conf.py

To increase awareness of our Flower AI Day 2025 in SF, this PR:
1. Adds a banner to the top of all of our framework docs.
2. Adds an additional link to `AI Day` at the top of this repository's `README.md`. 
The banner will look like this:

docs(*:skip) Add Flower AI Day 2025 banner to documentation and `README.md`

---

examples/pytorch-from-centralized-to-federated/pyproject.toml

Update dependency of `pytorch-from-centralized-to-federated` example as follows:
```
torch==2.6.0
torchvision==0.21.0
```

fix(examples) Update example dependency

---

framework/py/flwr/cli/utils.py
framework/py/flwr/superexec/exec_license_interceptor.py
framework/py/flwr/superexec/exec_license_interceptor_test.py
framework/py/flwr/superexec/exec_user_auth_interceptor.py
framework/py/flwr/superexec/exec_user_auth_interceptor_test.py

This PR improves the error message if permission is denied due to an expired license:
```shell
➜ flwr ls # same for `run`, `stop`, `log`
Loading project configuration...
Success
📄 Listing all runs...
❌ Permission denied.
❗️ License check failed. Please contact the SuperLink administrator.
```

refactor(framework) Improve user-facing error message when permission is denied

---

framework/py/flwr/common/record/array.py
framework/py/flwr/common/record/array_test.py

In the e2e-pandas tests, it always raises an error saying "Array must have children", which is not true if the array is like `Array(..., data=b"")`.

feat(framework) Allow empty `Array`

---

framework/py/flwr/cli/build.py

This fix is needed when executing `flwr run` from a Windows machine agains a `SuperLink` running Ubuntu.

fix(framework) Fix relative path generation during `FAB` build

---

framework/py/flwr/common/inflatable_utils.py
framework/py/flwr/common/inflatable_utils_test.py

This function can be used by the SuperNode to push object contents, without having to get all objects from the ObjectStore at one time.
This PR helps make #5606 smaller.

feat(framework) Add `push_object_contents_from_iterable` function

---

intelligence/kt/flwr/src/main/java/ai/flower/intelligence/Constants.kt
intelligence/kt/flwr/src/main/java/ai/flower/intelligence/RemoteEngine.kt
intelligence/kt/flwr/src/main/java/ai/flower/intelligence/Typing.kt

The OpenAI SDK uses SSE in chunk.
Update chunk processing to support server sent event to comply to OpenAI SDK.

feat(intelligence): Support server sent event chunk KT

---

framework/py/flwr/supernode/servicer/clientappio/clientappio_servicer_test.py

Update the `side_effect `from returning objects in a fixed order into a behaviour that returns the object specified in the request. This fix is needed to bring support for Python 3.13
close after merge: https://github.com/adap/flower/pull/5718

fix(framework): Fix test for `ClientAppIoServicer`

---

framework/py/flwr/simulation/app.py
framework/py/flwr/supercore/app_utils.py

refactor(framework): Remove `while` loop in `flwr-simulation` and remove `simple_get_token` util

---

framework/docs/source/ref-api-cli.rst

The `flower-simulation` is an internal command used by `flwr run` and therefore shouldn't be used in other contexts

docs(framework): Remove `flower-simulation` for CLI reference documentation

---

framework/e2e/test_control_api.sh
framework/e2e/test_serverapp_heartbeat.py
framework/py/flwr/server/app.py

break(framework): Deprecate `--executor*` arguments and introduce `--simulation` flag for `flower-superlink`

---

framework/py/flwr/serverapp/fedavg.py
framework/py/flwr/serverapp/strategy.py
framework/py/flwr/serverapp/strategy_utils.py
framework/py/flwr/serverapp/strategy_utils_tests.py

This PR introduces `InconsistentMessageReplies`, which is thrown if replies can't be aggregated. This exception is catched in the for loop of `<strategy>.start()` and it triggers a `flwr_exit` with code `SERVERAPP_STRATEGY_PRECONDITION_UNMET`

refactor(framework): Throw exception if consistency in replies is not met

---

framework/py/flwr/cli/new/new.py
framework/py/flwr/cli/new/templates/app/code/__init__.pytorch_msg_api.py.tpl
framework/py/flwr/cli/new/templates/app/code/client.pytorch_msg_api.py.tpl
framework/py/flwr/cli/new/templates/app/code/server.pytorch_msg_api.py.tpl
framework/py/flwr/cli/new/templates/app/code/task.pytorch_msg_api.py.tpl
framework/py/flwr/cli/new/templates/app/pyproject.pytorch_msg_api.toml.tpl

Adds a new template based on the `app-pytorch` example. It will be the second in the list.
> [!NOTE]
> Note global evaluation stage has been removed -- as we do with templates in general.

feat(framework): Add `PyTorch` `flwr new` template with `Message API`

---

examples/quickstart-pytorch/pytorchexample/server_app.py

fix(examples): Fix `quickstart-pytorch` example

---

examples/app-pytorch/app_pytorch/server_app.py
examples/quickstart-pytorch/pytorchexample/server_app.py
framework/docs/source/tutorial-quickstart-pytorch.rst
framework/py/flwr/cli/new/templates/app/code/server.pytorch_msg_api.py.tpl
framework/py/flwr/serverapp/strategy/result.py
framework/py/flwr/serverapp/strategy/strategy.py

examples and template have also been updated to remove the `pprint` lines.
Would look like:
```shell
INFO :      Strategy execution finished in 28.58s
INFO :
INFO :      Final results:
INFO :
INFO :          Global Arrays:
INFO :                  ArrayRecord (0.238 MB)
INFO :
INFO :          Aggregated Client-side Train Metrics:
INFO :          { 1: {'train_loss': '2.0984e+00'},
INFO :            2: {'train_loss': '2.0229e+00'},
INFO :            3: {'train_loss': '1.9634e+00'},
INFO :            4: {'train_loss': '1.8861e+00'},
INFO :            5: {'train_loss': '1.8315e+00'}}
INFO :
INFO :          Aggregated Client-side Evaluate Metrics:
INFO :          { 1: {'eval_acc': '1.2780e-01', 'eval_loss': '2.2512e+00'},
INFO :            2: {'eval_acc': '2.2110e-01', 'eval_loss': …
```

refactor(*:skip): Log `Result` at the end of strategy `start` execution

---

framework/py/flwr/serverapp/strategy/strategy_utils.py
framework/py/flwr/serverapp/strategy/strategy_utils_tests.py

When `np.array` objects with `ndim=0` get multiplied by a scalar, they get converted to a `np.float`. This type isn't compatible with `common.Array`. We therefore wrap the aggregation with `np.asarray` to retain the `np.array` representation after performing weighted aggregation.

refactor(framework): Perform aggregation with `np.asarray` wrapping

---

framework/e2e/test_reconnection.sh
framework/e2e/test_superlink.sh
framework/e2e/test_windows.sh

Now using `flwr ls` just like in https://github.com/adap/flower/pull/5842

ci(framework): Update CI tests to use `flwr ls` when checking for status of a run

---

framework/py/flwr/serverapp/strategy/fedavgm.py
framework/py/flwr/serverapp/strategy/fedprox.py
framework/py/flwr/serverapp/strategy/fedtrimmedavg.py
framework/py/flwr/serverapp/strategy/krum.py

refactor(framework): Use `│` instead of `|` to ensure consistency and make it prettier
